/**
 * Titans of War — Audio Catalog
 *
 * This is the source of truth for optional local archive recordings.
 * Files are intentionally not bundled here; drop verified public-domain or
 * permissively licensed recordings into /public/audio using these filenames.
 */

export const AUDIO_TRACK_LIBRARY = [
  {
    key: 'ambient_campfire',
    title: 'Campfire Ambience',
    src: '/audio/ambient_campfire.mp3',
    type: 'ambient',
    era: 'Archive ambience',
    mood: 'camp',
    bestFor: ['menu', 'letter', 'low-morale'],
    licenseStatus: 'verified-public-domain',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Barbecue.ogg',
    sourceInstitution: 'Wikimedia Commons / PDSounds',
    credit: 'Public-domain fire ambience by aldor via PDSounds/Wikimedia Commons.',
  },
  {
    key: 'lorena',
    title: 'Lorena',
    src: '/audio/lorena_instrumental.mp3',
    type: 'music',
    era: '1856',
    mood: 'melancholic',
    bestFor: ['low-morale', 'game-over', 'home-front'],
    licenseStatus: 'verified-public-domain',
    sourceUrl: 'https://citizen-dj.labs.loc.gov/items/loc-musicbox/20100929204929/',
    downloadUrl: 'https://s3.amazonaws.com/citizen-dj-assets.labs.loc.gov/audio/items/loc-musicbox/20100929204929.mp3',
    sourceInstitution: 'Library of Congress / Citizen DJ / American Folklife Center',
    credit: 'Trimmed from the Library of Congress Citizen DJ MusicBox recording, using the musical performance section beginning at 2:57; the LOC item states the recording is free to use and reuse.',
  },
  {
    key: 'lorena_alt',
    title: 'Lorena (Melancholic)',
    src: '/audio/lorena_melancholic.mp3',
    type: 'music',
    era: '1856',
    mood: 'elegy',
    bestFor: ['low-morale', 'appomattox_decision'],
    licenseStatus: 'recording-needed',
    sourceUrl: '',
    sourceInstitution: '',
    credit: 'Composition is public domain; verify the recording license before adding audio.',
  },
  {
    key: 'shenandoah',
    title: 'Shenandoah',
    src: '/audio/shenandoah.mp3',
    type: 'music',
    era: 'Traditional / 2017 USAF recording',
    mood: 'reflective',
    bestFor: ['letter', 'home-front', 'quiet-turn', 'low-morale'],
    licenseStatus: 'verified-public-domain',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Shenandoah_(2017)_-_Singing_Sergeants_-_United_States_Air_Force_Band.mp3',
    downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Shenandoah_%282017%29_-_Singing_Sergeants_-_United_States_Air_Force_Band.mp3',
    sourceInstitution: 'Wikimedia Commons / United States Air Force Band',
    credit: 'Public-domain Singing Sergeants performance via Wikimedia Commons; file metadata credits the official U.S. Air Force Public Domain Music catalog.',
  },
  {
    key: 'battle_cry',
    title: 'Battle Cry of Freedom',
    src: '/audio/battle_cry_brass.mp3',
    type: 'music',
    era: '1862',
    mood: 'martial',
    bestFor: ['high-morale', 'union-pressure', 'orthodox-campaign'],
    licenseStatus: 'verified-public-domain',
    sourceUrl: 'https://www.loc.gov/item/jukebox-25440/',
    sourceInstitution: 'Library of Congress National Jukebox / Victor Military Band',
    credit: '1917 public-domain U.S. band medley containing Battle Cry of Freedom; credit Library of Congress, National Jukebox.',
  },
  {
    key: 'march',
    title: 'When Johnny Comes Marching Home',
    src: '/audio/fife_drum_march.mp3',
    type: 'music',
    era: '1863',
    mood: 'march',
    bestFor: ['opening', 'movement', 'early-war'],
    licenseStatus: 'verified-public-domain',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:When_Johnny_Comes_Marching_Home_-_USMA_Band.ogg',
    downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/4/40/When_Johnny_Comes_Marching_Home_-_USMA_Band.ogg/When_Johnny_Comes_Marching_Home_-_USMA_Band.ogg.mp3',
    sourceInstitution: 'Wikimedia Commons / West Point Band',
    credit: 'Public-domain USMA/West Point Band performance via Wikimedia Commons.',
  },
  {
    key: 'battle_hymn',
    title: 'Battle Hymn of the Republic',
    src: '/audio/battle_hymn_triumphant.mp3',
    type: 'music',
    era: '1861',
    mood: 'solemn-triumphant',
    bestFor: ['high-morale', 'union-pressure', 'campaign-report', 'naval_technology'],
    licenseStatus: 'verified-public-domain',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Battle_Hymn_of_the_Republic,_Frank_C._Stanley,_Elise_Stevenson.ogg',
    sourceInstitution: 'Wikimedia Commons / Library of Congress',
    credit: '1908 public-domain recording by Frank C. Stanley and Elise Stevenson.',
  },
  {
    key: 'yellow_rose',
    title: 'The Yellow Rose of Texas',
    src: '/audio/yellow_rose_march.mp3',
    type: 'music',
    era: '1858',
    mood: 'southern-martial',
    bestFor: ['early-war', 'movement', 'gettysburg_decision'],
    licenseStatus: 'verified-public-domain',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Yellow_Rose_Of_Texas.ogg',
    sourceInstitution: 'Wikimedia Commons',
    credit: 'Rhythmic quickstep march recording via Wikimedia Commons.',
  },
  {
    key: 'dixie',
    title: 'Dixie Land',
    src: '/audio/dixie_instrumental.mp3',
    type: 'music',
    era: '1859 / 2023 Arrangement',
    mood: 'southern-martial',
    bestFor: ['high-divergence', 'hotspur', 'confederate-command'],
    licenseStatus: 'recording-needed',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Dixie_Land_(Instrumental_version).ogg',
    downloadUrl: '',
    sourceInstitution: 'Wikimedia Commons',
    credit: 'Composition is public domain; available CC-BY-SA recording is intentionally inactive for the MIT-code public release.',
  },
  {
    key: 'bonnie_blue_flag',
    title: 'The Bonnie Blue Flag',
    src: '/audio/bonnie_blue_flag_instrumental.mp3',
    type: 'music',
    era: '1861',
    mood: 'political-martial',
    bestFor: ['wolf', 'treasury', 'confederate-command'],
    licenseStatus: 'recording-needed',
    sourceUrl: '',
    sourceInstitution: '',
    credit: 'Composition is public domain; verify the recording license before adding audio.',
  },
  {
    key: 'tenting_tonight',
    title: 'Tenting Tonight on the Old Camp Ground',
    src: '/audio/tenting_tonight.mp3',
    type: 'music',
    era: '1863',
    mood: 'weary-camp',
    bestFor: ['letter', 'low-morale', 'winter-camps'],
    licenseStatus: 'verified-public-domain',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tenting_Tonight_on_Old_Camp_Ground.ogg',
    sourceInstitution: 'Wikimedia Commons',
    credit: 'Instrumental acoustic brass and guitar recording via Wikimedia Commons.',
  },
  {
    key: 'just_before_battle_mother',
    title: 'Just Before the Battle, Mother',
    src: '/audio/just_before_battle_mother.mp3',
    type: 'music',
    era: '1862',
    mood: 'melancholic',
    bestFor: ['letter', 'low-morale', 'wilderness'],
    licenseStatus: 'verified-public-domain',
    sourceUrl: 'https://www.loc.gov/item/jukebox-25959/',
    sourceInstitution: 'Library of Congress National Jukebox',
    credit: 'Haunting Civil War folk ballad depicting a soldier writing home on the eve of combat.',
  },
  {
    key: 'aura_lea',
    title: 'Aura Lea',
    src: '/audio/aura_lea.mp3',
    type: 'music',
    era: '1861',
    mood: 'reflective',
    bestFor: ['letter', 'home-front', 'quiet-turn'],
    licenseStatus: 'recording-needed',
    sourceUrl: '',
    sourceInstitution: '',
    credit: 'Composition is public domain; verify the recording license before adding audio.',
  },
  {
    key: 'home_sweet_home',
    title: 'Home, Sweet Home',
    src: '/audio/home_sweet_home.mp3',
    type: 'music',
    era: '1823',
    mood: 'homesick',
    bestFor: ['letter', 'morale-collapse', 'campaign-report'],
    licenseStatus: 'recording-needed',
    sourceUrl: '',
    sourceInstitution: '',
    credit: 'Composition is public domain; verify the recording license before adding audio.',
  },
  {
    key: 'elegy_final',
    title: 'Taps (Appomattox Elegy)',
    src: '/audio/elegy_final.mp3',
    type: 'music',
    era: '1874 official bugle call',
    mood: 'finale',
    bestFor: ['appomattox_decision', 'greensboro_convention', 'game-over'],
    licenseStatus: 'verified-public-domain',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Taps_on_bugle.ogg',
    sourceInstitution: 'Wikimedia Commons / U.S. Army Band',
    credit: 'Public-domain U.S. Army bugle performance via Wikimedia Commons.',
  },
  {
    key: 'distant_artillery',
    title: 'Distant Artillery Ambience',
    src: '/audio/distant_artillery_ambience.mp3',
    type: 'ambient',
    era: 'Archive ambience',
    mood: 'battlefield-distance',
    bestFor: ['battle', 'tactical-view', 'high-risk'],
    licenseStatus: 'recording-needed',
    sourceUrl: '',
    sourceInstitution: '',
    credit: 'Add a public-domain or CC0 ambience recording before shipping file playback.',
  },
];

export function getAudioTrackByKey(key) {
  return AUDIO_TRACK_LIBRARY.find((track) => track.key === key) || null;
}
