import { calculateCampaignScore, divergenceTier, summarizeCabinetCrises, summarizePoliticalEconomy } from './simulationEngine.js';
import { resolveScenarioMedia } from './mediaCatalog.js';
import { AUDIO_TRACK_LIBRARY } from './audioCatalog.js';

export function resolveExportMedia(scenarioId, scenarios = []) {
  const media = resolveScenarioMedia(scenarioId);
  if (media?.assetKey !== 'unknown' || !Array.isArray(scenarios)) {
    return media;
  }

  const scenario = scenarios.find((entry) => entry.id === scenarioId);
  if (!scenario?.image) {
    return media;
  }

  return {
    ...media,
    assetKey: `scenario_card_${scenarioId}`,
    src: scenario.image,
    title: `${scenario.title || scenarioId} Scenario Art`,
    kind: 'generated-art',
    caption: 'AI-created Titans of War scenario art for this campaign decision.',
    credit: 'Generated by Titans Forge for Titans of War',
    provenanceStatus: 'verified',
    license: 'MIT project media',
  };
}

function formatMediaEmbed(media, format) {
  if (!media?.src || media.assetKey === 'unknown') return '';
  if (format === 'markdown') {
    return `![${media.title}](${media.src})`;
  }
  const fileName = media.src.split('/').pop();
  return `![[${fileName}]]`;
}

function describeResourceState(value, goodLabel, badLabel) {
  return value > 50 ? goodLabel : badLabel;
}

export function buildCampaignChronicle(state, options = {}) {
  const generatedAt = options.generatedAt ? new Date(options.generatedAt) : new Date();
  const title = options.title || 'Titans of War — Alternate History Chronicles';
  const subtitle = options.subtitle || 'Bureau of Alternate Chronology // Grand Campaign Chapter';
  const mediaEmbedFormat = options.mediaEmbedFormat || 'obsidian';
  const includeMediaEmbeds = options.includeMediaEmbeds !== false;
  const scenarios = options.scenarios || [];

  const crisisSummary = summarizeCabinetCrises(state);
  const politicalEconomy = summarizePoliticalEconomy(state);
  const campaignScore = calculateCampaignScore(state);
  const divergenceState = divergenceTier(state.divergenceIndex);
  const usedMedia = [];
  const seenMedia = new Set();

  for (const entry of state.history || []) {
    const media = resolveExportMedia(entry.scenarioId, scenarios);
    if (media.assetKey === 'unknown' || seenMedia.has(media.assetKey)) continue;
    seenMedia.add(media.assetKey);
    usedMedia.push({
      assetKey: media.assetKey,
      src: media.src,
      title: media.title,
      kind: media.kind,
      caption: media.caption,
      credit: media.credit,
      scenarioId: entry.scenarioId,
    });
  }

  let markdown = `# ${title}\n`;
  markdown += `### *${subtitle}*\n\n`;
  markdown += `*Compiled automatically on ${generatedAt.toLocaleDateString()} ${generatedAt.toLocaleTimeString()}*\n\n`;
  markdown += `---\n\n`;
  markdown += `## 1. Faction and Telemetry Status at Campaign Conclusion\n\n`;
  markdown += `| Core Resource Indicator | Final Level | Threat / Security Status |\n`;
  markdown += `| :--- | :---: | :--- |\n`;
  markdown += `| Military Strength | ${state.metrics.militaryStrength}% | ${describeResourceState(state.metrics.militaryStrength, 'Strong unified corps.', 'Critically depleted standing force.')} |\n`;
  markdown += `| Munitions Stockpile | ${state.metrics.munitions}/100 | ${describeResourceState(state.metrics.munitions, 'Adequate supply buffers.', 'Severe ordnance starvation.')} |\n`;
  markdown += `| Treasury Reserves | ${state.metrics.treasury}/100 | ${describeResourceState(state.metrics.treasury, 'Stable sovereign backing.', 'Hyper-inflationary collapse.')} |\n`;
  markdown += `| Public Morale | ${state.metrics.publicMorale}% | ${describeResourceState(state.metrics.publicMorale, 'Home front stands firm.', 'Bread riots, draft resistance, and war-weariness spreading.')} |\n`;
  markdown += `| Divergence Index | ${(state.divergenceIndex * 100).toFixed(0)}% | ${divergenceState.label} — ${divergenceState.note} |\n\n`;

  markdown += `### Senate Political Shards Alignment\n`;
  markdown += `* Radical Attackers (Hotspur): ${state.shards.hotspur.alignment}% alignment | Influence weight: ${state.shards.hotspur.influence}\n`;
  markdown += `* Tactical Pragmatists (Fox): ${state.shards.fox.alignment}% alignment | Influence weight: ${state.shards.fox.influence}\n`;
  markdown += `* Diplomatic Strategists (Wolf): ${state.shards.wolf.alignment}% alignment | Influence weight: ${state.shards.wolf.influence}\n\n`;

  markdown += `### Strategic Stability Index\n`;
  markdown += `* Total score: **${campaignScore.total} / 1000** (${campaignScore.grade})\n`;
  markdown += `* Campaign outcome: **${campaignScore.survived ? 'Survived' : 'Collapsed'}**\n`;
  markdown += `* Ending class: **${campaignScore.endingClass}** — ${campaignScore.endingNote}\n`;
  markdown += `* Crisis management: **${campaignScore.crisisSummary.resolved}/${campaignScore.crisisSummary.faced}** crises resolved\n\n`;

  markdown += `### Cabinet Crisis Register\n`;
  markdown += `* Crises Faced: ${crisisSummary.faced}\n`;
  markdown += `* Crises Resolved in Council: ${crisisSummary.resolved}\n`;
  markdown += `* Crises Left Unresolved in the Record: ${crisisSummary.unresolved}\n`;
  markdown += `* Active Political Pressure at Campaign End: ${crisisSummary.activeAtEnd.length ? crisisSummary.activeAtEnd.map((entry) => `${entry.label} (${entry.alignment}%)`).join(', ') : 'None'}\n\n`;

  if (crisisSummary.entries.length > 0) {
    crisisSummary.entries.forEach((entry) => {
      markdown += `* Turn ${entry.turn}: **${entry.crisisLabel}** — ${entry.crisisResolved ? 'stabilized' : 'left unstable'} (${entry.crisisAlignmentBefore}% -> ${entry.crisisAlignmentAfter}%).\n`;
    });
    markdown += `\n`;
  }

  markdown += `### Political Economy Summary\n`;
  markdown += `* ${politicalEconomy.overview}\n`;
  politicalEconomy.summaryLines.forEach((line) => {
    markdown += `* ${line}\n`;
  });
  markdown += `* Dominant liabilities: ${politicalEconomy.dominantRisks.join(', ')}\n\n`;

  markdown += `---\n\n`;
  markdown += `## 2. Chronological Log of Divergences and Battles\n\n`;

  (state.history || []).forEach((entry) => {
    markdown += `### Turn ${entry.turn}: ${entry.date} — ${entry.scenarioTitle}\n`;
    const media = resolveExportMedia(entry.scenarioId, scenarios);
    if (includeMediaEmbeds) {
      const embed = formatMediaEmbed(media, mediaEmbedFormat);
      if (embed) {
        markdown += `${embed}\n\n`;
      }
    }
    markdown += `> **Operational Command**: *${entry.choiceText}*\n`;
    if (entry.choiceSucceeded !== null && entry.choiceSucceeded !== undefined) {
      markdown += `> **Tactical Dice Roll**: **${entry.choiceSucceeded ? 'SUCCESSFUL STRATEGIC BREAKTHROUGH' : 'STRATEGIC REJECT / FAILURE'}**\n`;
    }
    if (entry.crisisFor) {
      markdown += `> **Cabinet Crisis**: **${entry.crisisLabel}** — ${entry.crisisResolved ? 'temporarily stabilized' : 'still unstable after the session'}.\n`;
    }
    markdown += `>\n`;
    markdown += `> **Resolved Historical Consequence**: ${entry.consequence}\n\n`;
  });

  markdown += `---\n\n`;
  markdown += `## 3. Scholarly Alternate-History Post-Mortem Analysis\n\n`;
  markdown += `Based on the decisions made by the commander, this campaign timeline branched **${(state.divergenceIndex * 100).toFixed(0)}%** from the orthodox history.\n\n`;

  if (state.divergenceIndex > 0.4) {
    markdown += `> [!WARNING]\n`;
    markdown += `> **Branch Class**: *Severe Chronological Deviation.*\n`;
    markdown += `> The accumulation of non-orthodox choices has detached this continent from standard American historical progression. Re-anchoring to the standard chronological line is deemed mathematically impossible.\n\n`;
  } else {
    markdown += `> [!NOTE]\n`;
    markdown += `> **Branch Class**: *Tethered Semi-Orthodox Timeline.*\n`;
    markdown += `> Despite localized resource strains and tactical adjustments, the main operational milestones remained tethered to historical thresholds. Reconstruction will proceed along roughly standard timelines.\n\n`;
  }

  markdown += `---\n\n`;
  markdown += `## 4. Media Provenance & Curated Soundscapes\n\n`;
  markdown += `### Cartographic Assets & Campaign Visuals\n\n`;
  if (usedMedia.length === 0) {
    markdown += `* No scenario media was attached to this run.\n`;
  } else {
    usedMedia.forEach((media) => {
      markdown += `* **${media.title}** (${media.kind}) — \`${media.src}\`${media.credit ? ` — ${media.credit}` : ''}${media.caption ? ` — ${media.caption}` : ''}\n`;
    });
  }
  markdown += `\n`;

  markdown += `### Curated 19th-Century Soundscape Archives\n\n`;
  markdown += `The Grand Campaign is accompanied by highly authentic 19th-century musical scores and loops. Below is the historical catalog and scholarly sheet music references:\n\n`;

  AUDIO_TRACK_LIBRARY.forEach((track) => {
    if (track.licenseStatus === 'verified-public-domain') {
      markdown += `* **"${track.title}"** (${track.era}, ${track.mood}) — *${track.credit}*\n`;
      if (track.sheetMusicUrl) {
        markdown += `  * 🎼 **Scholarly Sheet Music & PDF Score**: [Access Score Page](${track.sheetMusicUrl})\n`;
      }
      if (track.sourceUrl) {
        markdown += `  * 📥 **Direct Archive Download**: [Access Audio Recording](${track.sourceUrl})\n`;
      }
      markdown += `\n`;
    }
  });

  const summary = `${campaignScore.survived ? 'Survived' : 'Collapsed'} through turn ${state.currentTurn} with SSI ${campaignScore.total}/${campaignScore.grade}, ${(state.divergenceIndex * 100).toFixed(0)}% divergence, and ${crisisSummary.resolved}/${crisisSummary.faced} cabinet crises resolved. Ending: ${campaignScore.endingClass}.`;
  const filename = options.filename || `Titans_of_War_Chronicle_Turn_${state.history.length}.md`;

  return {
    markdown,
    filename,
    usedMedia,
    summary,
    campaignScore,
    politicalEconomy,
  };
}
