// Titans of War — Historical Primers
//
// Topic-level sourced primers consulted in-game via an opt-in side panel.
// Scenarios point at primers by id through their `primerTags` array. Each
// primer carries the same fields the Titans Forge Social Science Rubric
// already evaluates on scenarios — a period_voice quotation, a power_analysis
// paragraph that frames the topic structurally (incentives, logistics,
// sectional interests), a complexity_note that shows where compromises broke
// down, and a sourceNotes line with real citations.
//
// These primers also feed the local Ollama prompt as ground-truth context
// for the topics tagged on the current turn, and they are recorded in the
// chronicle export so a run report shows which primers the player consulted.

export const HISTORICAL_PRIMERS = {
  naval_technology: {
    id: 'naval_technology',
    topic: 'Naval Technology — Ironclads, the Hunley, and Blockade Running',
    summary: `The Civil War converted shipbuilding from a craft tradition into a contested engineering race within eighteen months. The Confederate Navy raised the burned hull of the USS Merrimack at Norfolk, plated it in two layers of two-inch iron, and recommissioned her as the CSS Virginia. On March 8 1862 in Hampton Roads she rammed the Cumberland and burned the Congress. The next morning the Union ironclad USS Monitor — John Ericsson's low-freeboard, single-turret design — fought her to a draw, and wooden navies were effectively obsolete. The Western theater produced its own line of river ironclads (the City-class gunboats built by James Eads at Carondelet and Mound City), which let Foote, Porter, and Farragut convert the Mississippi into a Union highway. The Confederacy never matched Union industrial capacity for armor or marine engines, so it experimented at the edges: the H.L. Hunley, a hand-cranked submersible built in Mobile, sank the USS Housatonic off Charleston on February 17 1864 and was lost the same night. Blockade runners — fast shallow-draft steamers out of Wilmington, Charleston, and Galveston — moved cotton out and Enfield rifles, percussion caps, lead, and saltpeter in. By 1864 the Union blockade caught roughly one runner in three, but the surviving traffic still carried most of what kept Confederate ordnance bureaus in business.`,
    period_voice: `Lieutenant Catesby ap R. Jones, executive officer of the CSS Virginia, in his report of March 9 1862: "The Monitor lay at the bottom of Hampton Roads, an exceedingly formidable vessel; her single turret revolved while her hull was almost wholly submerged. Our shot glanced from her turret without effect." (OR Navies ser. 1 vol. 7 p. 60)`,
    power_analysis: `The decisive incentives were industrial, not tactical. The Union Navy could lay down twenty-two Passaic-class monitors in eighteen months because the Northern foundries, rolling mills, and machine shops existed; the Confederate Navy could not because they did not. Confederate ordnance officers chose torpedo warfare, spar-torpedo launches, and submersibles precisely because they were cheap and required few skilled marine engineers. The blockade itself ran on the same logic: a hundred Union warships could not seal three thousand miles of coast, but they could make insurance rates and crew wages high enough that the runners' profit margin pushed every voyage toward the highest-value cargo.`,
    complexity_note: `Both navies legitimately believed they were winning the technology race for most of 1862. The Virginia's first day broke the wooden Union fleet; the Monitor's second day broke the Virginia's aura. Each was right in part: ironclad-versus-ironclad combat at Hampton Roads, at the Head of Passes, and at Mobile Bay rarely produced clean victories. Where engineering told decisively was in the river campaigns and in the slow attritional pressure of the blockade — battles the wooden navies could not have fought at all.`,
    sourceNotes: `Official Records of the Union and Confederate Navies (OR Navies) ser. 1 vols. 6-7 (Hampton Roads), vol. 15 (Charleston and the Hunley), vol. 22-23 (Mississippi River squadrons); Battles and Leaders vol. I pp. 692-744 (Worden, Jones, Wood); Soley, The Blockade and the Cruisers (Scribner, 1883); Mahan, The Gulf and Inland Waters (Scribner, 1883); Scharf, History of the Confederate States Navy (Rogers and Sherwood, 1887).`,
    relatedScenarios: ['naval_technology', 'fort_sumter', 'antietam'],
  },

  cotton_diplomacy: {
    id: 'cotton_diplomacy',
    topic: `Cotton Diplomacy — British Cabinets, Lancashire Mills, and Russell's Neutrality`,
    summary: `The Confederate government bet, from the autumn of 1861 onward, that British and French textile capacity could not survive a sustained interruption of Southern cotton and that European intervention would follow. The economic premise was real: Lancashire mills consumed roughly seventy-five percent of their fiber from the American South, and a "cotton famine" did materialize through 1862-63, throwing operatives out of work in Manchester, Preston, and Blackburn. The political premise was wrong. Lord Palmerston's ministry — with Russell at the Foreign Office and Gladstone at the Exchequer — treated cotton as an industrial problem to be managed, not a casus belli. India, Egypt, and Brazil were brought online as substitute suppliers; Lancashire mill towns received public-works relief; and the diplomatic question turned on the battlefield rather than the loom. The Trent Affair in late 1861 brought the Royal Navy and the Union to the edge of war but ended in Seward's release of Mason and Slidell. After Antietam and the preliminary Emancipation Proclamation in September 1862, recognition became politically impossible: the Liberal cabinet would not be seen taking the slaveholders' side. By the end of 1863 the Laird rams had been seized and Confederate diplomatic strategy in Europe had effectively collapsed.`,
    period_voice: `Earl Russell, Foreign Secretary, to Lord Lyons (Washington), September 26 1862: "Her Majesty's Government cannot regard the events as yet justifying any proposition of mediation. They will wait to see if the prospect of a satisfactory result is sufficiently certain to warrant such a step." (British Sessional Papers, North America No. 1 (1863) p. 12)`,
    power_analysis: `British policy ran on three structural realities the Confederate cabinet kept underweighting. First, Lancashire was loud but Whitehall counted Liverpool ship-owners, Birmingham arms manufacturers, and Indian textile interests — all of whom benefited from the war continuing without intervention. Second, the Royal Navy could not protect a recognition decision against Union commerce raiders unless it was prepared to fight; the Admiralty estimated the convoy load and demurred. Third, anti-slavery sentiment in the Liberal coalition was not merely moral; it was a coalition-management problem inside the Cabinet, and the Emancipation Proclamation handed Russell and Gladstone a public reason to do what they already preferred.`,
    complexity_note: `Confederate envoys James Mason in London and John Slidell in Paris were not foolish to press their case. Through the autumn of 1862, the Palmerston ministry actively debated joint Anglo-French mediation, and Gladstone gave his famous "Jefferson Davis has made a nation" speech at Newcastle. Recognition was contingent, not impossible. But it was always contingent on Confederate battlefield success that did not arrive; Antietam, Vicksburg, and Gettysburg each removed it further from the table.`,
    sourceNotes: `British Sessional Papers, North America Nos. 1-3 (1862-1864); Adams, Charles Francis, "The Trent Affair" (American Historical Review 17, 1912); Owsley, King Cotton Diplomacy (University of Chicago Press, 1931); Henderson, The Civil War: A Soldier's View ch. 12; Lyons-Russell correspondence in PRO FO 5 series.`,
    relatedScenarios: ['antietam', 'second_manassas', 'potomac_leverage_campaign'],
  },

  conscription_substitution: {
    id: 'conscription_substitution',
    topic: 'Conscription, Substitution, and the Manpower Bargain',
    summary: `Both governments confronted the same arithmetic by spring 1862: voluntary enlistment alone could not replace battlefield losses and expiring terms. The Confederate Congress acted first, passing the Conscription Act of April 16 1862 and extending service for men already in the ranks. The Union followed with the Militia Act of July 1862 and the Enrollment Act of March 3 1863. Both systems permitted substitution and protected occupations considered necessary to government, transport, manufacturing, agriculture, and public order. The Confederate exemption for plantations with twenty or more slaves became a genuine political grievance, as did substitution on both sides. Yet the controversy should not obscure the scale of voluntary service or the social expectation that prominent families furnish officers and soldiers. Sons of substantial farmers, planters, merchants, and professional men served and suffered alongside men of smaller means; the argument was over unequal burdens within a society already mobilized on an extraordinary scale.`,
    period_voice: `President Jefferson Davis, December 26 1862: "It is no disgrace to be brought into the army by conscription. There is no more reason to expect from the citizen voluntary service in the army than to expect voluntary labor on the public roads or the voluntary payment of taxes." (The Papers of Jefferson Davis, vol. 8, pp. 565-84. Transcribed from the December 29, 1862, edition of the Memphis Appeal)`,
    power_analysis: `Conscription was first a logistical instrument. Enrollment officers needed county lists, militia rolls, medical examinations, camps of instruction, and railroad capacity; where those systems failed, the law produced evasion rather than soldiers. Governors Joseph E. Brown of Georgia and Zebulon Vance of North Carolina defended state officers, militia reserves, and essential workers against Richmond's demands. Plantation supervision also had a material rationale in food production and local control, even though the overseer exemption was easy to present as preference for wealth. Its political effect was larger than the number of men it exempted. A narrow exception could become a powerful symbol while most large slaveholding families still sent sons into service and sustained conspicuous losses.`,
    complexity_note: `The complaint of a "rich man's war and a poor man's fight" belonged to the period and cannot be dismissed, but neither should it be treated as a complete social description. Opposition varied sharply by state and locality; Virginia saw less agitation over the overseer law than several Deep South states. Substitution was an inherited military practice rather than a secret device invented for one class, and Congress repealed it when its political and administrative costs became too high. The important distinction is between a real controversy, its use by wartime opponents, and the much broader pattern of service, casualty, and family obligation across the white South.`,
    sourceNotes: `OR ser. 4 vols. 1-3 (Confederate conscription and exemption correspondence); Confederate Acts of April 16 and October 11 1862; U.S. Statutes at Large vol. 12 ch. 75 and ch. 201; Moore, Conscription and Conflict in the Confederacy (1924); Owsley, State Rights in the Confederacy (1925); household and service records should be used to test broad class claims against local evidence.`,
    relatedScenarios: ['black_confederate_debate', 'fredericksburg_winter_politics', 'petersburg_siege', 'five_forks'],
  },

  confederate_black_military_service: {
    id: 'confederate_black_military_service',
    topic: 'Black Military Service in the Confederacy — State Precedent, Army Labor, and 1865 Enlistment',
    summary: `Confederate policy in March 1865 emerged from a longer and uneven military history rather than appearing without precedent. In Louisiana, free men of color organized the Native Guard in 1861 under state militia authority, drawing on the local memory of free-colored service during the War of 1812. The unit paraded and offered service but was not accepted into the Confederate field army. Its removal from the militia occurred amid a general statutory reorganization, and it was briefly recalled as New Orleans faced capture. Across the Confederacy, a much larger number of freedmen and slaves accompanied armies or were impressed as teamsters, cooks, hospital workers, craftsmen, servants, laborers, and fortification hands. These roles became increasingly important as white manpower tightened, but they were not the same legal status as enlisted combat soldiers. By 1864-65, proposals by Patrick Cleburne, Jefferson Davis, Robert E. Lee, state politicians, editors, officers, and civilians turned that accumulated military dependence into a direct argument over armed enlistment.`,
    period_voice: `Lee's headquarters to Lieutenant General R. S. Ewell, March 27 1865: "As to the name of the troops, the general thinks you cannot do better than consult the men themselves." Lee accepted "colored," "Confederate troops," or "volunteers" according to the men's preference and directed that they receive the obligations and treatment of soldiers. (Charles Marshall for Lee, March 27 1865)`,
    power_analysis: `The development followed military function. Black labor already released white soldiers from wagons, hospitals, workshops, engineering details, and camp service; formal enlistment proposed converting part of that supporting manpower into armed formations. The obstacle was not merely battlefield confidence. Enlistment raised questions of owner consent, freedom for the recruit and possibly his family, state manumission law, pay, command, prisoner treatment, and the social meaning of military service. Congress could authorize Davis to accept men, but it could not by itself settle every property and emancipation question controlled by state law. Davis and the War Department therefore had to seek cooperation from governors, legislatures, owners, and army commanders if the act was to produce actual units rather than a paper authorization.`,
    complexity_note: `Three categories must remain separate. Louisiana's Native Guard was a real state militia formation of free men of color, but it did not become a Confederate combat regiment. Tens of thousands of black Southerners performed military labor and logistical work under circumstances ranging from personal attachment and paid employment to legal impressment and coercion, but that service did not automatically make them enlisted soldiers. Finally, the March 13 1865 act legally opened Confederate military service irrespective of color, and small companies began organizing in Richmond, but the authorization came too late to create a substantial field force. Recognizing the buildup prevents both errors: pretending nothing preceded March 1865 and retroactively turning all wartime support service into formal combat enlistment.`,
    sourceNotes: `New Orleans Crescent, April 27 1861, on the free-colored militia offer; OR ser. 4 vol. 1 p. 625 and Louisiana militia orders of 1861-62; Confederate act approved March 13 1865 and General Orders No. 14, March 23 1865; Journal of the Confederate Congress and Virginia legislative resolutions of March 1865; Lee-Hunter correspondence, January 1865; Charles Marshall for Lee to Ewell, March 27 1865.`,
    relatedScenarios: ['black_confederate_debate', 'petersburg_siege', 'richmond_evacuation'],
  },

  shiloh_western_theater: {
    id: 'shiloh_western_theater',
    topic: 'Shiloh and the Western Theater — Johnston, Corinth, and the Tennessee Line',
    summary: `Shiloh was the first battle that showed the war in the West would not be a sideshow. By April 1862 Union forces had taken Forts Henry and Donelson, opened the Tennessee and Cumberland river system, forced the evacuation of Nashville, and threatened the rail junction at Corinth, Mississippi. Albert Sidney Johnston concentrated the Army of Mississippi near Corinth and struck Grant at Pittsburg Landing on April 6. The first day nearly drove the Union army into the Tennessee River, but Confederate command control deteriorated in the woods and ravines, and Johnston was killed while personally directing the attack. Beauregard halted the evening assault short of the landing; Buell's Army of the Ohio arrived during the night; Grant counterattacked on April 7. The Confederates retreated to Corinth. The human cost shocked both sides, but the strategic result mattered more: the Confederacy never again had the same chance to stop the Union from turning the rivers, rails, and industrial towns of the lower West into a sustained invasion corridor.`,
    period_voice: `Albert Sidney Johnston's April 1862 correspondence before Shiloh treated the concentration at Corinth as a chance to recover Tennessee and restore initiative in the West; the Confederate reports after the battle instead record a retreat from Pittsburg Landing after Johnston's death and Buell's arrival.`,
    power_analysis: `The central fact at Shiloh was command cohesion under rail and river pressure. Johnston had the reputation, seniority, and Western credibility to hold a difficult coalition together: Bragg's discipline, Polk's political standing, Hardee's professional competence, and Beauregard's theater ambitions. Once he fell, the Western army kept bravery but lost the one figure who might have converted bravery into institutional coherence. The Union, by contrast, could absorb tactical surprise because its river logistics and reinforcement paths were stronger. Pittsburg Landing, Savannah, Corinth, and the Tennessee River were not just map labels; they were the material system deciding whether one army could be replaced and the other could not.`,
    complexity_note: `Shiloh was not simply a lost Confederate victory. Grant was surprised but not destroyed, and the Union river position gave him a recovery path even after a terrible first day. Johnston was not guaranteed to become a Western Lee had he lived; the theater's governors, rail shortages, and divided command geography were harder than Virginia's. But his death removed the best Confederate chance to make the Army of Tennessee a stable instrument before the West became a grinding strategic liability.`,
    sourceNotes: `OR ser. 1 vol. 10 pts. 1-2 (Shiloh reports of Grant, Buell, Beauregard, and Confederate subordinates); Grant, Personal Memoirs vol. I ch. 25; Johnston correspondence in Battles and Leaders vol. I pp. 465-608; Thomas L. Connelly, Army of the Heartland (1967); Wiley Sword, Shiloh: Bloody April (1974).`,
    relatedScenarios: ['shiloh_army_of_tennessee', 'chattanooga_stranglehold', 'chickamauga'],
  },

  shenandoah_valley_campaign: {
    id: 'shenandoah_valley_campaign',
    topic: 'The Shenandoah Valley — Granary, Corridor, and Washington Pressure',
    summary: `The Shenandoah Valley was both a military corridor and a supply district. Its northeast-southwest road net let Confederate forces move behind the Blue Ridge while threatening the Potomac line and Washington's political nerves. Its farms, mills, herds, and wagon routes also fed armies that Richmond could not easily supply from elsewhere. Jackson's 1862 Valley Campaign defeated or scattered separate Union columns under Banks, Fremont, and Shields, forcing Washington to retain forces for capital defense instead of sending them all to McClellan on the Peninsula. The same geography remained important in 1864, when Sigel, Hunter, Sheridan, and Early fought over whether the Valley would remain a Confederate breadbasket or become an exhausted corridor. Sheridan's later burning campaign targeted that material function directly: not merely enemy soldiers, but grain, barns, mills, forage, and livestock.`,
    period_voice: `Jackson's 1862 reports treated the Valley campaign as a contest over roads, stores, and separated Federal columns; Sheridan's 1864 dispatches later described the destruction of barns, mills, and forage as a deliberate way to deny the region to Confederate armies.`,
    power_analysis: `The Valley mattered because it converted geography into time. For Confederate commanders, a smaller army could use the Valley Pike, mountain gaps, and local knowledge to threaten larger Union plans indirectly. For Union commanders, every Confederate movement northward forced a calculation about Washington, Baltimore, the B&O Railroad, and public alarm. The material side was equally important: flour, cattle, horses, wagons, and fodder did not solve the Confederate economy, but losing them made every later campaign harder. A Valley victory that preserved stores was often worth more than a dramatic fight that left the barns empty.`,
    complexity_note: `The Valley was never a magic solution for the Confederacy. It could delay Union concentration, embarrass Washington, and feed armies, but it could not replace lost Western rivers or Northern industrial capacity. Union commanders were not foolish to burn and strip the district in 1864; by then the Valley's usefulness to Richmond had become a military fact. The hard question for the player is whether to treat the Valley as a battlefield legend or as a logistical system.`,
    sourceNotes: `OR ser. 1 vols. 12, 37, and 43 (Valley operations in 1862 and 1864); Henderson, Stonewall Jackson and the American Civil War vol. II; Hotchkiss, Make Me a Map of the Valley; Sheridan, Personal Memoirs vol. II; Freeman, Lee's Lieutenants vols. II-III.`,
    relatedScenarios: ['first_winchester', 'new_market', 'third_winchester', 'cedar_creek'],
  },

  emancipation_war_measure: {
    id: 'emancipation_war_measure',
    topic: 'Emancipation as War Measure — Manpower, Border States, and Europe',
    summary: `Lincoln's preliminary Emancipation Proclamation of September 22 1862 was issued after the Maryland Campaign gave the administration a battlefield position from which to act. The order deliberately exempted loyal slave states and occupied districts. Its legal form was military: slaves in areas still in rebellion would be declared free as a measure for suppressing rebellion. That form mattered because it tied emancipation to the commander-in-chief power, Union military necessity, and later recruitment. The policy carried political costs in parts of the North and among border-state Unionists, but it also made a clearer path for black enlistment after the Militia Act of 1862 and the later organization of United States Colored Troops. Diplomatically, it changed the British and French problem. Mediation or recognition could no longer be presented only as neutral settlement between belligerents; it now risked appearing as intervention against a government that had made slavery's destruction part of the war effort.`,
    period_voice: `Lincoln's preliminary proclamation declared that on January 1 1863 persons held as slaves in designated rebellious areas would be "then, thenceforward, and forever free."`,
    power_analysis: `The proclamation worked because it joined three interests that had been separate in 1861: military manpower, slave labor as Confederate war capacity, and European public opinion. Slave labor built fortifications, moved supplies, raised crops, and sustained the home front; striking that labor system weakened Confederate power without needing a battlefield victory everywhere at once. Black enlistment then converted policy into manpower. The border-state exemptions were not accidental weakness but coalition management. Lincoln could move only as fast as the war coalition, the army, and constitutional argument allowed.`,
    complexity_note: `The proclamation was neither pure humanitarian proclamation nor cynical politics. It was a war measure built from constitutional caution, military need, party pressure, and changing battlefield conditions. Abolitionists thought it too limited; many Democrats thought it dangerously radical; border-state Unionists feared it would break their coalition. Its strength was precisely that it made those conflicts serve a military object the administration could defend.`,
    sourceNotes: `Lincoln, Preliminary Emancipation Proclamation, Sept. 22 1862; Final Emancipation Proclamation, Jan. 1 1863; OR ser. 3 vol. 2 pp. 407-409; Lincoln, Annual Message to Congress, Dec. 1 1862; Salmon P. Chase diary entries on the cabinet debates; Nicolay and Hay, Abraham Lincoln: A History vol. VI.`,
    relatedScenarios: ['emancipation_cabinet_debate', 'antietam', 'black_confederate_debate'],
  },

  impressment_bread_riots: {
    id: 'impressment_bread_riots',
    topic: 'Impressment, Bread Riots, and Civil-Military Strain on the Home Front',
    summary: `Confederate logistics depended on impressment — the legal seizure of food, forage, slaves, wagons, and rolling stock from civilians for military use, with payment in increasingly worthless Confederate currency. The Impressment Act of March 26 1863 standardized prices well below market levels and authorized army quartermasters to take what they needed against compensation certificates. The economic consequence was predictable: farmers withheld stock from the market or sold under the table, urban food supplies tightened, and currency confidence collapsed faster than military reverses alone would have produced. The most visible eruption was the Richmond Bread Riot of April 2 1863, when several hundred women — many of them soldiers' wives — gathered at Capitol Square, marched on the commercial district, and broke into shops on Cary and Main Streets demanding bread, bacon, and shoes. President Davis personally addressed the crowd from a wagon, threw the contents of his pockets telling them it was all he had and later warning them force would be used if they didn't disperse. Similar riots followed in Mobile, Atlanta, Salisbury (North Carolina), and Petersburg through 1863-64. Governor Vance of North Carolina and Governor Brown of Georgia repeatedly clashed with Richmond over impressment, conscription, and habeas corpus suspension, arguing that the Confederate central government was destroying the state authority on which secession had been founded.`,
    period_voice: `Sara Pryor, Richmond resident, on the bread riot of April 2 1863: "A face passed me, so deathly in its sharp anguish, framed in its tangled mass of black hair, that I went after the woman and touched her shoulder. She turned her face and I saw it stamped with the brand of starvation." (Pryor, Reminiscences of Peace and War, Macmillan, 1904, p. 237)`,
    power_analysis: `Impressment broke because it tried to bypass the price system without commanding the political authority to do so. Confederate quartermasters paid certificates redeemable in depreciated currency at prices set by commissioners under conditions that effectively confiscated property. Farmers, millers, and slaveholders responded the way people in any market respond to confiscation: they hid stock, refused contracts, and shifted to barter. The bread riots were the urban consequence of a rural withholding pattern. Vance and Brown's defense of state authority was simultaneously a defense of their own political coalitions — yeoman farmers, militia officers, and county courts — and a structural correction the Confederate Congress was too weak to impose on itself.`,
    complexity_note: `The Davis government was not unfeeling. Confederate commissary general Lucius Northrop genuinely tried to build a working supply system out of disintegrating rail lines and inflated currency; he was scapegoated for problems no commissary general could have solved. The bread rioters were not entirely innocent: contemporary witnesses (including Mary Chesnut and Judith McGuire) noted that some of the looting moved past food into jewelry and silks before the militia restored order. The episode is most accurately read as a stress test the Confederate political economy failed by 1863, two years before the armies did.`,
    sourceNotes: `OR ser. 4 vol. 2 pp. 469-485, 707-720 (impressment correspondence and Northrop reports); Richmond Examiner and Richmond Whig, April 3-7 1863; Chesnut, A Diary from Dixie (Appleton, 1905) entries for April 1863; McGuire, Diary of a Southern Refugee (Hale, 1867); Vance and Brown gubernatorial correspondence in Hamilton (ed.), Papers of Zebulon Baird Vance vols. 1-2.`,
    relatedScenarios: ['fredericksburg_winter_politics', 'petersburg_siege', 'black_confederate_debate'],
  },

  border_state_bargain: {
    id: 'border_state_bargain',
    topic: 'The Border-State Bargain — Kentucky Neutrality, Maryland Under Arms, Missouri in Flames',
    summary: `The border states — Maryland, Kentucky, Missouri, and (after 1863) West Virginia — were the war's most important political prize and its most awkward strategic terrain. Lincoln told a visitor in September 1861 that he hoped to have God on his side but he must have Kentucky. The arithmetic was concrete: Kentucky controlled the Ohio River; Maryland surrounded Washington on three sides and held the rail link to the Northeast; Missouri commanded the upper Mississippi and the trans-Mississippi gateway. Maryland was held in the Union by force and political maneuver in April 1861 — General Butler's occupation of Baltimore, the suspension of habeas corpus, and the arrest of secessionist legislators before they could meet. Kentucky's legislature declared neutrality in May 1861 and held that posture until Confederate General Leonidas Polk's occupation of Columbus on September 3 broke it; Kentucky then formally aligned with the Union, and the Confederacy lost the Ohio-river line it had counted on. Missouri descended into a guerrilla war (Quantrill, Anderson, the Lawrence Massacre of 1863) that lasted longer than the conventional conflict and was not fully suppressed until 1865. West Virginia separated from Virginia under Wheeling convention authority in 1861-63 and entered the Union as a state on June 20 1863.`,
    period_voice: `President Lincoln to Senator Orville Browning, September 22 1861, on the importance of Kentucky: "I think to lose Kentucky is nearly the same as to lose the whole game. Kentucky gone, we cannot hold Missouri, nor, as I think, Maryland. These all against us, and the job on our hands is too large for us." (Lincoln, Collected Works vol. IV p. 532)`,
    power_analysis: `Border-state politics ran on a structure both governments understood: a planter or commercial elite often sympathetic to secession, a Unionist mountain or commercial counter-elite, and a large body of farmers whose loyalty was conditional on which army was nearer and which government was less abusive. Maryland's commercial connections to Philadelphia and New York gave the Unionists a structural majority once the spring 1861 crisis was contained by federal force. Kentucky's neutrality was a real political bargain — Magoffin meant it — that survived precisely until a Confederate general violated it militarily. Missouri broke earlier because Lyon's seizure of Camp Jackson and Frémont's emancipation proclamation forced everyone to pick sides before the bargain could be made. The Confederacy's structural error was treating border-state sympathy as identity rather than as a conditional coalition that required not provoking the conditions.`,
    complexity_note: `Lincoln's border-state policy was not cynical; it was the deliberate management of a coalition that would have collapsed if pushed faster. The revocation of Frémont's August 1861 emancipation order in Missouri, the delay of the Emancipation Proclamation until after Antietam, the exemption of border states from its terms, and the compensated-emancipation proposals of 1862 were all designed to keep the border-state coalition in place while the war's political center of gravity moved. By 1864 he could pay the bill — Maryland adopted a new state constitution abolishing slavery in November 1864, and Missouri followed in January 1865 — but only because the earlier coalition management had bought the time.`,
    sourceNotes: `OR ser. 1 vol. 2 (Maryland April 1861), vol. 4 (Kentucky neutrality and Columbus), vol. 3 and vol. 8 (Missouri Camp Jackson and Wilson's Creek); Lincoln Collected Works vols. IV-V (Basler ed.); Coulter, The Civil War and Readjustment in Kentucky (University of North Carolina Press, 1926); Channing, A History of the United States vol. VI ch. 12; Nevins, The War for the Union vol. I ch. 3-4.`,
    relatedScenarios: ['fort_sumter', 'radical_republican_crisis', 'manassas_battlefield'],
  },

  copperhead_politics: {
    id: 'copperhead_politics',
    topic: 'Copperhead Politics — Vallandigham, Seymour, and the Peace Democratic Press',
    summary: `The Peace Democrats — called Copperheads by their Republican opponents, after the venomous snake — were never a unified party. They were a faction of the Northern Democratic coalition that grew strong in the Old Northwest (Ohio, Indiana, Illinois) and held real power in New York under Governor Horatio Seymour. Their core argument was constitutional rather than pro-Confederate: that the war as Lincoln was prosecuting it — habeas corpus suspension, emancipation, conscription, military arrests of civilians — exceeded federal authority and was destroying the republic the Union was supposedly fighting to preserve. Their most prominent voice was Clement L. Vallandigham of Ohio, arrested by General Burnside in May 1863 under General Order No. 38 for a speech at Mount Vernon, tried by military commission, exiled to the Confederacy by Lincoln's order, and from there making his way to Canada to run for governor of Ohio in absentia (he lost). Copperhead press organs — the Chicago Times, the New York Daily News, the Columbus Crisis — pushed for negotiated settlement and amnesty for resistance to conscription. The faction peaked in 1863 and at the Chicago Democratic convention of August 1864, which adopted Vallandigham's "war is a failure" peace plank as the party platform while nominating General George McClellan, who repudiated it.`,
    period_voice: `Clement L. Vallandigham, speech in the House of Representatives, January 14 1863: "I see more of barbarism and sin, a thousand times, in the continuance of this war, the dissolution of the Union, the breaking up of the government, and the enslavement of the white race, than I have seen, or read of, under the most cruel features of African servitude in the South." (Congressional Globe, 37th Cong., 3rd Sess., Appendix p. 52)`,
    power_analysis: `Copperhead strength was a function of three structural conditions: war weariness that intensified with casualty lists, the Lincoln administration's genuinely aggressive use of executive power against civilians, and the economic geography of the Ohio Valley, whose river commerce had run south for two generations and which felt the loss more sharply than New England. Seymour and Vallandigham were rational politicians responding to real constituent grievances; they were not Confederate agents, though Confederate agents in Canada (Thompson, Clay) did try to use them. The faction's ceiling was set by the war's actual military trajectory: Vicksburg and Gettysburg in July 1863 broke the peace argument's strongest case, and the fall of Atlanta on September 2 1864 broke it in time to deliver the November election to Lincoln by 212 electoral votes to 21.`,
    complexity_note: `Lincoln's government overreacted to the Copperheads at times — the Vallandigham military commission was constitutional thin ice that even Lincoln found awkward to defend, and his commutation of the sentence to banishment was a tacit acknowledgment. But the Copperheads also overestimated how much of the Union electorate shared their reading. The 1864 vote — including a roughly 78 percent vote for Lincoln among Union soldiers — is the cleanest available test of the proposition, and it failed.`,
    sourceNotes: `Congressional Globe, 37th and 38th Congresses; OR ser. 2 vol. 5 (Vallandigham arrest correspondence); Klement, The Copperheads in the Middle West (University of Chicago Press, 1960) for primary-source reconstruction; New York World, Chicago Times, and Columbus Crisis editorials 1862-64; Lincoln, Collected Works vol. VI (Basler ed.); McClure, Recollections of Half a Century (Salem Press, 1902) ch. on the 1864 election.`,
    relatedScenarios: ['antietam', 'fredericksburg_winter_politics', 'potomac_leverage_campaign'],
  },

  atlanta_campaign_1864: {
    id: 'atlanta_campaign_1864',
    topic: 'Atlanta Campaign — Johnston, Hood, Railroads, and the Election Clock',
    summary: `The Atlanta Campaign was a military campaign inside an election year. Sherman advanced from Chattanooga in May 1864 with three armies and a rail supply line running back through Nashville and Louisville. Joseph E. Johnston repeatedly used ridges, river crossings, and rail junctions to slow him without risking the destruction of the Army of Tennessee. Davis and many Confederate critics saw this as surrendering Georgia by inches; Johnston saw it as preserving the only field army that could keep Atlanta from falling before Northern politics broke. In July Davis replaced Johnston with John Bell Hood, whose attacks at Peachtree Creek, Atlanta, and Ezra Church failed to stop Sherman and cost men the Confederacy could not replace. Atlanta fell on September 2 1864. The military result became a political event: it restored Northern confidence, undercut the Democratic claim that the war had failed, and helped Lincoln carry the November election.`,
    period_voice: `Lincoln's sealed memorandum of August 23 1864 recorded his expectation that his administration might not be re-elected; Sherman's September telegram that Atlanta was taken changed that political calculation almost immediately.`,
    power_analysis: `Atlanta mattered because railroads, workshops, and timing converged. Sherman did not need to annihilate Hood; he needed to keep his rail lifeline open and take the city before the election. Johnston did not need to win a Napoleonic battle; he needed to deny Sherman a political result long enough for Northern war weariness to mature. Hood's offensives answered Richmond's demand for action but spent the army's remaining offensive capital. The campaign shows why strategy and politics cannot be separated in 1864: a city, a rail hub, and a campaign calendar became one instrument.`,
    complexity_note: `Johnston's policy was not cowardice, and Hood's policy was not irrational bravery. Johnston's retreat strategy risked losing Atlanta without imposing enough pain; Hood's attacks tried to restore initiative before the city became politically fatal. Davis faced a real command problem either way. The player should feel that tension: delay can be strategically brilliant, but only if it actually buys the right kind of time.`,
    sourceNotes: `OR ser. 1 vols. 38-39 (Atlanta Campaign reports and correspondence); Sherman, Memoirs vol. II; Hood, Advance and Retreat; Johnston, Narrative of Military Operations; Lincoln, Collected Works vol. VII; Castel, Decision in the West (1992); Channing, A History of the United States vol. VI.`,
    relatedScenarios: ['atlanta_election_pressure', 'fall_of_atlanta', 'chattanooga_stranglehold', 'southern_independence_1864'],
  },

  trent_affair: {
    id: 'trent_affair',
    topic: 'The Trent Affair — Wilkes, Seward, Russell, and the November 1861 Brink',
    summary: `On November 8 1861 Captain Charles Wilkes of the USS San Jacinto stopped the British mail packet RMS Trent in the Bahama Channel, fired a shot across her bow, sent a boarding party, and removed Confederate envoys James Mason and John Slidell, who were en route to London and Paris to press for European recognition. The boarding was conducted without orders. Wilkes was greeted in Boston as a hero, and the House of Representatives voted him a gold medal. The British response was the opposite: Palmerston's cabinet demanded the envoys' release and an apology, the Royal Navy reinforced the North American Station, eleven thousand troops were ordered to Canada, and Lord Lyons in Washington was authorized to break diplomatic relations if Seward did not comply within seven days. The crisis lasted six weeks. Prince Albert, in one of his last acts before his death on December 14, softened the original British dispatch to give Seward room to retreat without humiliation. On December 26 1861 Seward formally released Mason and Slidell, conceding that Wilkes had failed to follow correct prize procedure: he should have brought the Trent into port for adjudication rather than removing passengers on the high seas. The envoys reached Europe in January 1862 and accomplished essentially nothing.`,
    period_voice: `Secretary of State William H. Seward to Lord Lyons, December 26 1861: "If the safety of the Union required the detention of the captured persons, it would be the right and duty of this government to detain them. But the effectual check and waning proportions of the existing insurrection, as well as the comparative unimportance of the captured persons themselves, when dispassionately weighed, happily forbid me from resorting to that defense." (Diplomatic Correspondence 1861 p. 297)`,
    power_analysis: `The Trent Affair revealed the structural ceiling on European intervention more clearly than any single document of the war. Britain could and would mobilize for a fight over maritime rights; it would not mobilize for the Confederacy as such. Palmerston's cabinet treated the boarding as a violation of the law of nations Britain itself had insisted on for two centuries, not as an opportunity to break the blockade. Seward's release, framed as a vindication of Anglo-American principles on neutral shipping, let both governments retreat from a war neither wanted. The Confederate diplomatic strategy lost what should have been its high-water moment: Mason and Slidell arrived in London and Paris diminished, having been bargained over rather than welcomed.`,
    complexity_note: `Wilkes' boarding was popular in the North precisely because it satisfied a legitimate grievance — the Royal Navy's wartime stop-and-search practices in the Napoleonic era had been a casus belli for the War of 1812. Seward's release was politically expensive: he absorbed the unpopularity to preserve the larger Union war effort. The episode is most accurately read not as a Union climbdown but as a deliberate trade — one captain's prize for the British neutrality the blockade required.`,
    sourceNotes: `Diplomatic Correspondence of the United States 1861-1862 (Department of State, 1862); British Sessional Papers, North America No. 1 (1862); Adams, "The Trent Affair" (American Historical Review 17, 1912); Bemis (ed.), The American Secretaries of State and Their Diplomacy vol. VII (Seward); Russell-Lyons correspondence in PRO FO 5 series; Channing, A History of the United States vol. VI ch. 11.`,
    relatedScenarios: ['fort_sumter', 'antietam', 'naval_technology'],
  },

  election_of_1864: {
    id: 'election_of_1864',
    topic: `The Election of 1864 — McClellan, the Soldier Vote, and Sherman's Timing`,
    summary: `The presidential election of November 8 1864 was the only national vote held during the war and the closest the Confederacy came to political victory after Gettysburg. Through the summer of 1864 Lincoln himself believed he would lose. The Overland Campaign had cost roughly 55,000 Union casualties between May and June without ending Lee's army. Grant was locked into the siege at Petersburg. Sherman was stalled outside Atlanta facing Joseph E. Johnston's prepared lines. The Republicans had nominated Lincoln in June at Baltimore on a "National Union" ticket with Andrew Johnson of Tennessee for vice president, a deliberate gesture toward War Democrats. The Democrats met at Chicago on August 29-31 and adopted a platform with two contradictory planks: a peace plank written by Vallandigham declaring the war a failure and demanding immediate cessation of hostilities, and a candidate, General George B. McClellan, who repudiated the peace plank in his acceptance letter of September 8. The two events that broke the deadlock were the fall of Atlanta on September 2 and Sheridan's decisive victory at Cedar Creek on October 19. Lincoln carried 22 of 25 participating states, 212 electoral votes to McClellan's 21, and 55 percent of the popular vote. Union soldier voting — counted separately under state laws that permitted it — ran roughly 78 percent for Lincoln, a verdict the peace Democrats had not anticipated.`,
    period_voice: `Lincoln, memorandum sealed and held by his cabinet, August 23 1864: "This morning, as for some days past, it seems exceedingly probable that this Administration will not be re-elected. Then it will be my duty to so co-operate with the President elect, as to save the Union between the election and the inauguration; as he will have secured his election on such ground that he can not possibly save it afterwards." (Lincoln, Collected Works vol. VII p. 514)`,
    power_analysis: `The political arithmetic of 1864 ran on a structural fact the Confederate cabinet kept missing: Lincoln did not need to win battles, he needed to win one before November. Atlanta was that battle. Sherman's telegram to Halleck on September 3 — "So Atlanta is ours, and fairly won" — converted the entire Northern political conversation in seventy-two hours. War Democrats who had been edging toward McClellan returned to the fold. Republican state organizations that had been preparing for defeat reorganized for turnout. The soldier vote, which both campaigns had spent the summer trying to capture, broke decisively for the administration that was visibly winning. The Confederate political strategy — wait out Northern war weariness — was sound; it failed because the strategic timing required holding out two more months than it could.`,
    complexity_note: `McClellan was not the peace candidate his platform implied. His acceptance letter explicitly rejected the Vallandigham plank and committed him to restoring the Union as a condition of any settlement. Had he won, the most likely outcome was probably an attempt at negotiated reunion on more lenient terms toward the planter class, not Confederate independence. The Chicago platform's contradiction reflected a genuine Democratic split that the war's conduct continued to widen. The election's clarity in retrospect should not obscure how genuinely close the political calculation looked from late July to early September 1864.`,
    sourceNotes: `Lincoln, Collected Works vols. VII-VIII (Basler ed.); McClellan, McClellan's Own Story (Webster, 1887); Nicolay and Hay, Abraham Lincoln: A History vol. IX (Century, 1890); Channing, A History of the United States vol. VI ch. 16; Nevins, The War for the Union vol. IV ch. 4-6; McClure, Recollections of Half a Century (Salem Press, 1902); contemporary New York Tribune, New York World, and Springfield Republican coverage, August-November 1864.`,
    relatedScenarios: ['fall_of_atlanta', 'election_1864_lincoln', 'election_1864_mcclellan', 'petersburg_siege'],
  },

  concurrent_majority_settlement: {
    id: 'concurrent_majority_settlement',
    topic: 'Concurrent Majority and Settlement — Calhoun, McClellan, and Conditional Reunion',
    summary: `John C. Calhoun's concurrent majority theory argued that a numerical national majority should not be able to govern a distinct sectional interest without that section's constitutional consent. By the Civil War, secession had moved beyond that theory into armed separation, but the idea remained useful for alternate settlement logic: a reunited Union might be restructured so that sectional sovereignty, slavery settlement, state authority, or reconstruction terms required concurrent consent rather than ordinary majority rule. In 1864 this was not the same as Confederate independence. George B. McClellan opposed Lincoln's conduct of the war and accepted nomination on a Democratic platform containing a peace plank, but his own acceptance letter rejected disunion and made restoration of the Union the object. A McClellan victory would more plausibly have opened a fight over armistice, reunion terms, constitutional guarantees, and Democratic coalition management than delivered automatic Southern independence.`,
    period_voice: `McClellan's September 8 1864 acceptance letter rejected disunion as the object of negotiation while condemning the administration's conduct of the war; Calhoun's earlier theory supplied a vocabulary for sectional consent rather than separation alone.`,
    power_analysis: `The useful distinction is between independence, armistice, and conditional reunion. Independence required military success, foreign recognition, and Northern political collapse at the same time. An armistice required less, but still needed enforcement and political will in Washington. Conditional reunion required the least battlefield miracle, but the most constitutional bargaining. A concurrent-majority settlement would not be easy to ratify, but it gives the game a historically intelligible alternate path: not "the South wins because McClellan wins," but "a different Union is proposed because the war coalition fractures."`,
    complexity_note: `This route should remain difficult. Calhoun's theory was not a neutral engineering fix; it was designed to protect sectional interests that ordinary majority rule threatened. McClellan was not Vallandigham, and peace Democrats were not the whole Democratic Party. Any settlement through him would have faced Congress, state ratification, soldiers in the field, emancipation policy, and Republican resistance. That makes it a plausible alternate-history negotiation, not an easy victory condition.`,
    sourceNotes: `Calhoun, A Disquisition on Government (1851); Democratic Party Platform of 1864; George B. McClellan acceptance letter, Sept. 8 1864; Lincoln, Collected Works vol. VII; Nevins, The War for the Union vol. IV; Foote, The Civil War vol. III; McClellan, McClellan's Own Story.`,
    relatedScenarios: ['southern_independence_1864', 'appomattox_decision', 'greensboro_convention'],
  },

  civil_war_medicine: {
    id: 'civil_war_medicine',
    topic: 'Civil War Medicine — Letterman, Anesthesia, and the Disease Ledger',
    summary: `The American Civil War killed roughly two soldiers from disease for every one killed in action. Camp dysentery, typhoid, malaria, measles, and pneumonia did the work that battlefield wounds did not, and the medical services on both sides were forced to professionalize under unprecedented load. The Union Army's medical bureau, reorganized under Surgeon General William A. Hammond in 1862, codified the Letterman ambulance system after Antietam: dedicated horse-drawn ambulances, trained stretcher details, forward dressing stations, and tiered field hospitals separating triage from operative surgery. Anesthesia — chloroform on the Confederate side, ether more commonly on the Union side — was widely available throughout the war; the popular memory of "no anesthesia for amputations" is largely myth. The Sanitary Commission and the Christian Commission ran civilian-led inspection and supply operations alongside the army medical departments. Female nurses — Dorothea Dix's matron corps, Clara Barton in the field, Phoebe Pember at Chimborazo Hospital in Richmond — established roles for women in military hospitals that had not existed in American medicine before. By 1865 American military medicine had been pulled, by necessity, decades closer to modern triage and hospital practice without yet having germ theory to explain why some of the reforms worked.`,
    period_voice: `Surgeon Jonathan Letterman, Medical Director of the Army of the Potomac, in his official report after Antietam, October 1862: "The system of ambulances which I had the honor to recommend to the Major General commanding worked admirably. I never saw, even at a small affair, such order, regularity, and absence of confusion." (OR ser. 1 vol. 19 pt. 2 p. 110)`,
    power_analysis: `The structural fact was scale. Both armies confronted casualty densities — Shiloh, the Seven Days, Antietam, Gettysburg, Chickamauga, the Wilderness — that no antebellum American medical institution had been built to handle. The Letterman system worked because it was a logistical reform, not a medical one: it treated the movement of wounded men as a supply problem with timetables and dedicated rolling stock. Hammond's reorganization of the Medical Bureau cleared out senior officers chosen by seniority and replaced them with administrators who could run a continental-scale operation. Confederate medicine was hobbled by the same industrial constraints that limited Confederate ordnance — no domestic production of standardized surgical instruments, limited chloroform supply, and a railroad system that could not move hospital stores reliably after 1863. Female nursing was not a sudden moral reform; it was a labor solution to a manpower shortage in army hospitals, and the institutional infrastructure (Dix's matron corps, the Sanitary Commission's volunteer system, Phoebe Pember at Chimborazo) developed because it had to.`,
    complexity_note: `Civil War surgeons knew the value of clean instruments, ventilation, and clean dressings well before they could explain it through germ theory; Joseph Lister's antiseptic publications came after the war. Amputation was often the correct decision for shattered limbs because the alternative — without antibiotics or aseptic technique — was usually fatal sepsis. The popular caricature of butcher surgeons is not the picture the operative case reports support. At the same time, hospital gangrene, pyemia, and erysipelas killed thousands who survived the operating table, and post-operative mortality on both sides remained terrible by any modern standard. Reformers on the Union side benefited from civilian press, the Sanitary Commission, and Hammond's willingness to spend political capital; Confederate medical officers worked harder for less under collapsing supply lines and got less institutional credit because the surviving paperwork is thinner.`,
    sourceNotes: `Medical and Surgical History of the War of the Rebellion (Government Printing Office, 1870-1888, 6 vols.); Letterman, Medical Recollections of the Army of the Potomac (Appleton, 1866); Hammond, A Statement of the Causes Which Led to the Dismissal of Surgeon-General William A. Hammond (1864); OR ser. 1 vols. 11, 19, 25, 36 (medical bureau correspondence); Pember, A Southern Woman's Story (Carleton, 1879); Barton, papers and Red Cross archive; Stille, History of the United States Sanitary Commission (Lippincott, 1866); Cunningham, Field Medical Services at the Battles of Manassas (Charles C. Thomas, 1968) as a synthesizing study.`,
    relatedScenarios: ['antietam', 'seven_days', 'fredericksburg_winter_politics', 'wilderness', 'petersburg_siege'],
  },

  army_technology_advancement: {
    id: 'army_technology_advancement',
    topic: 'Army Technology — Rifles, Trenches, Telegraphs, and the Tactical Lag',
    summary: `The Civil War was the first large industrial war fought primarily with rifled small arms. The standard issue infantry weapon on both sides — the U.S. M1861 Springfield rifle musket and the British Enfield M1853, both .58 caliber and firing the conical Minié ball — extended effective infantry range from the smoothbore's 80-100 yards out to 200-300 yards. Repeating arms (the Henry rifle, the Spencer repeater) appeared in Union service from 1863 forward but were never universal; they outclassed muzzle-loaders in skirmish and dismounted cavalry actions where adopted. Breech-loading carbines (Sharps, Burnside, Smith) gave Union cavalry an advantage by 1864. Field artillery moved from a mix of bronze 6-pounders and howitzers toward the 12-pounder Napoleon and the rifled Parrott and 3-inch Ordnance pieces; canister at close range remained the decisive infantry-killing round in the war. The Union Military Telegraph and the Construction Corps under Daniel McCallum tied railroads and dispatches into army operations on a scale never before attempted. Pontoon bridge trains, balloon observation under Thaddeus Lowe, the U.S. Signal Corps under Albert J. Myer, and steady evolution of field fortification from the Seven Days through Cold Harbor and Petersburg all belong to the same technological story: the tools advanced faster than the doctrine inherited from Mexico and Napoleonic Europe.`,
    period_voice: `Colonel Emory Upton, after directing the May 10 1864 assault at Spotsylvania, in his official report and subsequent A New System of Infantry Tactics (1867): "The history of the war proves that a column of attack with bayonets fixed will, with comparatively small loss, carry an entrenched position when the same position cannot be carried by a line of battle. The rifle has changed the conditions of attack." (Upton, Tactics, pref.)`,
    power_analysis: `The structural lag is the central fact. Hardee's Tactics, the 1855 manual most officers learned, was a translation of French doctrine assuming smoothbore ranges and shock combat. The minie-ball rifled musket — adopted by the U.S. Army in 1855 and standard on both sides by 1862 — quietly invalidated the assumption that a determined linear attack could close to bayonet range without prohibitive losses against unbroken infantry. The doctrinal response took the war's full length. Lee's instinct at Antietam and Gettysburg was still Napoleonic concentration; by the Overland Campaign and Petersburg, both armies entrenched on first contact, and Upton's column-of-attack revision at Spotsylvania was the first systematic American answer. The telegraph, rail, and pontoon advances ran on the same incentive structure — they reduced the cost of moving information, men, and supplies faster than European armies achieved until the 1870s. The Confederacy adopted as many of the same technologies as it could buy through the blockade or improvise (Mallory's torpedo boats, Gorgas's ordnance bureau improvisations), but it could not produce them at scale.`,
    complexity_note: `The "rifled musket revolution" thesis is real but overstated by some early-twentieth-century writers. Actual engagement ranges remained surprisingly short — rolling terrain, smoke, and command-and-control problems pushed most firefights inside 150 yards even with rifles theoretically lethal beyond 500. Repeating arms were limited as much by ammunition logistics and unit organization as by procurement reluctance. Trench warfare at Petersburg was not the Western Front of 1916: it included regular maneuver, raids, mining, and political negotiation around the lines. The Civil War is best read not as a foreshadowing of World War I but as a partial, incomplete adaptation: tools that outran doctrine, doctrine that caught up unevenly, and field commanders learning under fire.`,
    sourceNotes: `Hardee, Rifle and Light Infantry Tactics (Lippincott, 1855); Upton, A New System of Infantry Tactics (Appleton, 1867); Birkhimer, Historical Sketch of the Organization, Administration, Material and Tactics of the Artillery, United States Army (Government Printing Office, 1884); Annual Reports of the Chief of Ordnance, 1861-1865 (Government Printing Office); OR ser. 1 vols. 19, 25, 27, 36, 40 (ordnance and signal reports); Battles and Leaders vol. IV pp. 220-262 on small arms; Plum, The Military Telegraph During the Civil War in the United States (Jansen McClurg, 1882); Lord, A Source Book of Civil War Material (Council on Books in Wartime, 1944) as a synthesizing compilation.`,
    relatedScenarios: ['seven_days', 'antietam', 'gettysburg_decision', 'wilderness', 'petersburg_siege'],
  },

  wartime_industry: {
    id: 'wartime_industry',
    topic: 'Wartime Industry — Tredegar in Richmond, Springfield Armory in Massachusetts',
    summary: `Two arms-manufacturing institutions illustrate the industrial gulf the war fought across. The Tredegar Iron Works in Richmond, under Joseph Reid Anderson, was the only large rolling mill in the Confederacy. It produced approximately eleven hundred artillery pieces during the war, the iron plating for the CSS Virginia and other ironclads, projectile shells, gun carriages, and rail iron. Tredegar's output carried more strategic weight than its absolute size warranted, because no other Southern facility could replace it; its loss would have meant losing the Confederate ordnance program. Across the Potomac, the Springfield Armory in Massachusetts, under Alexander B. Dyer (later promoted to Chief of Ordnance), was already the largest small-arms factory in the United States in 1860 and expanded explosively through the war. By 1864 Springfield was producing roughly twenty thousand M1861 rifle muskets per month and had delivered more than 800,000 stand of arms by war's end, supplemented by private contractors (Colt, Remington, Sharps, Smith and Wesson) that the federal Ordnance Department could afford to compete with for skilled labor. The Confederate ordnance bureau under Josiah Gorgas worked with extraordinary improvisation — captured Union arms, blockade-run Enfields, Selma and Augusta arsenals, and what Tredegar could roll — to keep field armies armed. It was enough to fight a war, not enough to win an industrial one.`,
    period_voice: `Brigadier General Josiah Gorgas, Chief of Confederate Ordnance, in his diary entry of April 8 1864: "I have succeeded beyond my utmost expectations. From being the worst supplied of bureaus, the Ordnance is now the best. Large arsenals have been organized at Richmond, Fayetteville, Augusta, Charleston, Columbus, Macon, Atlanta and Selma, and smaller ones at Danville, Lynchburg, and Montgomery." (Gorgas, Diary, ed. Vandiver, p. 99)`,
    power_analysis: `Industrial capacity is the structural reality both armies fought inside. Tredegar succeeded as much as any Confederate institution could because Anderson combined an ironmaster's technical knowledge with the political skill needed to negotiate impressment of skilled labor, slave labor contracts, contracts with the War Department, and continued operation despite Richmond's chronic shortages of pig iron and coke. Springfield succeeded because Massachusetts had three generations of skilled machinist culture, an established rail network feeding raw materials in, and a Department of the Ordnance with the political latitude to sign contracts with private competitors when government output fell short. The structural lesson is not that Northern engineers were smarter; it is that the antebellum North had built the industrial preconditions (iron, coal, rail, skilled labor, capital markets) that war finance could mobilize at scale, and the South had not. Cotton diplomacy, Tredegar's improvisations, and blockade running were rational responses to a starting position the Confederacy could not change inside four years.`,
    complexity_note: `Confederate industry was not a failure relative to its inputs; it was an extraordinary improvisation. Selma Naval Foundry built heavy ordnance, the Augusta Powder Works (under George W. Rains) produced more gunpowder per worker than any contemporary American facility, and Confederate blockade runners delivered the rifles and percussion caps that Tredegar and the Augusta works could not duplicate. The opposite caricature — that Northern industry won the war while Northern soldiers stood by — also fails: the Springfield system worked only because it was tied to a recruitment, transportation, and command apparatus that successfully delivered armed men to the front. Industry was a necessary but not sufficient condition on both sides.`,
    sourceNotes: `OR ser. 4 vols. 1-3 (Confederate ordnance reports including Gorgas correspondence); Gorgas, The Civil War Diary of General Josiah Gorgas (ed. Frank E. Vandiver, University of Alabama Press, 1947 — primary diary); Annual Reports of the Chief of Ordnance (U.S.), 1861-1865 (Government Printing Office); Wright, Springfield Armory production records, U.S. Ordnance Department archives; Dew, Ironmaker to the Confederacy: Joseph R. Anderson and the Tredegar Iron Works (Yale University Press, 1966) for Tredegar's complete production records; Rains, History of the Confederate Powder Works (Chronicle and Constitutionalist, 1882); Bruce, Lincoln and the Tools of War (Bobbs-Merrill, 1956) on Northern ordnance procurement.`,
    relatedScenarios: ['naval_technology', 'fredericksburg_winter_politics', 'petersburg_siege', 'atlanta_election_pressure', 'fall_of_atlanta'],
  },

  faith_in_the_armies: {
    id: 'faith_in_the_armies',
    topic: 'Faith in the Armies — Camp Religion, Chaplains, and the Great Revival',
    summary: `Both armies were the most religiously self-conscious institutions in nineteenth-century American society, and religion did real organizational work in both. Confederate chaplaincy was small and informal at the war's beginning, then expanded through the army-wide Great Revival of the winter of 1863-1864, when an estimated 150,000 men in the Army of Northern Virginia and the Army of Tennessee professed conversion. J. William Jones, Baptist chaplain in Lee's army, documented this in Christ in the Camp (1887), recording prayer meetings, mass baptisms in the Rappahannock, and Lee's personal involvement in fast-day proclamations. Union chaplaincy was more organized but theologically more divided — Methodist, Baptist, Episcopalian, Presbyterian, and Catholic chaplains worked alongside one another, and Father William Corby's general absolution to the Irish Brigade before the second day at Gettysburg became one of the war's iconic religious moments. The U.S. Christian Commission, founded in November 1861 alongside the Sanitary Commission, sent civilian delegates to camps and hospitals with bibles, tracts, food, and pastoral care. Lincoln's wartime religious language evolved from the relatively formal providentialism of his early speeches into the strikingly dark theology of the Second Inaugural Address (March 4 1865), which declared that the war's continuation might be the just judgment of "a living God" against both sections for the offense of American slavery.`,
    period_voice: `General Orders No. 83, issued by Robert E Lee on August 13, 1863: "Soldiers! we have sinned against Almighty God. We have forgotten His signal mercies, and have cultivated a revengeful, haughty, and boastful spirit. We have not remembered that the defenders of a just cause should be pure in His eyes; that our times are in His hands, and we have relied too much on our own arms for the achievement of our independence. God is our only refuge and our strength. Let us humble ourselves before Him. Let us confess our many sins and beseech Him to give us a higher courage, a purer patriotism, and a more determined will; that He will convert the hearts of our enemies; that He will hasten the time when war, with its sorrows and sufferings, shall cease, and that He will give us a name and place among the nations of the earth." General Robert E. Lee After Appomattox, edited by Franklin L. Riley (New York, 1922), pp. 182-95.`,
    power_analysis: `Religion was a force for cohesion in the armies. Camp revivals operated in the windows between active campaigning, when armies were stationary, casualty memory was fresh, and disciplinary breakdown was a real threat; the Great Revival in the Army of Northern Virginia coincided with the winter after Gettysburg and Chickamauga, exactly when morale required reinforcement that battlefield victory could no longer supply. Chaplaincy in both armies functioned as low-cost pastoral and welfare infrastructure: letter-writing for wounded men, burial services, drink and gambling moderation in camp, and a hearing for grievances officers could not address through the chain of command. The Christian Commission and the Sanitary Commission carried out civilian-coordinated supply work that the army medical and quartermaster departments could not yet manage at scale. Lee's published General Orders calling for fast days and humility were not personal pieties dropped into official paperwork; they were morale instruments at moments when the army needed religious framing as much as it needed shoes.`,
    complexity_note: `Both sides genuinely believed God supported their cause, and chaplains on both sides preached it. Confederate sermons routinely treated the war as a defense of Christian civil order; Union sermons routinely treated it as a providential judgment on slavery, and increasingly so after 1863. The most striking thing in the surviving sermon record is not the differences but the structural similarity: providential reasoning, fast days, and revival meetings followed the same patterns in both armies because they came out of the same Protestant evangelical tradition. Catholic soldiers in both armies — Irish on the Union side, Louisiana French-Catholic on the Confederate side — worshipped inside a denominational tradition the dominant Protestant chaplaincy did not control. `,
    sourceNotes: `Jones, Christ in the Camp; or, Religion in Lee's Army (B. F. Johnson, 1887); Lincoln, Collected Works vol. VIII (Basler ed.), Second Inaugural Address; Bennett, The Great Revival in the Southern Armies (Claxton, Remsen and Haffelfinger, 1877); Annual Reports of the United States Christian Commission, 1861-1866; OR ser. 1 vol. 25 pt. 2 and vol. 29 pt. 2 (Lee's general orders on fast days and chaplaincy); Corby, Memoirs of Chaplain Life (La Monte, O'Donnell, 1893); Brinsfield, Faith in the Fight: Civil War Chaplains (University of Tennessee Press, 2003) as a recent synthesis drawing on primary chaplain records.`,
    relatedScenarios: ['chancellorsville_aftermath', 'fredericksburg_winter_politics', 'gettysburg_with_jackson', 'wilderness', 'appomattox_decision'],
  },

  upper_south_secession_crisis: {
    id: 'upper_south_secession_crisis',
    topic: 'Upper South Politics — Letcher, Lincoln, and the April 1861 Troop Call',
    summary: `The four Upper South states (Virginia, North Carolina, Tennessee, Arkansas) sat outside the seven-state Confederacy through the long secession winter of 1860-61. Virginia's Governor John Letcher had been elected as a Unionist Democrat. The Virginia State Convention, in session at Richmond, voted down a secession ordinance 88 to 45 on April 4 1861. The Cotton State governments and the Lincoln administration had both spent the winter assuming Virginia would not move. Fort Sumter changed only the timing. On April 15 1861, the day after Anderson surrendered, Lincoln issued a proclamation calling on the loyal states to furnish 75,000 militia "to cause the laws to be duly executed." Secretary of War Simon Cameron sent requisitions to every Northern and Upper South state governor, including Letcher, for Virginia's quota of three regiments. Letcher's reply of April 16 refused, declaring the militia would not be furnished "for any such use or purpose as they have in view." The Virginia Convention reassembled, and on April 17 1861 reversed its earlier vote by 88 to 55 in favor of secession, contingent on a popular referendum (which carried in May). North Carolina, Tennessee, and Arkansas followed under the same logic in the next six weeks. The Upper South did not secede over Sumter; it seceded over the call to coerce the Cotton States.`,
    period_voice: `Governor John Letcher of Virginia to Secretary of War Simon Cameron, April 16 1861: "I have only to say that the militia of Virginia will not be furnished to the powers at Washington for any such use or purpose as they have in view. Your object is to subjugate the Southern States, and a requisition made upon me for such an object — an object, in my judgment, not within the purview of the Constitution or the Act of 1795 — will not be complied with. You have chosen to inaugurate civil war; and having done so, we will meet it in a spirit as determined as the Administration has exhibited toward the South." (OR ser. 3 vol. 1 p. 76)`,
    power_analysis: `The Upper South crisis ran on a structural fact both Washington and Richmond underweighted in March 1861. Virginia's commercial elite — Norfolk shipping, Richmond's Tredegar and rail interests, Petersburg cotton brokerage — had antebellum ties running north to Baltimore and Philadelphia as well as south. Its planter elite had demographic ties to the slave economy that the Cotton State governments were defending. Letcher, William A. Graham in North Carolina, John Bell in Tennessee, and the convention Unionists held a coalition that depended on Washington not asking Virginia to fight its neighbors. Lincoln's April 15 proclamation did not invent secession in the Upper South; it asked the Upper South to choose between two coalitions whose costs had previously been deferrable. The structural argument is that the Sumter shot mattered politically because of what it forced — a federal request for armed coercion against states the Upper South had economic, social, and military ties to — rather than because of the masonry damage in Charleston Harbor.`,
    complexity_note: `Letcher and the Virginia Convention Unionists were not bluffing during the spring. The April 4 vote against secession was real and the Convention's Unionist leadership (Robert Y. Conrad, William Ballard Preston, John Janney as president) had been actively negotiating with the Lincoln administration through informal channels. Lincoln's calculation that he could refuse to evacuate Sumter without losing Virginia was not crazy; it was a bet on the Convention's prior balance of votes that the troop call invalidated. Both sides made decisions under genuine uncertainty about what the other would do, and both were partly surprised. The April 17 reversal vote of 88 to 55 also included Unionist holdouts (about a quarter of the no votes came from western counties that within two years would themselves separate and become West Virginia), which is the cleanest evidence that the Upper South crisis was a coalition fracture, not a unanimous moral conversion.`,
    sourceNotes: `OR ser. 3 vol. 1 pp. 67-83 (Lincoln's April 15 proclamation, Cameron's requisitions, gubernatorial replies including Letcher, Magoffin of Kentucky, Jackson of Missouri); Journal of the Acts and Proceedings of a General Convention of the State of Virginia, Assembled at Richmond, on Wednesday, the Thirteenth Day of February, Eighteen Hundred and Sixty-One (Richmond, 1861) — the Virginia Convention's own minutes; Reese, ed., Proceedings of the Virginia State Convention of 1861, 4 vols. (Virginia State Library, 1965) for the day-by-day debates; Channing, A History of the United States vol. VI ch. 14; Nevins, The War for the Union vol. I ch. 1-2; Freeman, R.E. Lee vol. I ch. 31-32 (on Lee's own decision tied to Virginia's); McGuire, Diary of a Southern Refugee from the Commencement of the War (Hale, 1867), entries for April 1861.`,
    relatedScenarios: ['fort_sumter', 'radical_republican_crisis', 'manassas_battlefield'],
  },

  women_in_the_war: {
    id: 'women_in_the_war',
    topic: 'Women in the War — Intelligence, Nursing, and the Home Front',
    summary: `Women did the war's work in three institutional areas that antebellum American society had not been built to staff. The first was intelligence and clandestine action. Rose O'Neal Greenhow ran a Confederate signal network out of her Washington home through the summer of 1861 and is credited by Beauregard's correspondence with passing the warning that contributed to Confederate concentration before First Manassas; she was arrested by Allan Pinkerton in August 1861 and later drowned off Wilmington carrying gold from Europe. Belle Boyd carried tactical intelligence to Stonewall Jackson during the 1862 Valley Campaign, including the warning that helped him secure Front Royal on May 23. Elizabeth Van Lew ran the most important Union intelligence network in Richmond for the duration of the war, placing freed servants inside the Confederate White House and forwarding reports through couriers to Grant in 1864-65. The second area was nursing. Dorothea Dix's Superintendent of Female Nurses commission organized the Union matron corps from June 1861; Clara Barton operated independently at Cedar Mountain, Second Manassas, Antietam, and Fredericksburg before the Red Cross; Phoebe Pember ran Chimborazo Hospital in Richmond, the largest military hospital in North America, from December 1862. The third area was home-front labor — running farms after enlistments, working in arsenals (the September 17 1862 Allegheny Arsenal explosion in Pittsburgh killed seventy-eight workers, most of them women and girls), staffing hospitals and aid societies, and writing the wartime diary record (Mary Boykin Chesnut, Judith McGuire, Sarah Morgan, Kate Stone, Sara Pryor) that preserves more of the conflict's domestic texture than either government's official papers.`,
    period_voice: `Phoebe Yates Pember, matron of the second division of Chimborazo Hospital, Richmond, in A Southern Woman's Story (Carleton, 1879): "In the midst of suffering and death, hoping with those almost beyond hope, smoothing the pillow for the head that pressed it for the last time, gleaning at last for the heart that loved its work, the meaning of life with all its hard burdens and harder lessons — there was nothing in the work that any woman of sense, energy and Christian spirit need have shrunk from." (Pember, A Southern Woman's Story, p. 23)`,
    power_analysis: `Female wartime labor was a structural answer to a manpower problem, not a moral reform that happened to coincide with mobilization. Army nursing in the United States had been almost entirely male in 1860; by 1862 both governments needed bodies to staff hospitals on a scale antebellum medical institutions had never built, and Dix's matron corps and the Confederate equivalent (under no equivalent national office, but coordinated by individual hospital matrons like Pember and Captain Sally Tompkins at Robertson Hospital) were the most cost-effective solution available. Intelligence work succeeded partly because nineteenth-century social conventions made elite women relatively immune to systematic searches, surveillance, and forcible interrogation; Greenhow operated openly in Washington under the eyes of the State Department until Pinkerton's August 1861 raid, and Van Lew's Richmond network depended on her ability to play the role of a harmless eccentric. Home-front labor in arsenals and quartermaster depots ran on the same wage and labor-supply logic that pulled antebellum women into Lowell textile mills, but at much higher physical risk: Allegheny Arsenal in 1862 and the Confederate States Laboratory explosion at Brown's Island in Richmond in March 1863 each killed scores of female workers handling fulminate of mercury and gunpowder.`,
    complexity_note: `The recorded female participation in the war is uneven by side and by social class. Union sources are richer because the postwar Sanitary Commission, the Christian Commission, and Frank Moore's Women of the War (1866) and Brockett and Vaughan's Woman's Work in the Civil War (1867) gathered firsthand accounts within two years of the surrender. Confederate sources survive in fewer official archives but are preserved in the diarist record (Chesnut, McGuire, Pryor, Morgan), in Pember's hospital memoir, and in individual letter collections. Female enlistment in disguise — Sarah Edmonds in the 2nd Michigan Infantry, the disputed memoir of Loreta Velazquez — is documented unevenly, with Edmonds's pension file confirming her service and Velazquez's account contested by Jubal Early in his lifetime.`,
    sourceNotes: `Greenhow, My Imprisonment and the First Year of Abolition Rule at Washington (Richard Bentley, London, 1863); Boyd, Belle Boyd in Camp and Prison (Saunders, Otley, London, 1865); Bradford, Scenes in the Life of Harriet Tubman (W. J. Moses, 1869) and Harriet, the Moses of Her People (G. R. Lockwood, 1886); Edmonds, Nurse and Spy in the Union Army (W. S. Williams, Hartford, 1865); Pember, A Southern Woman's Story (Carleton, 1879); Chesnut, A Diary from Dixie (Appleton, 1905); McGuire, Diary of a Southern Refugee (Hale, 1867); Pryor, Reminiscences of Peace and War (Macmillan, 1904); Moore, Women of the War: Their Heroism and Self-Sacrifice (S. S. Scranton, Hartford, 1866); Brockett and Vaughan, Woman's Work in the Civil War (Zeigler, McCurdy, Philadelphia, 1867); Van Lew Papers, New York Public Library and Virginia Historical Society; OR ser. 2 vol. 2 (Greenhow arrest correspondence) and ser. 1 vol. 14 (Combahee River raid reports).`,
    relatedScenarios: ['fort_sumter', 'first_winchester', 'antietam', 'chancellorsville_aftermath', 'fredericksburg_winter_politics', 'petersburg_siege'],
  },

  death_in_the_civil_war: {
    id: 'death_in_the_civil_war',
    topic: 'Death in the Civil War',
    summary: `The Civil War was not the first American conflict to be photographed, but it was the first in which photographs of battlefield dead reached a mass public. After Antietam, Alexander Gardner and James Gibson photographed bodies before burial; Mathew Brady displayed the images in New York in October 1862. The camera removed much of the distance maintained by heroic prints and newspaper prose. Families still experienced death chiefly through letters, casualty lists, returned personal effects, and graves that were often far from home. Identification systems were primitive, embalming was expensive, and armies buried thousands near hospitals or battlefields. Private grief was therefore everywhere, but public mourning rarely gathered around one ordinary death. Stonewall Jackson's death in May 1863 and Abraham Lincoln's assassination in April 1865 became exceptional mass events. Their funeral observances allowed large communities to mourn a commander, a president, a cause, and by extension many relatives and comrades whose deaths had received no comparable public ceremony. After the war, local grave-decoration customs developed across the country. General John A. Logan's Grand Army of the Republic order made May 30 1868 a national Union observance called Decoration Day; related Northern and Southern traditions gradually contributed to the Memorial Day commemorations that followed.`,
    period_voice: `Reviewing Brady's Antietam exhibition on October 20 1862, the New York Times wrote that the photographs brought home "the terrible reality and earnestness of war."`,
    power_analysis: `Mass death forced governments to build institutions that had scarcely existed before the war: systematic casualty reporting, hospital burial grounds, national cemeteries, reinterment programs, pension records, and organized grave registration. Photography changed what civilians could see, but railroads, telegraphs, newspapers, embalming, and military bureaucracy changed how quickly death could be reported, transported, counted, and converted into political pressure. Jackson's and Lincoln's deaths mattered beyond personal affection because each man represented a larger wartime coalition. Public ceremony concentrated otherwise dispersed grief into a form that armies, governments, churches, veterans' associations, and families could recognize together.`,
    complexity_note: `The war did not create a single national memory at once. Arlington became a national cemetery by War Department order in June 1864 and initially served principally as a United States military cemetery, with burial practices divided by army, race, and rank. Its Tomb of the Civil War Unknowns, dedicated in 1866, likely held remains from both armies, but Congress did not authorize a separate Confederate section until 1900. Decoration Day likewise grew from several local practices before the Grand Army of the Republic established a national Union observance in 1868; Southern communities maintained their own memorial days. Arlington's later standing as hallowed ground for veterans of successive wars, including recognized graves from both Civil War sides, was therefore a postwar development rather than an immediate settlement achieved in 1865.`,
    sourceNotes: `New York Times, October 20 1862, "Brady's Photographs: Pictures of the Dead at Antietam"; Gardner's Photographic Sketch Book of the War (1866); Richmond Dispatch and Southern Illustrated News accounts of Jackson's death and funeral, May 1863; Lincoln funeral correspondence and printed programs, April-May 1865; Grand Army of the Republic General Orders No. 11, May 5 1868; U.S. War Department order establishing Arlington National Cemetery, June 15 1864; Arlington National Cemetery records for the Tomb of the Civil War Unknowns, Decoration Day, and the Confederate section authorized in 1900.`,
    relatedScenarios: ['antietam', 'chancellorsville_aftermath', 'cold_harbor', 'appomattox_decision'],
  },
};

/**
 * Return the primer ids tagged on a scenario, deduplicated, preserving order.
 */
export function getPrimerIdsForScenario(scenario) {
  if (!scenario || !Array.isArray(scenario.primerTags)) return [];
  const seen = new Set();
  const ids = [];
  for (const tag of scenario.primerTags) {
    if (typeof tag === 'string' && !seen.has(tag) && HISTORICAL_PRIMERS[tag]) {
      seen.add(tag);
      ids.push(tag);
    }
  }
  return ids;
}

/**
 * Hydrate a scenario's primerTags into the full primer objects.
 */
export function resolvePrimersForScenario(scenario) {
  return getPrimerIdsForScenario(scenario).map((id) => HISTORICAL_PRIMERS[id]);
}

/**
 * Compact context block for the local Ollama prompt. Surfaces only the
 * power_analysis paragraph (the structural framing) plus a short sourceNotes
 * line so the model has ground-truth context for the tagged topics without
 * being flooded with the full primer body.
 */
export function buildPrimerContextNote(scenario) {
  const primers = resolvePrimersForScenario(scenario);
  if (!primers.length) return '';
  const lines = primers.map(
    (primer) => `- ${primer.topic}: ${primer.power_analysis} Sources: ${primer.sourceNotes}`,
  );
  return `\n\nHistorical primers tagged on this turn (ground truth — do not contradict):\n${lines.join('\n')}`;
}
