/**
 * Titans of War — Curated Historical Asset Manifest
 *
 * Shared by the downloader and validators. Assets may be marked `pending`
 * when the catalog target is known but a final downloadable URL still needs
 * source verification.
 */

export const HISTORICAL_ASSET_MANIFEST = [
  {
    id: 'audio_lorena_house_divided',
    type: 'audio',
    status: 'curated',
    filename: 'lorena_instrumental.mp3',
    targetDir: 'public/audio',
    catalogKey: 'lorena',
    title: 'Lorena',
    assetRole: 'music',
    scenarioIds: ['low-morale', 'game-over', 'home-front'],
    sourceUrl: 'https://natunelist.net/lorena/',
    downloadUrl: 'https://natunelist.net/wp-content/uploads/2017/03/Lorena.mp3',
    sourceInstitution: 'North Atlantic Tune List',
    license: 'Site states content is not copyrighted; attribution preferred',
    licenseStatus: 'verified-free-license',
    expectedContentType: 'audio/',
    notes: 'Melancholic Civil War-era song cue for low-morale and home-front turns.',
  },
  {
    id: 'audio_battle_cry_loc',
    type: 'audio',
    status: 'curated',
    filename: 'battle_cry_brass.mp3',
    targetDir: 'public/audio',
    catalogKey: 'battle_cry',
    title: 'Battle Cry of Freedom (Patriotic Medley March No. 2)',
    assetRole: 'music',
    scenarioIds: ['high-morale', 'union-pressure', 'orthodox-campaign'],
    sourceUrl: 'https://www.loc.gov/item/jukebox-25440/',
    downloadUrl: 'https://tile.loc.gov/storage-services/service/mbrsrs/mbrsjukebox/ucsb_victor_35657_01_c20607_01/ucsb_victor_35657_01_c20607_01.mp3',
    sourceInstitution: 'Library of Congress National Jukebox / Victor Military Band',
    license: 'Public Domain in the United States (pre-1923 sound recording)',
    licenseStatus: 'verified-public-domain',
    expectedContentType: 'audio/',
    notes: '1917 band medley containing Battle Cry of Freedom; strong high-morale maneuver cue.',
  },
  {
    id: 'audio_johnny_fife_drum',
    type: 'audio',
    status: 'curated',
    filename: 'fife_drum_march.mp3',
    targetDir: 'public/audio',
    catalogKey: 'march',
    title: 'When Johnny Comes Marching Home',
    assetRole: 'music',
    scenarioIds: ['opening', 'movement', 'early-war'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:When_Johnny_Comes_Marching_Home_-_USMA_Band.ogg',
    downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/4/40/When_Johnny_Comes_Marching_Home_-_USMA_Band.ogg/When_Johnny_Comes_Marching_Home_-_USMA_Band.ogg.mp3',
    sourceInstitution: 'Wikimedia Commons / West Point Band',
    license: 'Public Domain in the United States (U.S. Army performance)',
    licenseStatus: 'verified-public-domain',
    expectedContentType: 'audio/',
    notes: '1990 West Point Band recording; composition and performance are marked public domain on Commons.',
  },
  {
    id: 'audio_appomattox_elegy',
    type: 'audio',
    status: 'curated',
    filename: 'elegy_final.mp3',
    targetDir: 'public/audio',
    catalogKey: 'elegy_final',
    title: 'Taps (Appomattox Elegy)',
    assetRole: 'music',
    scenarioIds: ['appomattox_decision', 'greensboro_convention', 'game-over'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Taps_on_bugle.ogg',
    downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/2/25/Taps_on_bugle.ogg/Taps_on_bugle.ogg.mp3',
    sourceInstitution: 'Wikimedia Commons / U.S. Army Band',
    license: 'Public Domain in the United States (U.S. Army performance)',
    licenseStatus: 'verified-public-domain',
    expectedContentType: 'audio/',
    notes: 'Solemn bugle call for Appomattox, surrender, and game-over turns.',
  },
  {
    id: 'audio_campfire_cc0',
    type: 'audio',
    status: 'curated',
    filename: 'ambient_campfire.mp3',
    targetDir: 'public/audio',
    catalogKey: 'ambient_campfire',
    title: 'Campfire Ambience',
    assetRole: 'ambient',
    scenarioIds: ['menu', 'letter', 'low-morale'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Barbecue.ogg',
    downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/9/9b/Barbecue.ogg/Barbecue.ogg.mp3',
    sourceInstitution: 'Wikimedia Commons / PDSounds',
    license: 'Public Domain dedication',
    licenseStatus: 'verified-public-domain',
    expectedContentType: 'audio/',
    notes: 'Low-volume fire ambience for letters, camp, and quiet-command phases.',
  },
  {
    id: 'map_fort_sumter_charleston_harbor_loc',
    type: 'image',
    status: 'curated',
    filename: 'map_fort_sumter_charleston_harbor_loc.jpg',
    targetDir: 'public/images/cw_pictures',
    catalogKey: 'map_fort_sumter_charleston_harbor',
    title: 'Plan of Charleston Harbor and Fortifications',
    assetRole: 'tactical-underlay',
    scenarioIds: ['fort_sumter', 'charleston_harbor_escape'],
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd391:g3912:g3912c:cw0362000/full/pct:25/0/default.jpg',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    license: 'Public Domain',
    licenseStatus: 'verified-public-domain',
    expectedContentType: 'image/',
    notes: 'Opening-turn tactical map for Charleston Harbor and Fort Sumter.',
  },
  {
    id: 'map_antietam_sharpsburg_loc',
    type: 'image',
    status: 'curated',
    filename: 'map_antietam_sharpsburg_loc.jpg',
    targetDir: 'public/images/cw_pictures',
    catalogKey: 'map_antietam_sharpsburg',
    title: 'Topographical Approach Map of Sharpsburg and Dunker Church',
    assetRole: 'tactical-underlay',
    scenarioIds: ['antietam', 'potomac_leverage_campaign'],
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd384:g3844:g3844s:cw0252000/full/pct:25/0/default.jpg',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    license: 'Public Domain',
    licenseStatus: 'verified-public-domain',
    expectedContentType: 'image/',
    notes: 'Verified historical tactical map for the Antietam and Potomac campaigns.',
  },

  {
    id: 'map_gettysburg_cemetery_ridge_loc',
    type: 'image',
    status: 'curated',
    filename: 'map_gettysburg_cemetery_ridge_loc.jpg',
    targetDir: 'public/images/cw_pictures',
    catalogKey: 'map_gettysburg_cemetery_ridge',
    title: 'Cemetery Ridge and Round Tops Elevation Contours',
    assetRole: 'tactical-underlay',
    scenarioIds: ['gettysburg_decision', 'susquehanna_offensive'],
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd382:g3824:g3824g:cw0328000/full/pct:25/0/default.jpg',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    license: 'Public Domain',
    licenseStatus: 'verified-public-domain',
    expectedContentType: 'image/',
    notes: 'Verified elevation contours showing Cemetery Ridge and Little Round Top.',
  },

  {
    id: 'map_petersburg_crater_loc',
    type: 'image',
    status: 'curated',
    filename: 'map_petersburg_crater_loc.jpg',
    targetDir: 'public/images/cw_pictures',
    catalogKey: 'map_petersburg_crater',
    title: 'Petersburg Siege Trenches and Crater Coordinates',
    assetRole: 'tactical-underlay',
    scenarioIds: ['petersburg_siege'],
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd388:g3884:g3884r:cw0648000/full/pct:25/0/default.jpg',
    sourceInstitution: 'Library of Congress / National Archives',
    license: 'Public Domain',
    licenseStatus: 'verified-public-domain',
    expectedContentType: 'image/',
    notes: 'Verified trench siege lines map showing Petersburg detonation coordinates.',
  },

  {
    id: 'map_appomattox_retreat_lines_loc',
    type: 'image',
    status: 'curated',
    filename: 'map_appomattox_retreat_lines_loc.jpg',
    targetDir: 'public/images/cw_pictures',
    catalogKey: 'map_appomattox_retreat_lines',
    title: "Lee's Final Retreat Lines to Appomattox Station",
    assetRole: 'tactical-underlay',
    scenarioIds: ['appomattox_decision', 'greensboro_convention'],
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd388:g3884:g3884a:cw0524000/full/pct:25/0/default.jpg',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    license: 'Public Domain',
    licenseStatus: 'verified-public-domain',
    expectedContentType: 'image/',
    notes: 'Verified final retreat lines map and Appomattox Court House surroundings.',
  },
  {
    id: 'map_wilderness_loc',
    type: 'image',
    status: 'curated',
    filename: 'map_wilderness_russell.jpg',
    targetDir: 'public/images/cw_pictures',
    catalogKey: 'map_wilderness',
    title: 'Spotsylvania & Wilderness Battlefield, May 1864',
    assetRole: 'tactical-underlay',
    scenarioIds: ['wilderness'],
    sourceUrl: 'https://loc.getarchive.net/media/battle-of-the-wilderness-may-5-6-and-7-1864-between-lee-60000-and-grant-120000-5',
    downloadUrl: '',
    sourceInstitution: 'Geography & Map Division, Library of Congress (Robert E. L. Russell 1935 Atlas Collection)',
    license: 'Public Domain',
    licenseStatus: 'verified-public-domain',
    expectedContentType: 'image/',
    notes: 'Verified historical tactical map for the Wilderness campaign, Robert E. L. Russell Atlas Plate 5 showing Lee (60,000) vs Grant (120,000) positions.',
  },
  {
    id: 'audio_dixie_commons',
    type: 'audio',
    status: 'pending',
    filename: 'dixie_instrumental.mp3',
    targetDir: 'public/audio',
    catalogKey: 'dixie',
    title: 'Dixie Land (Instrumental)',
    assetRole: 'music',
    scenarioIds: ['high-divergence', 'hotspur'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Dixie_Land_(Instrumental_version).ogg',
    downloadUrl: '',
    sourceInstitution: 'Wikimedia Commons',
    license: 'Creative Commons Attribution-ShareAlike 4.0 International; excluded from public release until media policy is finalized',
    licenseStatus: 'recording-needed',
    expectedContentType: 'audio/',
    notes: 'Composition is historical period material, but the available recording is CC-BY-SA. Keep inactive for the MIT-code public release unless the repo intentionally ships separate share-alike media.',
  },
  {
    id: 'audio_battle_hymn_triumphant',
    type: 'audio',
    status: 'curated',
    filename: 'battle_hymn_triumphant.mp3',
    targetDir: 'public/audio',
    catalogKey: 'battle_hymn',
    title: 'The Battle Hymn of the Republic',
    assetRole: 'music',
    scenarioIds: ['high-morale', 'union-pressure', 'naval_technology'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Battle_Hymn_of_the_Republic,_Frank_C._Stanley,_Elise_Stevenson.ogg',
    downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/2/20/Battle_Hymn_of_the_Republic,_Frank_C._Stanley,_Elise_Stevenson.ogg/Battle_Hymn_of_the_Republic,_Frank_C._Stanley,_Elise_Stevenson.ogg.mp3',
    sourceInstitution: 'Wikimedia Commons / Library of Congress',
    license: 'Public Domain',
    licenseStatus: 'verified-public-domain',
    expectedContentType: 'audio/',
    notes: 'Uplifting grand brass and choral march recording representing Union pressure and naval technology.',
  },
  {
    id: 'audio_yellow_rose_march',
    type: 'audio',
    status: 'curated',
    filename: 'yellow_rose_march.mp3',
    targetDir: 'public/audio',
    catalogKey: 'yellow_rose',
    title: 'The Yellow Rose of Texas',
    assetRole: 'music',
    scenarioIds: ['early-war', 'movement', 'gettysburg_decision'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Yellow_Rose_Of_Texas.ogg',
    downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/f/fb/Yellow_Rose_Of_Texas.ogg/Yellow_Rose_Of_Texas.ogg.mp3',
    sourceInstitution: 'Wikimedia Commons',
    license: 'Public Domain',
    licenseStatus: 'verified-public-domain',
    expectedContentType: 'audio/',
    notes: 'Rhythmic, upbeat quickstep march representing cavalry movements and Southern camp marches.',
  },
  {
    id: 'audio_tenting_tonight',
    type: 'audio',
    status: 'curated',
    filename: 'tenting_tonight.mp3',
    targetDir: 'public/audio',
    catalogKey: 'tenting_tonight',
    title: 'Tenting Tonight on the Old Camp Ground',
    assetRole: 'music',
    scenarioIds: ['letter', 'low-morale', 'winter-camps'],
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tenting_Tonight_on_Old_Camp_Ground.ogg',
    downloadUrl: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/0/0d/Tenting_Tonight_on_Old_Camp_Ground.ogg/Tenting_Tonight_on_Old_Camp_Ground.ogg.mp3',
    sourceInstitution: 'Wikimedia Commons',
    license: 'Public Domain',
    licenseStatus: 'verified-public-domain',
    expectedContentType: 'audio/',
    notes: 'Weary, sappy campfire ballad representing soldiers sitting around campfire ashes dreaming of peace.',
  },
  {
    id: 'audio_just_before_battle_mother',
    type: 'audio',
    status: 'curated',
    filename: 'just_before_battle_mother.mp3',
    targetDir: 'public/audio',
    catalogKey: 'just_before_battle_mother',
    title: 'Just Before the Battle, Mother',
    assetRole: 'music',
    scenarioIds: ['letter', 'low-morale', 'wilderness'],
    sourceUrl: 'https://www.loc.gov/item/jukebox-25959/',
    downloadUrl: 'https://archive.org/download/edison-51109_01_8486/cusb_ed_51109_01_8486_0c.mp3',
    sourceInstitution: 'Library of Congress National Jukebox',
    license: 'Public Domain',
    licenseStatus: 'verified-public-domain',
    expectedContentType: 'audio/',
    notes: 'Heartbreaking campfire folk ballad depicting a soldier writing final thoughts to home on the eve of combat.',
  },

];

export function getHistoricalAssetByCatalogKey(catalogKey) {
  return HISTORICAL_ASSET_MANIFEST.find((asset) => asset.catalogKey === catalogKey) || null;
}
