/**
 * Titans of War — Media Catalog
 *
 * Structured metadata for all historical image assets used in the game.
 * Drives the ScenarioTheater component, chronicle exports, benchmark reports,
 * and future AI image-generation prompts.
 *
 * Asset fields:
 *   src              — public-folder path (served by Vite static server)
 *   kind             — 'battlefield' | 'map' | 'art' | 'reenactment' | 'fallback'
 *   title            — human-readable label for the image
 *   location         — geographic context
 *   era              — approximate period or date string
 *   bestFor          — array of scenario ids this image best represents
 *   caption          — one-sentence historical note shown in-game
 *   credit           — provenance / license note
 *   provenanceStatus — 'verified' | 'needs-review' (defaults to needs-review)
 *   sourceInstitution— archive or institution that provided the file
 *   sourceUrl        — canonical source URL for license/provenance audit
 *   license          — concise rights label
 *   historicalMedium — period-photo | period-art | modern-photo | reenactment | generated-art | map | unknown
 *   assetRoles       — theater | tactical-underlay | card | chronicle
 *   cropFocus        — { x: 0–1, y: 0–1 } focal point for CSS object-position
 *   cropMode         — 'wide' | 'portrait' | 'contain'
 *   tacticalView     — optional { focus, zoom } tuning for BattlefieldMap underlay framing
 *   theaterOpacity   — opacity used in full-screen historical mode (0–1)
 *   overlayOpacity   — opacity used as a canvas underlay blend (0–1)
 *   promptSeed       — descriptive seed for future AI image generation
 */

const LOCAL_ARCHIVE_PROVENANCE = {
  sourceInstitution: 'Local archive',
  sourceUrl: '',
  license: 'Provenance review needed',
  historicalMedium: 'unknown',
  assetRoles: ['theater', 'tactical-underlay', 'chronicle'],
};

const ASSETS = {
  battlefield_start_of_war: {
    src: '/images/cw_pictures/battlefield start of war.jpg',
    kind: 'battlefield',
    title: 'Charleston Harbor — Opening Bombardment',
    location: 'Charleston Harbor, South Carolina',
    era: 'April 1861',
    bestFor: ['fort_sumter', 'charleston_harbor_escape'],
    caption: 'Fort Sumter in Charleston Harbor, the flashpoint where the opening crisis of the war becomes a command decision.',
    credit: 'Project archive image — Titans Forge',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'MIT project media',
    historicalMedium: 'modern-photo',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Charleston harbor 1861 Confederate artillery battery dawn bombardment sepia illustration',
  },

  battlefield_jackson_flank_march: {
    src: '/images/cw_pictures/battlefield Jackson flank march.jpg',
    kind: 'battlefield',
    title: "Jackson's Flank March — Chancellorsville",
    location: 'Wilderness, Virginia',
    era: 'May 2, 1863',
    bestFor: ['manassas_battlefield', 'chancellorsville_aftermath'],
    caption: "Stonewall Jackson's corps sweeps the Union right flank in a bold night march.",
    credit: 'Public domain — Civil War period artwork',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Confederate infantry column march Virginia woodland 1863 sepia illustration',
  },

  battlefield1: {
    src: '/images/cw_pictures/battlefield1.jpg',
    kind: 'battlefield',
    title: 'The Seven Days — Richmond Perimeter',
    location: 'Peninsula, Virginia',
    era: 'June–July 1862',
    bestFor: ['seven_days'],
    caption: "McClellan's advance stalls against Lee's aggressive counter-offensive outside Richmond.",
    credit: 'Public domain — Civil War period illustration',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.4 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Richmond Virginia 1862 Civil War battlefield artillery charge sepia',
  },

  battlefield2: {
    src: '/images/cw_pictures/battlefield2.jpg',
    kind: 'battlefield',
    title: 'Second Bull Run — Henry House Hill',
    location: 'Prince William County, Virginia',
    era: 'August 28–30, 1862',
    bestFor: ['second_manassas'],
    caption: 'Jackson holds his position as Longstreet prepares the decisive flank assault.',
    credit: 'Public domain — Civil War period artwork',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Bull Run Virginia 1862 Confederate infantry defensive position artillery sepia',
  },

  battlefield_md_campaign: {
    src: '/images/cw_pictures/battlefield MD campaign.jpg',
    kind: 'battlefield',
    title: 'The Maryland Campaign — Sharpsburg Corridor',
    location: 'Western Maryland',
    era: 'September 1862',
    bestFor: ['potomac_leverage_campaign', 'antietam'],
    caption: "Lee's army crosses the Potomac and moves through Maryland toward Sharpsburg.",
    credit: 'Public domain — Civil War period illustration',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Maryland farmland 1862 Civil War army march Potomac River sepia illustration',
  },

  battlefield3: {
    src: '/images/cw_pictures/battlefield3.jpg',
    kind: 'battlefield',
    title: 'Chancellorsville — The Rappahannock Line',
    location: 'Spotsylvania County, Virginia',
    era: 'May 1–6, 1863',
    bestFor: ['chancellorsville_aftermath'],
    caption: "After Hooker's retreat, Lee consolidates along the Rappahannock River.",
    credit: 'Public domain — Civil War period artwork',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Rappahannock River Virginia 1863 Confederate defensive line sepia illustration',
  },

  battlefield4: {
    src: '/images/cw_pictures/battlefield4.jpg',
    kind: 'battlefield',
    title: 'Pennsylvania Invasion — Susquehanna Corridor',
    location: 'South-central Pennsylvania',
    era: 'June–July 1863',
    bestFor: ['susquehanna_offensive', 'gettysburg_decision'],
    caption: 'Confederate columns spread alarm through Pennsylvania, threatening the Susquehanna crossings.',
    credit: 'Public domain — Civil War period illustration',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Pennsylvania 1863 Civil War Confederate march farmland hills sepia illustration',
  },

  battlefield5: {
    src: '/images/cw_pictures/battlefield5.jpg',
    kind: 'battlefield',
    title: 'Chickamauga — The Western Theater',
    location: 'Walker County, Georgia',
    era: 'September 18–20, 1863',
    bestFor: ['chickamauga'],
    caption: "Bragg's Army of Tennessee drives Rosecrans from the field in the deadliest Western Theater battle.",
    credit: 'Public domain — Civil War period artwork',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Chickamauga Georgia 1863 Civil War infantry battle woodland sepia',
  },

  battlefield5_chattanooga: {
    src: '/images/cw_pictures/battlefield 5.jpg',
    kind: 'battlefield',
    title: 'Chattanooga Stranglehold — Ridge Siege',
    location: 'Hamilton County, Tennessee',
    era: 'October–November 1863',
    bestFor: ['chattanooga_stranglehold'],
    caption: 'Confederate forces hold the ridgelines above Chattanooga, besieging the Union garrison below.',
    credit: 'Public domain — Civil War period illustration',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.4 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Chattanooga Tennessee 1863 ridge siege Confederate artillery overlook sepia',
  },

  art1: {
    src: '/images/cw_pictures/art1.jpg',
    kind: 'art',
    title: 'The Wilderness — Burning Forest',
    location: 'Spotsylvania County, Virginia',
    era: 'May 5–7, 1864',
    bestFor: ['wilderness'],
    caption: 'The tangled Wilderness burns as Grant and Lee clash in the dense Virginia woodland.',
    credit: 'Public domain — Civil War period artwork',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.88,
    overlayOpacity: 0.3,
    promptSeed: 'Wilderness Virginia 1864 Civil War forest fire infantry clash dark atmospheric artwork',
  },

  art2: {
    src: '/images/cw_pictures/art2.jpg',
    kind: 'art',
    title: 'Third Winchester — Valley Campaign',
    location: 'Winchester, Virginia',
    era: 'September 19, 1864',
    bestFor: ['third_winchester'],
    caption: "Sheridan's cavalry and infantry drive Early's Army of the Valley from Winchester.",
    credit: 'Public domain — Civil War period artwork',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.88,
    overlayOpacity: 0.3,
    promptSeed: 'Shenandoah Valley 1864 Civil War cavalry charge Union attack sepia artwork',
  },

  art3: {
    src: '/images/cw_pictures/art3.jpg',
    kind: 'art',
    title: 'Richmond War Cabinet — Fire-Eaters Session',
    location: 'Richmond, Virginia',
    era: '1861–1865',
    bestFor: ['hotspur_cabinet_crisis', 'naval_technology'],
    caption: 'The Confederate cabinet debates the crisis of political resolve and offensive action.',
    credit: 'Public domain — Civil War period artwork',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.85,
    overlayOpacity: 0.3,
    promptSeed: 'Confederate Richmond cabinet war council 1862 political figures dramatic lighting artwork',
  },

  art4: {
    src: '/images/cw_pictures/art4.jpg',
    kind: 'art',
    title: 'Quartermaster Emergency — Supply Lines',
    location: 'Confederate Supply Corridor',
    era: '1862–1864',
    bestFor: ['fox_supply_crisis'],
    caption: "Strained rail and supply networks threaten the army's ability to remain in the field.",
    credit: 'Public domain — Civil War period artwork',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.85,
    overlayOpacity: 0.3,
    promptSeed: 'Confederate supply wagon train railroad 1862 quartermaster logistics sepia artwork',
  },

  art5: {
    src: '/images/cw_pictures/art5.jpg',
    kind: 'art',
    title: 'Confederate Treasury — Bond Crisis',
    location: 'Richmond, Virginia',
    era: '1863–1864',
    bestFor: ['wolf_finance_crisis'],
    caption: 'Inflation, blockade, and bond-market collapse threaten the Confederate financial system.',
    credit: 'Public domain — Civil War period artwork',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.85,
    overlayOpacity: 0.3,
    promptSeed: 'Confederate treasury Richmond inflation bond market political crisis 1863 artwork',
  },

  reenactment: {
    src: '/images/cw_pictures/re-enactment.jpg',
    kind: 'reenactment',
    title: 'Petersburg Siege Lines',
    location: 'Petersburg, Virginia',
    era: 'June 1864 – April 1865',
    bestFor: ['petersburg_siege'],
    caption: "Union miners detonate the Crater beneath Confederate lines — the explosion that changed the siege.",
    credit: 'Civil War reenactment — public domain',
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.88,
    overlayOpacity: 0.3,
    promptSeed: 'Petersburg Virginia 1864 siege trench warfare Union Confederate lines Civil War reenactment',
  },

  reenactment2: {
    src: '/images/cw_pictures/re-enactment2.jpg',
    kind: 'reenactment',
    title: 'Appomattox Court House — Final Days',
    location: 'Appomattox, Virginia',
    era: 'April 1865',
    bestFor: ['greensboro_convention', 'appomattox_decision'],
    caption: "Lee's remaining columns face the final decision: surrender with honor or dissolution.",
    credit: 'Civil War reenactment — public domain',
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.88,
    overlayOpacity: 0.3,
    promptSeed: 'Appomattox Virginia 1865 Confederate surrender honor final campaign Civil War reenactment',
  },

  unknown: {
    src: '/images/cw_pictures/unknown.svg',
    kind: 'fallback',
    title: 'Procedural Civil War Theater',
    location: 'Eastern Theater, 1861–1865',
    era: '1861–1865',
    bestFor: [],
    caption: 'Procedural tactical backdrop used when no verified historical asset is available for public release.',
    credit: 'Generated by the Titans of War interface',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge',
    sourceUrl: 'https://github.com/JCapone83/titans-of-war',
    license: 'MIT',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.85,
    overlayOpacity: 0.3,
    promptSeed: 'Civil War 1861 battlefield sepia period illustration',
  },

  map_fort_sumter_charleston_harbor: {
    src: '/images/cw_pictures/map_fort_sumter_charleston_harbor_loc.jpg',
    kind: 'map',
    title: 'Plan of Charleston Harbor and Fortifications',
    location: 'Charleston Harbor, South Carolina',
    era: 'April 1861',
    bestFor: ['fort_sumter', 'charleston_harbor_escape'],
    caption: 'Library of Congress map plate for Charleston Harbor and Fort Sumter approaches.',
    credit: 'Library of Congress Geography and Map Division — Public Domain',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd391:g3912:g3912c:cw0362000/full/pct:25/0/default.jpg',
    license: 'Public Domain',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    tacticalView: { zoom: 1 },
    theaterOpacity: 0.92,
    overlayOpacity: 0.45,
    promptSeed: 'Charleston Harbor Fort Sumter 1861 historical military map',
  },

  map_antietam_sharpsburg: {
    src: '/images/cw_pictures/map_antietam_sharpsburg_loc.jpg',
    kind: 'map',
    title: 'Sharpsburg and Dunker Church Approaches',
    location: 'Sharpsburg, Maryland',
    era: 'September 1862',
    bestFor: ['antietam', 'potomac_leverage_campaign'],
    caption: 'Topographical approach map for Sharpsburg approaches and Antietam Creek sectors.',
    credit: 'Geography & Map Division, Library of Congress, Washington, D.C.',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd384:g3844:g3844s:cw0252000/full/pct:25/0/default.jpg',
    license: 'Public Domain',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.92,
    overlayOpacity: 0.45,
    promptSeed: 'Antietam Sharpsburg Dunker Church historical topographical map',
  },


  map_gettysburg_cemetery_ridge: {
    src: '/images/cw_pictures/map_gettysburg_cemetery_ridge_loc.jpg',
    kind: 'map',
    title: 'Cemetery Ridge and Round Tops Contours',
    location: 'Gettysburg, Pennsylvania',
    era: 'July 1863',
    bestFor: ['gettysburg_decision', 'susquehanna_offensive'],
    caption: 'Topographical map showing Cemetery Ridge, Little Round Top, and Gettysburg contours.',
    credit: 'Geography & Map Division, Library of Congress, Washington, D.C.',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd382:g3824:g3824g:cw0328000/full/pct:25/0/default.jpg',
    license: 'Public Domain',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.92,
    overlayOpacity: 0.45,
    promptSeed: 'Gettysburg Cemetery Ridge Round Tops historical contour map',
  },


  map_petersburg_crater: {
    src: '/images/cw_pictures/map_petersburg_crater_loc.jpg',
    kind: 'map',
    title: 'Petersburg Siege Lines and Crater',
    location: 'Petersburg, Virginia',
    era: '1864',
    bestFor: ['petersburg_siege'],
    caption: 'Detailed siege map showing Petersburg trench lines and Crater breach coordinates.',
    credit: 'Geography & Map Division, Library of Congress, Washington, D.C.',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress / National Archives',
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd388:g3884:g3884r:cw0648000/full/pct:25/0/default.jpg',
    license: 'Public Domain',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.92,
    overlayOpacity: 0.45,
    promptSeed: 'Petersburg siege trenches Crater historical military map',
  },


  map_appomattox_retreat_lines: {
    src: '/images/cw_pictures/map_appomattox_retreat_lines_loc.jpg',
    kind: 'map',
    title: "Lee's Retreat Lines to Appomattox Station",
    location: 'Appomattox, Virginia',
    era: 'April 1865',
    bestFor: ['appomattox_decision', 'greensboro_convention'],
    caption: "Survey map mapping final retreat lines, Appomattox Station, and surrender geography.",
    credit: 'Geography & Map Division, Library of Congress, Washington, D.C.',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd388:g3884:g3884a:cw0524000/full/pct:25/0/default.jpg',
    license: 'Public Domain',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.92,
    overlayOpacity: 0.45,
    promptSeed: 'Appomattox retreat lines station historical military map',
  },

  map_wilderness: {
    src: '/images/cw_pictures/map_wilderness_russell.jpg',
    kind: 'map',
    title: 'Spotsylvania & Wilderness Battlefield (Robert E. L. Russell Atlas)',
    location: 'Wilderness, Virginia',
    era: 'May 1864',
    bestFor: ['wilderness'],
    caption: "Robert E. L. Russell's 1935 Battle of the Wilderness Map (Plate 5: Orange Turnpike & Brock Road crossroads detailing Lee's 60,000 vs Grant's 120,000 troop lines).",
    credit: 'Geography & Map Division, Library of Congress, Robert E. L. Russell Atlas Collection (1935)',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    sourceUrl: 'https://loc.getarchive.net/media/battle-of-the-wilderness-may-5-6-and-7-1864-between-lee-60000-and-grant-120000-5',
    license: 'Public Domain',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.92,
    overlayOpacity: 0.45,
    promptSeed: 'Wilderness Spotsylvania historical military map Orange turnpike Brock road',
  },

  map_first_manassas: {
    src: '/images/cw_pictures/map_first_manassas.png',
    kind: 'map',
    title: 'Bull Run or First Manassas Tactical Map',
    location: 'Manassas, Virginia',
    era: 'July 1861',
    bestFor: ['manassas_battlefield'],
    caption: 'First Manassas tactical map candidate for Bull Run Creek, Henry House Hill, and Manassas Junction.',
    credit: 'American Battlefield Trust / Library of Congress map resource - exact local image source review needed',
    provenanceStatus: 'needs-review',
    sourceInstitution: 'American Battlefield Trust / Library of Congress Geography and Map Division',
    sourceUrl: 'https://www.battlefields.org/learn/maps/map-seat-war-battles-july-18th-21st-1861',
    license: 'Source page credits Library of Congress; exact local image source review needed',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.9,
    overlayOpacity: 0.45,
    promptSeed: 'First Manassas Bull Run Creek Henry House Hill historical tactical map',
  },

  map_second_manassas: {
    src: '/images/cw_pictures/map_second_manassas_aug30_movements.png',
    kind: 'map',
    title: 'Second Manassas Troop Movements, August 30, 1862',
    location: 'Prince William County, Virginia',
    era: 'August 1862',
    bestFor: ['second_manassas'],
    caption: 'Map of battle-field of Manassas, Virginia, giving positions and movements of troops on August 30, 1862.',
    credit: 'Library of Congress Geography and Map Division - Public Domain',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    sourceUrl: 'https://www.loc.gov/item/99439157/',
    license: 'Public Domain',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.9,
    overlayOpacity: 0.45,
    promptSeed: 'Second Manassas railway cut Longstreet flank historical tactical map',
  },

  map_seven_days: {
    src: '/images/cw_pictures/map_seven_days.png',
    kind: 'map',
    title: 'Seven Days Battles Tactical Map',
    location: 'Richmond Peninsula, Virginia',
    era: 'June-July 1862',
    bestFor: ['seven_days'],
    caption: 'Local tactical map candidate for the Seven Days battles around the Chickahominy and Richmond approaches.',
    credit: 'Local archive image - provenance review needed',
    provenanceStatus: 'needs-review',
    sourceInstitution: 'Local archive',
    sourceUrl: '',
    license: 'Provenance review needed',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.9,
    overlayOpacity: 0.45,
    promptSeed: 'Seven Days battles Richmond Chickahominy historical tactical map',
  },

  map_chancellorsville: {
    src: '/images/cw_pictures/map_chancellorsville.jpeg',
    kind: 'map',
    title: 'Chancellorsville Tactical Map',
    location: 'Spotsylvania County, Virginia',
    era: 'May 1863',
    bestFor: ['chancellorsville_aftermath'],
    caption: "Battlefield wayside map photographed on site, showing Chancellorsville, Wilderness crossings, and Jackson's flank march.",
    credit: 'On-site battlefield interpretive map photograph - project archive; underlying wayside rights need review',
    provenanceStatus: 'needs-review',
    sourceInstitution: 'Battlefield interpretive wayside / project archive',
    sourceUrl: '',
    license: 'Project photograph; underlying modern wayside map rights need review',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.9,
    overlayOpacity: 0.45,
    promptSeed: 'Chancellorsville Wilderness crossings Jackson flank march historical tactical map',
  },

  map_third_winchester: {
    src: '/images/cw_pictures/map_third_winchester.png',
    kind: 'map',
    title: 'Battles of Winchester Tactical Map',
    location: 'Winchester, Virginia',
    era: 'September 1864',
    bestFor: ['third_winchester'],
    caption: 'Local tactical map candidate for Winchester and Opequon Creek operations in the Shenandoah Valley.',
    credit: 'Local archive image - provenance review needed',
    provenanceStatus: 'needs-review',
    sourceInstitution: 'Local archive',
    sourceUrl: '',
    license: 'Provenance review needed',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.9,
    overlayOpacity: 0.45,
    promptSeed: 'Winchester Opequon Creek Shenandoah Valley historical tactical map',
  },

  map_virginia_campaigns_reference: {
    src: '/images/cw_pictures/map_virginia_campaigns_reference.jpeg',
    kind: 'map',
    title: 'Virginia Campaigns Reference Map',
    location: 'Virginia',
    era: '1861-1865',
    bestFor: [],
    caption: 'Broad battlefield wayside reference map for Virginia campaign geography; kept as backup rather than a scenario-specific tactical underlay.',
    credit: 'On-site battlefield interpretive map photograph - project archive; underlying wayside rights need review',
    provenanceStatus: 'needs-review',
    sourceInstitution: 'Battlefield interpretive wayside / project archive',
    sourceUrl: '',
    license: 'Project photograph; underlying modern wayside map rights need review',
    historicalMedium: 'map',
    assetRoles: ['chronicle'],
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.85,
    overlayOpacity: 0.35,
    promptSeed: 'Virginia Civil War campaign reference map',
  },

};

const PROCEDURAL_TACTICAL_MAP = {
  src: '',
  kind: 'procedural',
  title: 'Procedural Terrain Schematic',
  location: 'Scenario tactical sector',
  era: '1861–1865',
  bestFor: [],
  caption: 'Scenario-specific procedural terrain drawn from authored map annotations.',
  credit: 'Titans of War procedural tactical layer',
  provenanceStatus: 'needs-review',
  sourceInstitution: 'Titans of War',
  sourceUrl: '',
  license: 'Generated by game engine',
  historicalMedium: 'unknown',
  assetRoles: ['tactical-underlay'],
  useInApp: true,
  cropFocus: { x: 0.5, y: 0.5 },
  cropMode: 'contain',
  tacticalView: { focus: { x: 0.5, y: 0.5 }, zoom: 1 },
  theaterOpacity: 0,
  overlayOpacity: 0,
  promptSeed: 'procedural tactical terrain schematic',
  isProcedural: true,
};

function normalizeMediaAsset(assetKey, asset) {
  const provenanceStatus = asset.provenanceStatus || 'needs-review';
  return {
    ...LOCAL_ARCHIVE_PROVENANCE,
    ...asset,
    provenanceStatus,
    credit: provenanceStatus === 'verified'
      ? asset.credit
      : 'Local archive image - provenance review needed',
    assetKey,
  };
}

/** Maps each authored scenario id to its canonical media asset key. */
const SCENARIO_ASSET_MAP = {
  fort_sumter:              'battlefield_start_of_war',
  charleston_harbor_escape: 'battlefield_start_of_war',
  naval_technology:         'art3',
  hotspur_cabinet_crisis:   'art3',
  fox_supply_crisis:        'art4',
  wolf_finance_crisis:      'art5',
  manassas_battlefield:     'battlefield_jackson_flank_march',
  seven_days:               'battlefield1',
  second_manassas:          'battlefield2',
  potomac_leverage_campaign:'battlefield_md_campaign',
  antietam:                 'map_antietam_sharpsburg',
  chancellorsville_aftermath:'battlefield3',
  susquehanna_offensive:    'battlefield4',
  gettysburg_decision:      'battlefield4',
  chickamauga:              'battlefield5',
  chattanooga_stranglehold: 'battlefield5_chattanooga',
  wilderness:               'art1',
  third_winchester:         'art2',
  petersburg_siege:         'map_petersburg_crater',
  greensboro_convention:    'map_appomattox_retreat_lines',
  appomattox_decision:      'map_appomattox_retreat_lines',
};

const SCENARIO_TACTICAL_ASSET_MAP = {
  fort_sumter: 'map_fort_sumter_charleston_harbor',
  charleston_harbor_escape: 'map_fort_sumter_charleston_harbor',
  naval_technology: 'map_fort_sumter_charleston_harbor',
  manassas_battlefield: 'map_first_manassas',
  second_manassas: 'map_second_manassas',
  seven_days: 'map_seven_days',
  antietam: 'map_antietam_sharpsburg',
  potomac_leverage_campaign: 'map_antietam_sharpsburg',
  chancellorsville_aftermath: 'map_chancellorsville',
  gettysburg_decision: 'map_gettysburg_cemetery_ridge',
  susquehanna_offensive: 'map_gettysburg_cemetery_ridge',
  third_winchester: 'map_third_winchester',
  petersburg_siege: 'map_petersburg_crater',
  appomattox_decision: 'map_appomattox_retreat_lines',
  greensboro_convention: 'map_appomattox_retreat_lines',
  wilderness: 'map_wilderness',
};

/**
 * Scenario-specific framing adjustments layered on top of the canonical asset metadata.
 * This keeps theater and tactical placement sourced from one shared catalog instead of
 * letting BattlefieldMap drift with its own local tuning table.
 */
const SCENARIO_MEDIA_OVERRIDES = {
  fort_sumter: { tacticalView: { zoom: 1.18 } },
  naval_technology: { tacticalView: { zoom: 1.15 } },
  manassas_battlefield: { tacticalView: { zoom: 1.08 } },
  second_manassas: { tacticalView: { zoom: 1.08 } },
  seven_days: { tacticalView: { zoom: 1.08 } },
  antietam: { tacticalView: { zoom: 1.16 } },
  chancellorsville_aftermath: { tacticalView: { zoom: 1.08 } },
  chickamauga: { tacticalView: { zoom: 1.1 } },
  third_winchester: { tacticalView: { zoom: 1.08 } },
  wilderness: { tacticalView: { zoom: 1.1 } },
  petersburg_siege: { tacticalView: { zoom: 1.14 } },
  appomattox_decision: { tacticalView: { zoom: 1.12 } },
};

/**
 * Resolve the best media asset for a given scenario id.
 * Always returns a complete record — never null — so callers can use it unconditionally.
 *
 * @param {string} scenarioId
 * @returns {{ src: string, kind: string, title: string, caption: string, credit: string,
 *             cropFocus: {x:number, y:number}, tacticalView: {focus:{x:number,y:number}, zoom:number},
 *             theaterOpacity: number, overlayOpacity: number, promptSeed: string,
 *             assetKey: string, scenarioId: string }}
 */
export function resolveScenarioMedia(scenarioId) {
  const assetKey = SCENARIO_ASSET_MAP[scenarioId] || 'unknown';
  const asset = normalizeMediaAsset(assetKey, ASSETS[assetKey] || ASSETS.unknown);
  const override = SCENARIO_MEDIA_OVERRIDES[scenarioId] || {};
  const tacticalView = {
    focus: asset.cropFocus || { x: 0.5, y: 0.5 },
    zoom: 1,
    ...(asset.tacticalView || {}),
    ...(override.tacticalView || {}),
  };

  return {
    ...asset,
    ...override,
    tacticalView,
    scenarioId,
  };
}

export function resolveScenarioMediaSet(scenarioId) {
  const theater = resolveScenarioMedia(scenarioId);
  const tacticalAssetKey = SCENARIO_TACTICAL_ASSET_MAP[scenarioId];
  const override = SCENARIO_MEDIA_OVERRIDES[scenarioId] || {};
  const plannedTacticalMap = tacticalAssetKey && MEDIA_CATALOG[tacticalAssetKey]
    ? {
        ...MEDIA_CATALOG[tacticalAssetKey],
        tacticalView: {
          focus: MEDIA_CATALOG[tacticalAssetKey].cropFocus || { x: 0.5, y: 0.5 },
          zoom: 1,
          ...(MEDIA_CATALOG[tacticalAssetKey].tacticalView || {}),
          ...(override.tacticalView || {}),
        },
        scenarioId,
      }
    : null;
  const proceduralTacticalMap = {
    ...PROCEDURAL_TACTICAL_MAP,
    title: `${theater.title} Tactical Schematic`,
    location: theater.location,
    era: theater.era,
    tacticalView: {
      ...PROCEDURAL_TACTICAL_MAP.tacticalView,
      ...(override.tacticalView || {}),
    },
    scenarioId,
  };

  return {
    theater,
    tacticalMap: plannedTacticalMap?.useInApp ? plannedTacticalMap : proceduralTacticalMap,
    plannedTacticalMap,
    card: null,
  };
}

/** Full catalog — exported for tooling (validator, benchmark reports, etc.) */
export const MEDIA_CATALOG = Object.fromEntries(
  Object.entries(ASSETS).map(([assetKey, asset]) => [assetKey, normalizeMediaAsset(assetKey, asset)])
);

/** Scenario → asset key mapping — exported for the content validator. */
export const SCENARIO_ASSET_MAP_EXPORT = SCENARIO_ASSET_MAP;
export const SCENARIO_TACTICAL_ASSET_MAP_EXPORT = SCENARIO_TACTICAL_ASSET_MAP;

/** Scenario → framing overrides — exported for the content validator. */
export const SCENARIO_MEDIA_OVERRIDES_EXPORT = SCENARIO_MEDIA_OVERRIDES;
