/**
 * Titans of War — Media Catalog
 *
 * Structured metadata for all historical image assets used in the game.
 * Drives the ScenarioTheater component, chronicle exports, benchmark reports,
 * and future AI image-generation prompts.
 *
 * Asset fields:
 *   src              — public-folder path (served by Vite static server)
 *   kind             — 'battlefield' | 'map' | 'art' | 'reenactment' | 'fallback'
 *   title            — human-readable label for the image
 *   location         — geographic context
 *   era              — approximate period or date string
 *   bestFor          — array of scenario ids this image best represents
 *   caption          — one-sentence historical note shown in-game
 *   credit           — provenance / license note
 *   provenanceStatus — 'verified' | 'needs-review' (defaults to needs-review)
 *   sourceInstitution— archive or institution that provided the file
 *   sourceUrl        — canonical source URL for license/provenance audit
 *   license          — concise rights label
 *   historicalMedium — period-photo | period-art | modern-photo | reenactment | generated-art | map | unknown
 *   assetRoles       — theater | tactical-underlay | card | chronicle
 *   cropFocus        — { x: 0–1, y: 0–1 } focal point for CSS object-position
 *   cropMode         — 'wide' | 'portrait' | 'contain'
 *   tacticalView     — optional { focus, zoom } tuning for BattlefieldMap underlay framing
 *   theaterOpacity   — opacity used in full-screen historical mode (0–1)
 *   overlayOpacity   — opacity used as a canvas underlay blend (0–1)
 *   promptSeed       — descriptive seed for future AI image generation
 */

const LOCAL_ARCHIVE_PROVENANCE = {
  sourceInstitution: 'Local archive',
  sourceUrl: '',
  license: 'Provenance review needed',
  historicalMedium: 'unknown',
  assetRoles: ['theater', 'tactical-underlay', 'chronicle'],
};

const ASSETS = {
  battlefield_start_of_war: {
    src: '/images/cw_pictures/battlefield start of war.jpg',
    kind: 'battlefield',
    title: 'Charleston Harbor — Opening Bombardment',
    location: 'Charleston Harbor, South Carolina',
    era: 'April 1861',
    bestFor: ['fort_sumter', 'charleston_harbor_escape'],
    caption: 'Fort Sumter in Charleston Harbor, the flashpoint where the opening crisis of the war becomes a command decision.',
    credit: 'Contemporary photograph taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Charleston harbor 1861 Confederate artillery battery dawn bombardment sepia illustration',
  },

  harbor_escape_real_photo: {
    src: '/images/cw_pictures/Second slide image after the start of war.jpeg',
    kind: 'harbor',
    title: 'Charleston Harbor — Escape Route',
    location: 'Charleston Harbor, South Carolina',
    era: 'April 1861',
    bestFor: ['charleston_harbor_escape'],
    caption: 'The real Charleston Harbor where the garrison made their desperate escape under cover of darkness.',
    credit: 'Contemporary photograph taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Charleston harbor escape boat waterway 1861 atmospheric historical',
  },

  battlefield_jackson_flank_march: {
    src: '/images/cw_pictures/battlefield Jackson flank march.jpg',
    kind: 'battlefield',
    title: "Cobble Steps — Jackson's Flank March",
    location: 'Wilderness, Virginia',
    era: 'May 2, 1863',
    bestFor: ['chancellorsville_aftermath'],
    caption: "Cobble steps along the Chancellorsville ground tied to Jackson's flank march route.",
    credit: "Photo by the creator of Titans of War of the cobble steps of Jackson's flank march",
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Chancellorsville Jackson flank march cobble steps battlefield photo',
  },

  lee_jackson_last_meeting: {
    src: '/images/cw_pictures/Lee and Jackson last meeting.jpeg',
    kind: 'art',
    title: "Lee and Jackson's Last Meeting",
    location: 'Chancellorsville, Virginia',
    era: 'May 1-2, 1863',
    bestFor: ['chancellorsville_maneuver'],
    caption: "Lee and Jackson confer before the flank march that turned Hooker's right at Chancellorsville.",
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.36 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'Lee and Jackson last meeting Chancellorsville command conference generated theater art',
  },

  ricketts_battery_first_manassas: {
    src: '/images/cw_pictures/MNBPRickettsBatteryPainting.jpg',
    kind: 'battlefield',
    title: "Ricketts' Battery — First Manassas",
    location: 'Henry Hill, Prince William County, Virginia',
    era: 'July 21, 1861',
    bestFor: ['manassas_battlefield'],
    caption: "Union artillery under Captain James Ricketts holds its ground at Henry Hill during the opening Confederate assault.",
    credit: 'National Military Park Service — Public Domain',
    provenanceStatus: 'verified',
    sourceInstitution: 'Manassas National Battlefield Park',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:MNBPRickettsBatteryPainting.jpg',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'First Manassas Henry Hill Ricketts Battery Union artillery Confederate charge 1861',
  },

  hunley_submarine: {
    src: '/images/cw_pictures/Conrad_Wise_Chapman_-_Submarine_Torpedo_Boat_H.L._Hunley,_Dec._6,_1863_(cropped).jpg',
    kind: 'naval',
    title: 'H.L. Hunley — Confederate Submarine',
    location: 'Charleston Harbor, South Carolina',
    era: 'December 6, 1863',
    bestFor: ['naval_technology'],
    caption: 'Conrad Wise Chapman\'s rendering of the H.L. Hunley, the experimental Confederate submarine that sank the USS Housatonic in the first successful submarine attack in naval history.',
    credit: 'Conrad Wise Chapman — Public Domain',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Conrad_Wise_Chapman_-_Submarine_Torpedo_Boat_H.L._Hunley,_Dec._6,_1863.jpg',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'H.L. Hunley submarine Confederate naval experimental torpedo boat Charleston 1863',
  },

  hunley_project_art: {
    src: '/images/cw_pictures/The Hunley.jpeg',
    kind: 'art',
    title: 'The Hunley at Charleston',
    location: 'Charleston Harbor, South Carolina',
    era: '1863',
    bestFor: ['naval_technology'],
    caption: 'A project-owned dramatic rendering of the H.L. Hunley at dock before its hazardous torpedo work against the blockade.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.46, y: 0.56 },
    cropMode: 'portrait',
    theaterOpacity: 0.95,
    overlayOpacity: 0.3,
    promptSeed: 'H.L. Hunley at Charleston dock dusk harbor crew torpedo boat generated theater art',
  },

  battlefield1: {
    src: '/images/cw_pictures/battlefield1.jpg',
    kind: 'battlefield',
    title: 'The Seven Days — Richmond Perimeter',
    location: 'Peninsula, Virginia',
    era: 'June–July 1862',
    bestFor: ['seven_days'],
    caption: "McClellan's advance stalls against Lee's aggressive counter-offensive outside Richmond.",
    credit: 'Contemporary photograph taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.4 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Richmond Virginia 1862 Civil War battlefield artillery charge sepia',
  },

  mcclellan_seven_days_grok: {
    src: '/images/cw_pictures/General McClellan at Seven Days.jpeg',
    kind: 'art',
    title: 'McClellan at the Seven Days',
    location: 'Richmond approaches, Virginia',
    era: 'June 1862',
    bestFor: ['seven_days'],
    caption: 'McClellan surveys the Richmond approaches as Lee tries to turn Federal weight and caution into a retreat down the Peninsula.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.58, y: 0.46 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'General McClellan Seven Days Richmond peninsula command view generated theater art',
  },

  gettysburg_thulstrup_1887: {
    src: '/images/cw_pictures/Thure de Thulstrup - L. Prang and Co. - Battle of Gettysburg - Restoration by Adam Cuerden.jpg',
    kind: 'battlefield',
    title: 'The Battle of Gettysburg — Thulstrup',
    location: 'Gettysburg, Pennsylvania',
    era: 'July 1863',
    bestFor: ['gettysburg_decision'],
    caption: 'Thure de Thulstrup\'s dramatic 1887 restoration of the pivotal moment at Gettysburg, published by L. Prang and Company.',
    credit: 'Thure de Thulstrup, L. Prang and Co. — Public Domain',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress Prints and Photographs',
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Thure_de_Thulstrup',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Battle of Gettysburg 1863 Thulstrup period illustration charge cavalry artillery',
  },

  second_bull_run_lithograph: {
    src: '/images/cw_pictures/Second_Battle_of_Bull_Run_1860s_lithograph_currier_and_ives.jpg',
    kind: 'battlefield',
    title: 'Second Battle of Bull Run — Currier & Ives',
    location: 'Prince William County, Virginia',
    era: 'August 28–30, 1862',
    bestFor: ['second_manassas'],
    caption: 'The Second Battle of Bull Run (Second Manassas) where Longstreet\'s flank assault routed Union forces in one of the war\'s pivotal victories.',
    credit: 'Currier & Ives lithograph — Public Domain',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress',
    sourceUrl: 'https://commons.wikimedia.org/wiki/Category:Currier_%26_Ives',
    license: 'Public Domain',
    historicalMedium: 'period-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Second Bull Run 1862 Currier Ives lithograph Civil War battle',
  },

  x3_battlefield_action: {
    src: '/images/cw_pictures/X3.jpeg',
    kind: 'art',
    title: 'Field Assault — Entrenchments and Smoke',
    location: 'Virginia campaign field',
    era: '1862-1864',
    bestFor: ['wilderness'],
    caption: 'Close-range assault imagery used for campaigns where shock, fieldworks, and rapid decision pressure dominate the player choice.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.54 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'Civil War field assault entrenchments smoke photorealistic theater art',
  },

  jackson_second_manassas_grok: {
    src: '/images/cw_pictures/Jackson second Manassas.jpeg',
    kind: 'art',
    title: 'Jackson at Second Manassas',
    location: 'Prince William County, Virginia',
    era: 'August 28-30, 1862',
    bestFor: ['second_manassas'],
    caption: 'Jackson holds Pope in place near the unfinished railroad while Longstreet prepares the flank blow that makes Second Manassas a campaign trap.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.48 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'Stonewall Jackson Second Manassas battlefield artillery smoke Longstreet flank attack generated theater art',
  },

  dictator_cannon_petersburg: {
    src: '/images/cw_pictures/battlefield2.jpg',
    kind: 'artillery',
    title: 'The Dictator — Petersburg Siege Artillery',
    location: 'Petersburg, Virginia',
    era: 'June 1864 – April 1865',
    bestFor: ['petersburg_siege'],
    caption: 'Union\'s massive "Dictator" mortar battery overlooking the Petersburg siege lines—a symbol of Northern industrial power.',
    credit: 'Contemporary photograph taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Petersburg siege Dictator cannon Union artillery massive mortar 1864 1865',
  },

  battlefield_md_campaign: {
    src: '/images/cw_pictures/battlefield MD campaign.jpg',
    kind: 'battlefield',
    title: 'Maryland Campaign — Stone Bridge Crossing',
    location: 'Sharpsburg, Maryland',
    era: 'September 1862',
    bestFor: ['potomac_leverage_campaign'],
    caption: 'A Maryland battlefield bridge frames Lee\'s campaign as a problem of Potomac crossings, road control, and political leverage before Sharpsburg fixes the map.',
    credit: 'Contemporary battlefield photograph taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.48 },
    cropMode: 'wide',
    theaterOpacity: 0.92,
    overlayOpacity: 0.33,
    promptSeed: 'Maryland campaign Antietam bridge Potomac crossing battlefield photo',
  },

  antietam_thulstrup_1887: {
    src: '/images/cw_pictures/Antietam Thulstrup, Thure de 1887.png',
    kind: 'art',
    title: 'Battle of Antietam — Thulstrup Print',
    location: 'Sharpsburg, Maryland',
    era: 'September 17, 1862',
    bestFor: ['antietam'],
    caption: 'Thure de Thulstrup\'s late-19th-century print captures the violence around Antietam as the Maryland campaign reaches its decisive shock point.',
    credit: 'Library of Congress / Thure de Thulstrup / L. Prang & Co.',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress Prints and Photographs Division',
    sourceUrl: 'https://www.loc.gov/pictures/item/2003663827/',
    license: 'No known restrictions on publication',
    historicalMedium: 'period-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Antietam Sharpsburg Thulstrup print Union and Confederate infantry collision',
  },

  battlefield3: {
    src: '/images/cw_pictures/battlefield3.jpg',
    kind: 'battlefield',
    title: 'Chancellorsville — The Rappahannock Line',
    location: 'Spotsylvania County, Virginia',
    era: 'May 1–6, 1863',
    bestFor: ['chancellorsville_aftermath'],
    caption: "After Hooker's retreat, Lee consolidates along the Rappahannock River.",
    credit: 'Contemporary battlefield photograph taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Rappahannock River Virginia 1863 Confederate defensive line sepia illustration',
  },

  fredericksburg_rappahannock_winter: {
    src: '/images/cw_pictures/battlefield3.jpg',
    kind: 'battlefield',
    title: 'Fredericksburg Winter Camps — Rappahannock Line',
    location: 'Fredericksburg, Virginia',
    era: 'December 1862 - January 1863',
    bestFor: ['fredericksburg_winter_politics'],
    caption: 'After Fredericksburg, victory gives way to winter camps, burial flags, and the political labor of keeping the army fit for spring.',
    credit: 'Contemporary battlefield photograph taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Fredericksburg Virginia winter camps Rappahannock burial flags Christmas fraternization sepia illustration',
  },

  battlefield4: {
    src: '/images/cw_pictures/battlefield4.jpg',
    kind: 'battlefield',
    title: 'Pennsylvania Invasion — Susquehanna Corridor',
    location: 'South-central Pennsylvania',
    era: 'June–July 1863',
    bestFor: ['gettysburg_campaign_setup', 'gettysburg_with_jackson_setup', 'susquehanna_offensive', 'gettysburg_decision'],
    caption: 'Confederate columns spread alarm through Pennsylvania, threatening the Susquehanna crossings.',
    credit: 'Contemporary battlefield photograph taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Pennsylvania 1863 Civil War Confederate march farmland hills sepia illustration',
  },

  battlefield5: {
    src: '/images/cw_pictures/battlefield5.jpg',
    kind: 'battlefield',
    title: 'Chickamauga — The Western Theater',
    location: 'Walker County, Georgia',
    era: 'September 18–20, 1863',
    bestFor: ['chickamauga'],
    caption: "Bragg's Army of Tennessee drives Rosecrans from the field in the deadliest Western Theater battle.",
    credit: 'Contemporary battlefield photograph taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Chickamauga Georgia 1863 Civil War infantry battle woodland sepia',
  },

  chickamauga_close_battle_grok: {
    src: '/images/cw_pictures/generic battle scene 3.jpeg',
    kind: 'art',
    title: 'Chickamauga — Close-Range Field Chaos',
    location: 'Walker County, Georgia',
    era: 'September 18-20, 1863',
    bestFor: ['chickamauga'],
    caption: 'Dense smoke, close-range infantry, and confused artillery fire stand in for Chickamauga\'s chaotic Western Theater fight without reusing Antietam imagery.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.52 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'Chickamauga River of Death dense smoke close infantry combat generated theater art',
  },

  atlanta_campaign_georgia_fallback: {
    src: '/images/cw_pictures/battlefield5.jpg',
    kind: 'battlefield',
    title: 'North Georgia Campaign — Approaches to Atlanta',
    location: 'North Georgia rail corridor',
    era: 'Summer 1864',
    bestFor: ['atlanta_election_pressure', 'greensboro_convention'],
    caption: 'Temporary Western Theater artwork used for the march on Atlanta until a dedicated Atlanta or Cold Harbor replacement is selected.',
    credit: 'Contemporary battlefield photograph taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.48 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'North Georgia 1864 railroad corridor hills Confederate retreat Sherman advance sepia illustration',
  },

  atlanta_burning_grok: {
    src: '/images/cw_pictures/Burning of Atlanta.jpeg',
    kind: 'art',
    title: 'Atlanta in Flames — Election Shock',
    location: 'Atlanta, Georgia',
    era: 'September 1864',
    bestFor: ['fall_of_atlanta'],
    caption: 'Atlanta burns as Sherman\'s success reshapes Northern politics, Southern morale, and the last hope of changing the 1864 election clock.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.52, y: 0.46 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'Atlanta burning Sherman campaign 1864 city in flames generated theater art',
  },

  battlefield5_chattanooga: {
    src: '/images/cw_pictures/battlefield 5.jpg',
    kind: 'battlefield',
    title: 'Chattanooga Stranglehold — Ridge Siege',
    location: 'Hamilton County, Tennessee',
    era: 'October–November 1863',
    bestFor: ['chattanooga_stranglehold'],
    caption: 'Confederate forces hold the ridgelines above Chattanooga, besieging the Union garrison below.',
    credit: 'Contemporary battlefield photograph taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.4 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.35,
    promptSeed: 'Chattanooga Tennessee 1863 ridge siege Confederate artillery overlook sepia',
  },

  chattanooga_reenactment_ridge: {
    src: '/images/cw_pictures/re-enactment.jpg',
    kind: 'reenactment',
    title: 'Chattanooga Ridge Line',
    location: 'Chattanooga, Tennessee',
    era: 'October-November 1863',
    bestFor: ['chattanooga_stranglehold'],
    caption: 'Confederate infantry hold a smoky ridge line as the fight for the rail gateway into Georgia tightens around Chattanooga.',
    credit: 'Contemporary reenactment photograph taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    assetRoles: ['theater', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.38, y: 0.46 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.3,
    promptSeed: 'Chattanooga ridge Confederate line smoke reenactment theater image',
  },

  forrest_bragg_chattanooga_grok: {
    src: '/images/cw_pictures/General Forrest and General Bragg at Chattanooga.jpeg',
    kind: 'art',
    title: 'Forrest and Bragg at Chattanooga',
    location: 'Chattanooga, Tennessee',
    era: 'October-November 1863',
    bestFor: ['chattanooga_stranglehold'],
    caption: 'The image centers the command friction inside the Confederate high command after Chickamauga, when tactical advantage and personal mistrust pulled in opposite directions.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.44 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.3,
    promptSeed: 'Forrest Bragg argument Chattanooga campaign command dispute generated theater art',
  },

  art1: {
    src: '/images/cw_pictures/art1.jpg',
    kind: 'art',
    title: 'The Wilderness — Burning Forest',
    location: 'Spotsylvania County, Virginia',
    era: 'May 5–7, 1864',
    bestFor: ['wilderness'],
    caption: 'The tangled Wilderness burns as Grant and Lee clash in the dense Virginia woodland.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.88,
    overlayOpacity: 0.3,
    promptSeed: 'Wilderness Virginia 1864 Civil War forest fire infantry clash dark atmospheric artwork',
  },

  grant_overland_command: {
    src: '/images/cw_pictures/Grant at Cold Harbor.jpeg',
    kind: 'art',
    title: 'Grant at Cold Harbor',
    location: 'Cold Harbor, Virginia',
    era: 'June 1864',
    bestFor: ['cold_harbor'],
    caption: 'Grant studies the lines at Cold Harbor as the Overland Campaign hardens into trench warfare and politically costly slaughter. The sharper render is used as the primary theater image.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.46, y: 0.47 },
    cropMode: 'wide',
    theaterOpacity: 0.94,
    overlayOpacity: 0.32,
    promptSeed: 'Grant Virginia overland campaign command tent generated theater art',
  },

  lee_before_wilderness_grok: {
    src: '/images/cw_pictures/Lee before a battle .jpeg',
    kind: 'art',
    title: 'Lee Before the Wilderness Counterstroke',
    location: 'Wilderness, Virginia',
    era: 'May 6, 1864',
    bestFor: ['wilderness_opening'],
    caption: 'Lee faces the crisis of the Wilderness before Longstreet arrives, with the army staggered and the Texas Brigade about to become decisive.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.34 },
    cropMode: 'portrait',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'Robert E Lee before Wilderness battle Texas Brigade Longstreet reinforcements generated theater art',
  },

  grant_meade_overland_grok: {
    src: '/images/cw_pictures/Grant and Meade updated.jpeg',
    kind: 'art',
    title: 'Grant and Meade in the Overland',
    location: 'Wilderness, Virginia',
    era: 'May 1864',
    bestFor: ['wilderness'],
    caption: 'Grant and Meade confer in the Virginia woods as the Overland Campaign begins its relentless southward grind.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.48, y: 0.36 },
    cropMode: 'portrait',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'Grant and Meade overland campaign Virginia woods generated theater art',
  },

  art2: {
    src: '/images/cw_pictures/art2.jpg',
    kind: 'art',
    title: 'Third Winchester — Valley Campaign',
    location: 'Winchester, Virginia',
    era: 'September 19, 1864',
    bestFor: ['third_winchester'],
    caption: "Sheridan's cavalry and infantry drive Early's Army of the Valley from Winchester.",
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.88,
    overlayOpacity: 0.3,
    promptSeed: 'Shenandoah Valley 1864 Civil War cavalry charge Union attack sepia artwork',
  },

  third_winchester_grok: {
    src: '/images/cw_pictures/Third Battle of Winchester.jpeg',
    kind: 'art',
    title: 'Third Winchester — Valley Crisis',
    location: 'Winchester, Virginia',
    era: 'September 19, 1864',
    bestFor: ['third_winchester'],
    caption: 'The Third Battle of Winchester opens the Valley to Sheridan and turns the Shenandoah into a final struggle over grain, mobility, and morale.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.54, y: 0.44 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'Third Winchester cavalry artillery valley battle generated theater art',
  },

  first_winchester_valley_reference: {
    src: '/images/cw_pictures/Jackon marches to first Winchester Gemini.PNG',
    kind: 'art',
    title: 'Jackson Marches to First Winchester',
    location: 'Winchester, Virginia',
    era: 'May 1862',
    bestFor: ['first_winchester'],
    caption: 'Jackson drives up the Valley roads through mud and mountain weather toward First Winchester and the lower Shenandoah granary corridor.',
    credit: 'AI-generated image created by the project author with Google Gemini image generation',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    useInApp: true,
    cropFocus: { x: 0.56, y: 0.46 },
    cropMode: 'wide',
    theaterOpacity: 0.94,
    overlayOpacity: 0.32,
    promptSeed: 'Jackson Valley campaign march to First Winchester storm clouds road column',
  },

  x2_pennsylvania_campaign: {
    src: '/images/cw_pictures/X2.jpeg',
    kind: 'art',
    title: 'Pennsylvania Campaign — Tempo Before Contact',
    location: 'Pennsylvania campaign corridor',
    era: 'June-July 1863',
    bestFor: ['gettysburg_with_jackson_setup'],
    caption: 'A young soldier framed by guns and smoke gives the Jackson-survives Pennsylvania campaign a human, pre-contact tension distinct from Petersburg or Gettysburg battle art.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.4 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.3,
    promptSeed: 'Pennsylvania campaign Civil War soldier artillery smoke pre battle tension generated theater art',
  },

  new_market_valley_reference: {
    src: '/images/cw_pictures/art2.jpg',
    kind: 'art',
    title: 'New Market — Valley Wheatfields Reference',
    location: 'New Market, Virginia',
    era: 'May 1864',
    bestFor: ['new_market'],
    caption: 'Reference Valley campaign artwork used for New Market, Bushong Farm, and the middle Shenandoah grain belt.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.88,
    overlayOpacity: 0.3,
    promptSeed: 'New Market Virginia cadets rain wheatfields Shenandoah Valley sepia artwork',
  },

  new_market_cadets_grok: {
    src: '/images/cw_pictures/VMI cadets New Market Gemini.PNG',
    kind: 'art',
    title: 'New Market — VMI Cadets',
    location: 'New Market, Virginia',
    era: 'May 1864',
    bestFor: ['new_market'],
    caption: 'The cadets press through smoke and wheatfields as New Market becomes a manpower, morale, and Valley food-supply decision point.',
    credit: 'AI-generated image created by the project author with Google Gemini image generation',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.47 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'New Market VMI cadets charge Virginia flag generated theater art',
  },

  christmas_truce_winter: {
    src: '/images/cw_pictures/Christmas Truce.jpeg',
    kind: 'art',
    title: 'Christmas Truce of 1862',
    location: 'Rappahannock winter lines, Virginia',
    era: 'December 1862',
    bestFor: ['fredericksburg_winter_politics'],
    caption: 'A winter truce scene frames the strange calm after Fredericksburg, when camps, politics, and the possibility of temporary humanity interrupted slaughter.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.34 },
    cropMode: 'wide',
    theaterOpacity: 0.94,
    overlayOpacity: 0.3,
    promptSeed: 'Christmas truce 1862 Civil War winter camps generated theater art',
  },

  cedar_creek_belle_grove_reference: {
    src: '/images/cw_pictures/art2.jpg',
    kind: 'art',
    title: 'Cedar Creek — Belle Grove Reference Theater',
    location: 'Belle Grove / Middletown, Virginia',
    era: 'October 1864',
    bestFor: ['cedar_creek'],
    caption: 'Reference Shenandoah artwork used for Cedar Creek, Belle Grove, and the final fight over the Valley granaries.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.88,
    overlayOpacity: 0.3,
    promptSeed: 'Cedar Creek Belle Grove dawn Shenandoah Valley autumn mist sepia artwork',
  },

  cedar_creek_reenactment: {
    src: '/images/cw_pictures/re-enactment2.jpg',
    kind: 'reenactment',
    title: 'Cedar Creek — Valley Counterstroke',
    location: 'Belle Grove / Middletown, Virginia',
    era: 'October 1864',
    bestFor: ['cedar_creek'],
    caption: 'A reenactment view of mounted movement and infantry lines fits Cedar Creek\'s dawn attack and the violent afternoon reversal that decided the Valley.',
    credit: 'Contemporary reenactment photograph taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.48, y: 0.56 },
    cropMode: 'wide',
    theaterOpacity: 0.9,
    overlayOpacity: 0.3,
    promptSeed: 'Cedar Creek reenactment cavalry infantry valley theater image',
  },

  art3: {
    src: '/images/cw_pictures/art3.jpg',
    kind: 'art',
    title: 'Richmond War Cabinet — Fire-Eaters Session',
    location: 'Richmond, Virginia',
    era: '1861–1865',
    bestFor: ['hotspur_cabinet_crisis', 'naval_technology'],
    caption: 'The Confederate cabinet debates the crisis of political resolve and offensive action.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.85,
    overlayOpacity: 0.3,
    promptSeed: 'Confederate Richmond cabinet war council 1862 political figures dramatic lighting artwork',
  },

  davis_cabinet_grok: {
    src: '/images/cw_pictures/Davis cabinet.jpeg',
    kind: 'art',
    title: 'Jefferson Davis and Cabinet',
    location: 'Richmond, Virginia',
    era: '1862-1865',
    bestFor: ['naval_technology', 'hotspur_cabinet_crisis'],
    caption: 'Davis and his ministers frame the war as a sequence of cabinet fights over escalation, resources, and political survival.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.46 },
    cropMode: 'wide',
    theaterOpacity: 0.93,
    overlayOpacity: 0.28,
    promptSeed: 'Jefferson Davis cabinet Richmond war council generated theater art',
  },

  davis_lee_war_room: {
    src: '/images/cw_pictures/Davis and Lee.jpeg',
    kind: 'art',
    title: 'Davis and Lee — Late War Strategy Room',
    location: 'Richmond, Virginia',
    era: '1864',
    bestFor: ['atlanta_election_pressure'],
    caption: 'Davis and Lee weigh Atlanta, industrial survival, and the 1864 election clock as late-war strategy collapses into political crisis.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.47 },
    cropMode: 'wide',
    theaterOpacity: 0.93,
    overlayOpacity: 0.28,
    promptSeed: 'Jefferson Davis Robert E Lee Richmond late war strategy room generated theater art',
  },

  csa_victory_condition_grok: {
    src: '/images/cw_pictures/CSA Independence.jpeg',
    kind: 'art',
    title: 'Confederate Independence Victory Condition',
    location: 'Richmond, Virginia',
    era: 'Alternate 1865',
    bestFor: ['gettysburg_recognition_crisis', 'southern_independence_1864'],
    caption: 'Reserved result art for the rare full-independence ending: the hardest alternate-history line in the campaign.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'portrait',
    theaterOpacity: 0.95,
    overlayOpacity: 0.28,
    promptSeed: 'Confederate independence alternate history victory parade Richmond capitol generated ending art',
  },

  mcclellan_armistice_grok: {
    src: '/images/cw_pictures/Armistice.jpeg',
    kind: 'art',
    title: 'McClellan Armistice and Conditional Reunion',
    location: 'Virginia peace line',
    era: 'Alternate 1865',
    bestFor: ['election_1864_mcclellan', 'southern_independence_1864'],
    caption: 'Reserved result art for the McClellan victory route: an armistice and proposed constitutional settlement, not automatic Southern independence.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.48 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.28,
    promptSeed: 'McClellan Lee armistice conditional reunion Civil War alternate history generated ending art',
  },

  lee_at_fredericksburg: {
    src: '/images/cw_pictures/Lee at Fredricksburg.jpeg',
    kind: 'art',
    title: 'Lee at Fredericksburg — Before the Battle',
    location: 'Fredericksburg, Virginia',
    era: 'December 1862',
    bestFor: ['fredericksburg_winter_politics'],
    caption: 'Lee stands resolute before Fredericksburg, commanding the heights above the Rappahannock as Northern columns prepare their assault.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.94,
    overlayOpacity: 0.32,
    promptSeed: 'Robert E Lee Fredericksburg Virginia 1862 battle command portrait generated theater art',
  },

  lincoln_cabinet_grok: {
    src: '/images/cw_pictures/Lincoln Cabinet.jpeg',
    kind: 'art',
    title: 'Lincoln and Cabinet',
    location: 'Washington, D.C.',
    era: 'April 1861',
    bestFor: ['radical_republican_crisis', 'greensboro_convention'],
    caption: 'Lincoln and his cabinet face the political consequences of the Fort Sumter crisis as mobilization, restraint, and border-state pressure collide.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.47 },
    cropMode: 'wide',
    theaterOpacity: 0.93,
    overlayOpacity: 0.28,
    promptSeed: 'Lincoln cabinet war settlement generated theater art',
  },

  art4: {
    src: '/images/cw_pictures/art4.jpg',
    kind: 'art',
    title: 'Quartermaster Emergency — Supply Lines',
    location: 'Confederate Supply Corridor',
    era: '1862–1864',
    bestFor: ['fox_supply_crisis'],
    caption: "Strained rail and supply networks threaten the army's ability to remain in the field.",
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.85,
    overlayOpacity: 0.3,
    promptSeed: 'Confederate supply wagon train railroad 1862 quartermaster logistics sepia artwork',
  },

  art5: {
    src: '/images/cw_pictures/art5.jpg',
    kind: 'art',
    title: 'Confederate Treasury — Bond Crisis',
    location: 'Richmond, Virginia',
    era: '1863–1864',
    bestFor: ['wolf_finance_crisis'],
    caption: 'Inflation, blockade, and bond-market collapse threaten the Confederate financial system.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.85,
    overlayOpacity: 0.3,
    promptSeed: 'Confederate treasury Richmond inflation bond market political crisis 1863 artwork',
  },

  reenactment: {
    src: '/images/cw_pictures/re-enactment.jpg',
    kind: 'reenactment',
    title: 'Petersburg Siege Lines',
    location: 'Petersburg, Virginia',
    era: 'June 1864 – April 1865',
    bestFor: ['petersburg_siege'],
    caption: "Union miners detonate the Crater beneath Confederate lines — the explosion that changed the siege.",
    credit: 'Contemporary photograph / reenactment taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.88,
    overlayOpacity: 0.3,
    promptSeed: 'Petersburg Virginia 1864 siege trench warfare Union Confederate lines Civil War reenactment',
  },

  reenactment2: {
    src: '/images/cw_pictures/re-enactment2.jpg',
    kind: 'reenactment',
    title: 'Appomattox Court House — Final Days',
    location: 'Appomattox, Virginia',
    era: 'April 1865',
    bestFor: ['greensboro_convention', 'appomattox_decision'],
    caption: "Lee's remaining columns face the final decision: surrender with honor or dissolution.",
    credit: 'Contemporary photograph / reenactment taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.88,
    overlayOpacity: 0.3,
    promptSeed: 'Appomattox Virginia 1865 Confederate surrender honor final campaign Civil War reenactment',
  },

  unknown: {
    src: '/images/cw_pictures/unknown.svg',
    kind: 'fallback',
    title: 'Procedural Civil War Theater',
    location: 'Eastern Theater, 1861–1865',
    era: '1861–1865',
    bestFor: [],
    caption: 'Procedural tactical backdrop used when no verified historical asset is available for public release.',
    credit: 'Generated by the Titans of War interface',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'MIT',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'wide',
    theaterOpacity: 0.85,
    overlayOpacity: 0.3,
    promptSeed: 'Civil War 1861 battlefield sepia period illustration',
  },

  map_fort_sumter_charleston_harbor: {
    src: '/images/cw_pictures/map_fort_sumter_charleston_harbor_loc.jpg',
    kind: 'map',
    title: 'Plan of Charleston Harbor and Fortifications',
    location: 'Charleston Harbor, South Carolina',
    era: 'April 1861',
    bestFor: ['fort_sumter', 'charleston_harbor_escape'],
    caption: 'Library of Congress map plate for Charleston Harbor and Fort Sumter approaches.',
    credit: 'Library of Congress Geography and Map Division — Public Domain',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd391:g3912:g3912c:cw0362000/full/pct:25/0/default.jpg',
    license: 'Public Domain',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    tacticalView: { zoom: 1 },
    theaterOpacity: 0.92,
    overlayOpacity: 0.45,
    promptSeed: 'Charleston Harbor Fort Sumter 1861 historical military map',
  },

  map_antietam_sharpsburg: {
    src: '/images/cw_pictures/map_antietam_sharpsburg_loc.jpg',
    kind: 'map',
    title: 'Sharpsburg and Dunker Church Approaches',
    location: 'Sharpsburg, Maryland',
    era: 'September 1862',
    bestFor: ['antietam', 'potomac_leverage_campaign'],
    caption: 'Topographical approach map for Sharpsburg approaches and Antietam Creek sectors.',
    credit: 'Geography & Map Division, Library of Congress, Washington, D.C.',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd384:g3844:g3844s:cw0252000/full/pct:25/0/default.jpg',
    license: 'Public Domain',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.92,
    overlayOpacity: 0.45,
    promptSeed: 'Antietam Sharpsburg Dunker Church historical topographical map',
  },

  map_shiloh_buell: {
    src: '/images/cw_pictures/map_shiloh_buell_loc.jpg',
    kind: 'map',
    title: "General Buell's Map of the Battle-Field of Shiloh",
    location: 'Shiloh / Pittsburg Landing, Tennessee',
    era: 'April 1862',
    bestFor: ['shiloh_army_of_tennessee'],
    caption: 'Detailed historical battle map of Shiloh showing roads, camps, field sectors, and the approaches to Pittsburg Landing.',
    credit: 'Library of Congress Geography and Map Division — Public Domain',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd396:g3964:g3964s:cw0435000/full/pct:25/0/default.jpg',
    license: 'Public Domain',
    historicalMedium: 'map',
    assetRoles: ['theater', 'tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.92,
    overlayOpacity: 0.45,
    promptSeed: 'Shiloh Pittsburg Landing Albert Sidney Johnston historical battle map',
  },

  shiloh_ai_gen: {
    src: '/images/cw_pictures/Shiloh AI Gen.jpeg',
    kind: 'art',
    title: 'Shiloh — AI Theater Render',
    location: 'Shiloh / Pittsburg Landing, Tennessee',
    era: 'April 1862',
    bestFor: ['shiloh_army_of_tennessee'],
    caption: 'Primary theater image for Shiloh, emphasizing the surprise collapse of the Union camps near Pittsburg Landing.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.44 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'Shiloh surprise attack dawn at Pittsburg Landing painterly theater image',
  },

  shiloh_pittsburg_landing_theater_flux2: {
    src: '/images/cw_pictures/shiloh_pittsburg_landing_theater_flux2.jpg',
    kind: 'art',
    title: 'Shiloh at Pittsburg Landing — Flux2 Theater Render',
    location: 'Shiloh / Pittsburg Landing, Tennessee',
    era: 'April 1862',
    bestFor: ['shiloh_army_of_tennessee'],
    caption: 'Generated theater art emphasizing the wooded shock of Shiloh, the pressure toward Pittsburg Landing, and the Western Theater stakes of command cohesion.',
    credit: 'Generated by Titans Forge with local FLUX.2 Klein 9B',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge local image engine',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War/blob/main/docs/image-generation-pipeline.md',
    license: 'Excluded from public release; local FLUX.2 Klein 9B non-commercial model license',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.46 },
    cropMode: 'wide',
    theaterOpacity: 0.94,
    overlayOpacity: 0.32,
    promptSeed: 'Shiloh wooded assault Pittsburg Landing river steamers generated theater art',
  },

  petersburg_ai_gen: {
    src: '/images/cw_pictures/battle of petersburg.jpeg',
    kind: 'art',
    title: 'Petersburg — AI Theater Render',
    location: 'Petersburg, Virginia',
    era: '1864-1865',
    bestFor: ['black_confederate_debate', 'petersburg_siege'],
    caption: 'Primary theater image for the Petersburg front and the late-war manpower politics bound up with the final defense of Richmond.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.46 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'Petersburg trenches siege collapse AI theater image',
  },

  five_forks_generated_battle: {
    src: '/images/cw_pictures/generic battle scene 2.jpeg',
    kind: 'art',
    title: 'Five Forks — The Last Railroad Flank',
    location: 'Dinwiddie County, Virginia',
    era: 'April 1, 1865',
    bestFor: ['five_forks'],
    caption: 'Close infantry and artillery combat represents the collapse of Pickett\'s exposed line as Sheridan and Warren turn the last railroad flank southwest of Petersburg.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.42 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'Five Forks Virginia April 1865 railroad flank infantry battle generated theater art',
  },

  richmond_ct_parade_grok: {
    src: '/images/cw_pictures/CSA colored CTs parade in Richmond March 1865.JPG',
    kind: 'art',
    title: 'Richmond CT Parade — March 1865',
    location: 'Richmond, Virginia',
    era: 'March 1865',
    bestFor: ['black_confederate_debate'],
    caption: 'A late-war Richmond parade frames the political fight over recruiting Colored Troops and the limits of Confederate manpower policy.',
    credit: 'AI-generated image created by the project author with Grok Imagine',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.66 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.3,
    promptSeed: 'Richmond March 1865 Colored Troops parade Confederate manpower debate generated theater art',
  },

  richmond_burns_grok: {
    src: '/images/cw_pictures/Richmond burns 1864.jpeg',
    kind: 'art',
    title: 'Richmond Evacuation — The Capital Burns',
    location: 'Richmond, Virginia',
    era: 'April 1865',
    bestFor: ['richmond_evacuation'],
    caption: 'The Confederate capital burns along the James as evacuation, collapse, and the last political decisions race each other to the end.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.45 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'Richmond burns evacuation generated theater art',
  },

  richmond_evacuation_theater_flux2: {
    src: '/images/cw_pictures/richmond_evacuation_theater_flux2.jpg',
    kind: 'art',
    title: 'Richmond Evacuation — Flux2 Theater Render',
    location: 'Richmond, Virginia',
    era: 'April 1865',
    bestFor: ['richmond_evacuation'],
    caption: 'Generated theater art of Confederate columns leaving Richmond through smoke, fires, and civilian traffic as the capital collapses behind them.',
    credit: 'Generated by Titans Forge with local FLUX.2 Klein 9B',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge local image engine',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War/blob/main/docs/image-generation-pipeline.md',
    license: 'Excluded from public release; local FLUX.2 Klein 9B non-commercial model license',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.54, y: 0.48 },
    cropMode: 'wide',
    theaterOpacity: 0.94,
    overlayOpacity: 0.32,
    promptSeed: 'Richmond evacuation fires civilians wagons night march generated theater art',
  },

  appomattox_ai_gen: {
    src: '/images/cw_pictures/Appomattox.jpeg',
    kind: 'art',
    title: 'Appomattox — AI Theater Render',
    location: 'Appomattox Court House, Virginia',
    era: 'April 1865',
    bestFor: ['appomattox_decision', 'greensboro_convention'],
    caption: 'Primary theater image for the final surrender settlement and the last political choices around Confederate collapse.',
    credit: 'AI-generated image created by the project author',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'generated-art',
    assetRoles: ['theater', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.46 },
    cropMode: 'wide',
    theaterOpacity: 0.95,
    overlayOpacity: 0.32,
    promptSeed: 'Appomattox surrender settlement AI theater image',
  },


  map_gettysburg_cemetery_ridge: {
    src: '/images/cw_pictures/map_gettysburg_cemetery_ridge_loc.jpg',
    kind: 'earthworks',
    title: 'Gettysburg Cemetery Ridge — Earthworks Photograph',
    location: 'Gettysburg, Pennsylvania',
    era: 'July 1863',
    bestFor: ['gettysburg_campaign_setup', 'gettysburg_with_jackson_setup', 'gettysburg_decision', 'gettysburg_with_jackson', 'susquehanna_offensive'],
    caption: 'Historic earthworks and defensive positions at Cemetery Ridge and Round Tops as they stand today at the battlefield.',
    credit: 'Contemporary photograph taken by the creator of Titans of War',
    provenanceStatus: 'verified',
    sourceInstitution: 'Titans Forge project archive',
    sourceUrl: 'https://github.com/JCapone83/Titans_of_War',
    license: 'CC BY 4.0 project media',
    historicalMedium: 'modern-photo',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.92,
    overlayOpacity: 0.45,
    promptSeed: 'Gettysburg Cemetery Ridge Round Tops earthworks trenches defensive position',
  },


  map_petersburg_crater: {
    src: '/images/cw_pictures/map_petersburg_crater_loc.jpg',
    kind: 'map',
    title: 'Petersburg Siege Lines and Crater',
    location: 'Petersburg, Virginia',
    era: '1864',
    bestFor: ['petersburg_siege'],
    caption: 'Detailed siege map showing Petersburg trench lines and Crater breach coordinates.',
    credit: 'Geography & Map Division, Library of Congress, Washington, D.C.',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress / National Archives',
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd388:g3884:g3884r:cw0648000/full/pct:25/0/default.jpg',
    license: 'Public Domain',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.92,
    overlayOpacity: 0.45,
    promptSeed: 'Petersburg siege trenches Crater historical military map',
  },


  map_appomattox_retreat_lines: {
    src: '/images/cw_pictures/map_appomattox_retreat_lines_loc.jpg',
    kind: 'map',
    title: "Lee's Retreat Lines to Appomattox Station",
    location: 'Appomattox, Virginia',
    era: 'April 1865',
    bestFor: ['appomattox_decision', 'greensboro_convention'],
    caption: "Survey map mapping final retreat lines, Appomattox Station, and surrender geography.",
    credit: 'Geography & Map Division, Library of Congress, Washington, D.C.',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    sourceUrl: 'https://tile.loc.gov/image-services/iiif/service:gmd:gmd388:g3884:g3884a:cw0524000/full/pct:25/0/default.jpg',
    license: 'Public Domain',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.92,
    overlayOpacity: 0.45,
    promptSeed: 'Appomattox retreat lines station historical military map',
  },

  map_wilderness: {
    src: '/images/cw_pictures/map_wilderness_russell.jpg',
    kind: 'map',
    title: 'Spotsylvania & Wilderness Battlefield (Robert E. L. Russell Atlas)',
    location: 'Wilderness, Virginia',
    era: 'May 1864',
    bestFor: ['wilderness'],
    caption: "Robert E. L. Russell's 1935 Battle of the Wilderness Map (Plate 5: Orange Turnpike & Brock Road crossroads detailing Lee's 60,000 vs Grant's 120,000 troop lines).",
    credit: 'Geography & Map Division, Library of Congress, Robert E. L. Russell Atlas Collection (1935)',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    sourceUrl: 'https://loc.getarchive.net/media/battle-of-the-wilderness-may-5-6-and-7-1864-between-lee-60000-and-grant-120000-5',
    license: 'Public Domain',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.92,
    overlayOpacity: 0.45,
    promptSeed: 'Wilderness Spotsylvania historical military map Orange turnpike Brock road',
  },

  map_first_manassas: {
    src: '/images/cw_pictures/map_first_manassas.png',
    kind: 'map',
    title: 'Bull Run or First Manassas Tactical Map',
    location: 'Manassas, Virginia',
    era: 'July 1861',
    bestFor: ['manassas_battlefield'],
    caption: 'First Manassas tactical map candidate for Bull Run Creek, Henry House Hill, and Manassas Junction.',
    credit: 'American Battlefield Trust / Library of Congress map resource - exact local image source review needed',
    provenanceStatus: 'needs-review',
    sourceInstitution: 'American Battlefield Trust / Library of Congress Geography and Map Division',
    sourceUrl: 'https://www.battlefields.org/learn/maps/map-seat-war-battles-july-18th-21st-1861',
    license: 'Source page credits Library of Congress; exact local image source review needed',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.9,
    overlayOpacity: 0.45,
    promptSeed: 'First Manassas Bull Run Creek Henry House Hill historical tactical map',
  },

  map_second_manassas: {
    src: '/images/cw_pictures/map_second_manassas_aug30_movements.png',
    kind: 'map',
    title: 'Second Manassas Troop Movements, August 30, 1862',
    location: 'Prince William County, Virginia',
    era: 'August 1862',
    bestFor: ['second_manassas'],
    caption: 'Map of battle-field of Manassas, Virginia, giving positions and movements of troops on August 30, 1862.',
    credit: 'Library of Congress Geography and Map Division - Public Domain',
    provenanceStatus: 'verified',
    sourceInstitution: 'Library of Congress Geography and Map Division',
    sourceUrl: 'https://www.loc.gov/item/99439157/',
    license: 'Public Domain',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: true,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.9,
    overlayOpacity: 0.45,
    promptSeed: 'Second Manassas railway cut Longstreet flank historical tactical map',
  },

  map_seven_days: {
    src: '/images/cw_pictures/map_seven_days.png',
    kind: 'map',
    title: 'Seven Days Battles Tactical Map',
    location: 'Richmond Peninsula, Virginia',
    era: 'June-July 1862',
    bestFor: ['seven_days'],
    caption: 'Local tactical map candidate for the Seven Days battles around the Chickahominy and Richmond approaches.',
    credit: 'Local archive image - provenance review needed',
    provenanceStatus: 'needs-review',
    sourceInstitution: 'Local archive',
    sourceUrl: '',
    license: 'Provenance review needed',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.9,
    overlayOpacity: 0.45,
    promptSeed: 'Seven Days battles Richmond Chickahominy historical tactical map',
  },

  map_chancellorsville: {
    src: '/images/cw_pictures/map_chancellorsville.jpeg',
    kind: 'map',
    title: 'Chancellorsville Tactical Map',
    location: 'Spotsylvania County, Virginia',
    era: 'May 1863',
    bestFor: ['chancellorsville_aftermath'],
    caption: "Battlefield wayside map photographed on site, showing Chancellorsville, Wilderness crossings, and Jackson's flank march.",
    credit: 'On-site battlefield interpretive map photograph - project archive; underlying wayside rights need review',
    provenanceStatus: 'needs-review',
    sourceInstitution: 'Battlefield interpretive wayside / project archive',
    sourceUrl: '',
    license: 'Project photograph; underlying modern wayside map rights need review',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.9,
    overlayOpacity: 0.45,
    promptSeed: 'Chancellorsville Wilderness crossings Jackson flank march historical tactical map',
  },

  map_third_winchester: {
    src: '/images/cw_pictures/map_third_winchester.png',
    kind: 'map',
    title: 'Battles of Winchester Tactical Map',
    location: 'Winchester, Virginia',
    era: 'September 1864',
    bestFor: ['third_winchester'],
    caption: 'Local tactical map candidate for Winchester and Opequon Creek operations in the Shenandoah Valley.',
    credit: 'Local archive image - provenance review needed',
    provenanceStatus: 'needs-review',
    sourceInstitution: 'Local archive',
    sourceUrl: '',
    license: 'Provenance review needed',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.9,
    overlayOpacity: 0.45,
    promptSeed: 'Winchester Opequon Creek Shenandoah Valley historical tactical map',
  },

  map_first_winchester_reference: {
    src: '/images/cw_pictures/map_third_winchester.png',
    kind: 'map',
    title: 'First Winchester Valley Reference Map',
    location: 'Winchester, Virginia',
    era: 'May 1862',
    bestFor: ['first_winchester'],
    caption: 'Reference Shenandoah tactical map reused to orient the roads, creek lines, and approach sectors at First Winchester.',
    credit: 'Local archive image - provenance review needed',
    provenanceStatus: 'needs-review',
    sourceInstitution: 'Local archive',
    sourceUrl: '',
    license: 'Provenance review needed',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.9,
    overlayOpacity: 0.45,
    promptSeed: 'First Winchester Shenandoah Valley tactical reference map',
  },

  map_new_market_reference: {
    src: '/images/cw_pictures/map_third_winchester.png',
    kind: 'map',
    title: 'New Market Valley Reference Map',
    location: 'New Market, Virginia',
    era: 'May 1864',
    bestFor: ['new_market'],
    caption: 'Reference Shenandoah tactical map reused to frame Bushong Farm, the Valley Pike, and New Market approach roads.',
    credit: 'Local archive image - provenance review needed',
    provenanceStatus: 'needs-review',
    sourceInstitution: 'Local archive',
    sourceUrl: '',
    license: 'Provenance review needed',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.9,
    overlayOpacity: 0.45,
    promptSeed: 'New Market Bushong Farm Shenandoah Valley tactical reference map',
  },

  map_cedar_creek_reference: {
    src: '/images/cw_pictures/map_third_winchester.png',
    kind: 'map',
    title: 'Cedar Creek Valley Reference Map',
    location: 'Belle Grove / Middletown, Virginia',
    era: 'October 1864',
    bestFor: ['cedar_creek'],
    caption: 'Reference Shenandoah tactical map reused to frame Belle Grove, Middletown, and the Cedar Creek crossing sector.',
    credit: 'Local archive image - provenance review needed',
    provenanceStatus: 'needs-review',
    sourceInstitution: 'Local archive',
    sourceUrl: '',
    license: 'Provenance review needed',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.9,
    overlayOpacity: 0.45,
    promptSeed: 'Cedar Creek Belle Grove Shenandoah Valley tactical reference map',
  },

  map_virginia_campaigns_reference: {
    src: '/images/cw_pictures/map_virginia_campaigns_reference.jpeg',
    kind: 'map',
    title: 'Virginia Campaigns Reference Map',
    location: 'Virginia',
    era: '1861-1865',
    bestFor: ['fredericksburg_winter_politics'],
    caption: 'Broad battlefield reference map used as a temporary tactical underlay for the Fredericksburg-to-Chancellorsville winter hinge.',
    credit: 'On-site battlefield interpretive map photograph - project archive; underlying wayside rights need review',
    provenanceStatus: 'needs-review',
    sourceInstitution: 'Battlefield interpretive wayside / project archive',
    sourceUrl: '',
    license: 'Project photograph; underlying modern wayside map rights need review',
    historicalMedium: 'map',
    assetRoles: ['tactical-underlay', 'chronicle'],
    useInApp: false,
    cropFocus: { x: 0.5, y: 0.5 },
    cropMode: 'contain',
    theaterOpacity: 0.85,
    overlayOpacity: 0.35,
    promptSeed: 'Virginia Civil War campaign reference map',
  },

};

const PROCEDURAL_TACTICAL_MAP = {
  src: '',
  kind: 'procedural',
  title: 'Procedural Terrain Schematic',
  location: 'Scenario tactical sector',
  era: '1861–1865',
  bestFor: [],
  caption: 'Scenario-specific procedural terrain drawn from authored map annotations.',
  credit: 'Titans of War procedural tactical layer',
  provenanceStatus: 'needs-review',
  sourceInstitution: 'Titans of War',
  sourceUrl: '',
  license: 'Generated by game engine',
  historicalMedium: 'unknown',
  assetRoles: ['tactical-underlay'],
  useInApp: true,
  cropFocus: { x: 0.5, y: 0.5 },
  cropMode: 'contain',
  tacticalView: { focus: { x: 0.5, y: 0.5 }, zoom: 1 },
  theaterOpacity: 0,
  overlayOpacity: 0,
  promptSeed: 'procedural tactical terrain schematic',
  isProcedural: true,
};

function normalizeMediaAsset(assetKey, asset) {
  const provenanceStatus = asset.provenanceStatus || 'needs-review';
  return {
    ...LOCAL_ARCHIVE_PROVENANCE,
    ...asset,
    provenanceStatus,
    credit: provenanceStatus === 'verified'
      ? asset.credit
      : 'Local archive image - provenance review needed',
    assetKey,
  };
}

/** Maps each authored scenario id to its canonical media asset key. */
const SCENARIO_ASSET_MAP = {
  fort_sumter:              'battlefield_start_of_war',
  charleston_harbor_escape: 'harbor_escape_real_photo',
  radical_republican_crisis:'lincoln_cabinet_grok',
  naval_technology:         'hunley_project_art',
  shiloh_army_of_tennessee: 'shiloh_ai_gen',
  first_winchester:         'first_winchester_valley_reference',
  hotspur_cabinet_crisis:   'davis_cabinet_grok',
  fox_supply_crisis:        'art4',
  wolf_finance_crisis:      'art5',
  manassas_battlefield:     'ricketts_battery_first_manassas',
  seven_days:               'mcclellan_seven_days_grok',
  second_manassas:          'jackson_second_manassas_grok',
  potomac_leverage_campaign:'battlefield_md_campaign',
  antietam:                 'antietam_thulstrup_1887',
  emancipation_cabinet_debate:'lincoln_cabinet_grok',
  fredericksburg_winter_politics:'lee_at_fredericksburg',
  chancellorsville_maneuver:'lee_jackson_last_meeting',
  chancellorsville_aftermath:'battlefield_jackson_flank_march',
  gettysburg_campaign_setup:'battlefield4',
  gettysburg_with_jackson_setup:'x2_pennsylvania_campaign',
  gettysburg_with_jackson:  'gettysburg_thulstrup_1887',
  gettysburg_recognition_crisis:'csa_victory_condition_grok',
  susquehanna_offensive:    'battlefield4',
  gettysburg_decision:      'gettysburg_thulstrup_1887',
  chickamauga:              'chickamauga_close_battle_grok',
  atlanta_election_pressure:'davis_lee_war_room',
  atlanta_holds_october:    'davis_lee_war_room',
  fall_of_atlanta:          'atlanta_burning_grok',
  chattanooga_stranglehold: 'forrest_bragg_chattanooga_grok',
  wilderness_opening:       'lee_before_wilderness_grok',
  wilderness:               'grant_meade_overland_grok',
  cold_harbor:             'grant_overland_command',
  new_market:               'new_market_cadets_grok',
  black_confederate_debate: 'richmond_ct_parade_grok',
  third_winchester:         'third_winchester_grok',
  cedar_creek:              'cedar_creek_reenactment',
  election_1864_lincoln:    'lincoln_cabinet_grok',
  election_1864_mcclellan:  'mcclellan_armistice_grok',
  petersburg_siege:         'petersburg_ai_gen',
  five_forks:               'five_forks_generated_battle',
  richmond_evacuation:      'richmond_burns_grok',
  greensboro_convention:    'davis_lee_war_room',
  appomattox_decision:      'appomattox_ai_gen',
  southern_independence_1864:'davis_lee_war_room',
};

const SCENARIO_TACTICAL_ASSET_MAP = {
  fort_sumter: 'map_fort_sumter_charleston_harbor',
  charleston_harbor_escape: 'map_fort_sumter_charleston_harbor',
  radical_republican_crisis: 'map_fort_sumter_charleston_harbor',
  naval_technology: 'map_fort_sumter_charleston_harbor',
  shiloh_army_of_tennessee: 'map_shiloh_buell',
  first_winchester: 'map_first_winchester_reference',
  manassas_battlefield: 'map_first_manassas',
  second_manassas: 'map_second_manassas',
  seven_days: 'map_seven_days',
  antietam: 'map_antietam_sharpsburg',
  potomac_leverage_campaign: 'map_antietam_sharpsburg',
  emancipation_cabinet_debate: 'map_antietam_sharpsburg',
  fredericksburg_winter_politics: 'map_virginia_campaigns_reference',
  chancellorsville_maneuver: 'map_chancellorsville',
  chancellorsville_aftermath: 'map_chancellorsville',
  gettysburg_campaign_setup: 'map_gettysburg_cemetery_ridge',
  gettysburg_with_jackson_setup: 'map_gettysburg_cemetery_ridge',
  gettysburg_with_jackson: 'map_gettysburg_cemetery_ridge',
  gettysburg_recognition_crisis: 'map_gettysburg_cemetery_ridge',
  gettysburg_decision: 'map_gettysburg_cemetery_ridge',
  susquehanna_offensive: 'map_gettysburg_cemetery_ridge',
  black_confederate_debate: 'map_petersburg_crater',
  new_market: 'map_new_market_reference',
  third_winchester: 'map_third_winchester',
  cedar_creek: 'map_cedar_creek_reference',
  petersburg_siege: 'map_petersburg_crater',
  election_1864_lincoln: 'map_virginia_campaigns_reference',
  election_1864_mcclellan: 'map_virginia_campaigns_reference',
  richmond_evacuation: 'map_appomattox_retreat_lines',
  appomattox_decision: 'map_appomattox_retreat_lines',
  greensboro_convention: 'map_appomattox_retreat_lines',
  southern_independence_1864: 'map_virginia_campaigns_reference',
  wilderness_opening: 'map_wilderness',
  wilderness: 'map_wilderness',
  cold_harbor: 'map_wilderness',
};

/**
 * Scenario-specific framing adjustments layered on top of the canonical asset metadata.
 * This keeps theater and tactical placement sourced from one shared catalog instead of
 * letting BattlefieldMap drift with its own local tuning table.
 */
const SCENARIO_MEDIA_OVERRIDES = {
  fort_sumter: { tacticalView: { zoom: 1.18 } },
  naval_technology: { tacticalView: { zoom: 1.15 } },
  shiloh_army_of_tennessee: { tacticalView: { zoom: 1.08 } },
  manassas_battlefield: { tacticalView: { zoom: 1.08 } },
  second_manassas: { tacticalView: { zoom: 1.08 } },
  seven_days: { tacticalView: { zoom: 1.08 } },
  antietam: { tacticalView: { zoom: 1.16 } },
  fredericksburg_winter_politics: { tacticalView: { zoom: 1.04 } },
  black_confederate_debate: { tacticalView: { zoom: 1.14 } },
  chancellorsville_aftermath: { tacticalView: { zoom: 1.08 } },
  gettysburg_campaign_setup: { tacticalView: { zoom: 1.08 } },
  gettysburg_with_jackson_setup: { tacticalView: { zoom: 1.08 } },
  gettysburg_with_jackson: { tacticalView: { zoom: 1.08 } },
  chickamauga: { tacticalView: { zoom: 1.1 } },
  atlanta_election_pressure: { tacticalView: { zoom: 1.04 } },
  first_winchester: { tacticalView: { zoom: 1.08 } },
  new_market: { tacticalView: { zoom: 1.08 } },
  third_winchester: { tacticalView: { zoom: 1.08 } },
  cedar_creek: { tacticalView: { zoom: 1.08 } },
  wilderness: { tacticalView: { zoom: 1.1 } },
  cold_harbor: { tacticalView: { zoom: 1.12 } },
  petersburg_siege: { tacticalView: { zoom: 1.14 } },
  five_forks: { tacticalView: { zoom: 1.06 } },
  appomattox_decision: { tacticalView: { zoom: 1.12 } },
};

/**
 * Resolve the best media asset for a given scenario id.
 * Always returns a complete record — never null — so callers can use it unconditionally.
 *
 * @param {string} scenarioId
 * @returns {{ src: string, kind: string, title: string, caption: string, credit: string,
 *             cropFocus: {x:number, y:number}, tacticalView: {focus:{x:number,y:number}, zoom:number},
 *             theaterOpacity: number, overlayOpacity: number, promptSeed: string,
 *             assetKey: string, scenarioId: string }}
 */
export function resolveScenarioMedia(scenarioId) {
  const assetKey = SCENARIO_ASSET_MAP[scenarioId] || 'unknown';
  const asset = normalizeMediaAsset(assetKey, ASSETS[assetKey] || ASSETS.unknown);
  const override = SCENARIO_MEDIA_OVERRIDES[scenarioId] || {};
  const tacticalView = {
    focus: asset.cropFocus || { x: 0.5, y: 0.5 },
    zoom: 1,
    ...(asset.tacticalView || {}),
    ...(override.tacticalView || {}),
  };

  return {
    ...asset,
    ...override,
    tacticalView,
    scenarioId,
  };
}

export function resolveScenarioMediaSet(scenarioId) {
  const theater = resolveScenarioMedia(scenarioId);
  const tacticalAssetKey = SCENARIO_TACTICAL_ASSET_MAP[scenarioId];
  const override = SCENARIO_MEDIA_OVERRIDES[scenarioId] || {};
  const plannedTacticalMap = tacticalAssetKey && MEDIA_CATALOG[tacticalAssetKey]
    ? {
        ...MEDIA_CATALOG[tacticalAssetKey],
        tacticalView: {
          focus: MEDIA_CATALOG[tacticalAssetKey].cropFocus || { x: 0.5, y: 0.5 },
          zoom: 1,
          ...(MEDIA_CATALOG[tacticalAssetKey].tacticalView || {}),
          ...(override.tacticalView || {}),
        },
        scenarioId,
      }
    : null;
  const proceduralTacticalMap = {
    ...PROCEDURAL_TACTICAL_MAP,
    title: `${theater.title} Tactical Schematic`,
    location: theater.location,
    era: theater.era,
    tacticalView: {
      ...PROCEDURAL_TACTICAL_MAP.tacticalView,
      ...(override.tacticalView || {}),
    },
    scenarioId,
  };

  return {
    theater,
    tacticalMap: plannedTacticalMap?.useInApp ? plannedTacticalMap : proceduralTacticalMap,
    plannedTacticalMap,
    card: null,
  };
}

export function resolveCampaignEndingMedia(state) {
  const history = Array.isArray(state?.history) ? state.history : [];
  const lastEntry = history[history.length - 1] || null;
  const endingKey = `${lastEntry?.scenarioId || ''}:${lastEntry?.choiceId || ''}`;
  const endingAssetMap = {
    'southern_independence_1864:option_a': 'csa_victory_condition_grok',
    'southern_independence_1864:option_b': 'csa_victory_condition_grok',
    'southern_independence_1864:option_c': 'mcclellan_armistice_grok',
  };
  const assetKey = endingAssetMap[endingKey] || null;

  return assetKey ? normalizeMediaAsset(assetKey, ASSETS[assetKey] || ASSETS.unknown) : null;
}

/** Full catalog — exported for tooling (validator, benchmark reports, etc.) */
export const MEDIA_CATALOG = Object.fromEntries(
  Object.entries(ASSETS).map(([assetKey, asset]) => [assetKey, normalizeMediaAsset(assetKey, asset)])
);

/** Scenario → asset key mapping — exported for the content validator. */
export const SCENARIO_ASSET_MAP_EXPORT = SCENARIO_ASSET_MAP;
export const SCENARIO_TACTICAL_ASSET_MAP_EXPORT = SCENARIO_TACTICAL_ASSET_MAP;

/** Scenario → framing overrides — exported for the content validator. */
export const SCENARIO_MEDIA_OVERRIDES_EXPORT = SCENARIO_MEDIA_OVERRIDES;
