import React, { useState } from 'react';
import { Image as ImageIcon, Map } from 'lucide-react';
import { resolveScenarioMedia } from '../game/mediaCatalog.js';
import BattlefieldMap from './BattlefieldMap.jsx';

/**
 * ScenarioTheater — Cinematic scenario header with dual view modes.
 *
 * Replaces the old 160px card grid + BattlefieldMap pair.
 *
 * PHOTO mode  — Full-width historical period image at high opacity.
 *               Caption, credit, and card-art thumbnail overlaid.
 * TACTICAL mode — Existing BattlefieldMap canvas (photo underlay + tactical drawing).
 *
 * Description is always shown below the visual panel in both modes.
 *
 * Props:
 *   scenario         — active scenario object from STATIC_SCENARIOS
 *   gameState        — current campaign state ({ actor, roleLabel, … })
 *   selectedChoiceId — id of the player's currently selected choice (for arrow animation)
 */
export default function ScenarioTheater({ scenario, gameState, selectedChoiceId }) {
  const [mode, setMode] = useState('photo');
  const catalogMedia = resolveScenarioMedia(scenario?.id);
  const useScenarioArt = catalogMedia.assetKey === 'unknown' && scenario?.image;
  const media = useScenarioArt
    ? {
        ...catalogMedia,
        src: scenario.image,
        kind: 'generated-art',
        title: `${scenario?.title || 'Scenario'} Art`,
        caption: 'AI-created Titans of War scenario art for this campaign decision.',
        credit: 'Generated by Titans Forge for Titans of War',
        provenanceStatus: 'verified',
        historicalMedium: 'generated-art',
        license: 'MIT project media',
        cropMode: 'wide',
        theaterOpacity: 0.94,
      }
    : catalogMedia;
  const heroHeight = media.cropMode === 'portrait'
    ? 'clamp(320px, 48vw, 420px)'
    : 'clamp(260px, 36vw, 360px)';
  const heroObjectFit = media.cropMode === 'contain' ? 'contain' : 'cover';

  const btnBase = {
    fontFamily: 'var(--font-mono)',
    fontSize: '0.58rem',
    letterSpacing: '1.5px',
    padding: '3px 9px',
    borderRadius: '3px',
    cursor: 'pointer',
    textTransform: 'uppercase',
    transition: 'background 0.15s, border-color 0.15s',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
  };

  const btnActive = {
    ...btnBase,
    background: 'rgba(212,175,55,0.18)',
    border: '1px solid var(--accent-gold)',
    color: 'var(--accent-gold)',
  };

  const btnInactive = {
    ...btnBase,
    background: 'rgba(0,0,0,0.55)',
    border: '1px solid rgba(255,255,255,0.08)',
    color: 'var(--text-secondary)',
  };

  const kindLabel = media.provenanceStatus !== 'verified' ? 'LOCAL ARCHIVE' :
    media.kind === 'reenactment' ? 'RE-ENACTMENT' :
    media.kind === 'art'         ? 'PERIOD ART' :
    media.kind === 'generated-art' ? 'SCENARIO ART' :
    media.kind === 'map'         ? 'TACTICAL MAP' :
    media.kind === 'battlefield' ? 'THEATER PHOTO' :
                                   'HISTORICAL RECORD';

  return (
    <div style={{ marginBottom: '1.25rem' }}>

      {/* ── Scenario identity row (always visible) ────────────────── */}
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '0.5rem', gap: '0.75rem' }}>
        <div>
          <h2 style={{ fontSize: '1.15rem', fontWeight: 'bold', color: 'var(--text-primary)', lineHeight: 1.2, marginBottom: '0.2rem' }}>
            {scenario?.title}
          </h2>
          <div style={{ fontSize: '0.7rem', fontFamily: 'var(--font-mono)', color: 'var(--accent-gold)', textTransform: 'uppercase', letterSpacing: '1px' }}>
            {gameState?.actor} — {gameState?.roleLabel}
          </div>
        </div>

        {/* View mode toggle */}
        <div style={{ display: 'flex', gap: '4px', flexShrink: 0, paddingTop: '2px' }}>
          <button onClick={() => setMode('tactical')} style={mode === 'tactical' ? btnActive : btnInactive}>
            <Map size={13} strokeWidth={1.8} aria-hidden="true" /> Map
          </button>
          <button onClick={() => setMode('photo')} style={mode === 'photo' ? btnActive : btnInactive}>
            <ImageIcon size={13} strokeWidth={1.8} aria-hidden="true" /> Image
          </button>
        </div>
      </div>

      {/* ── Visual panel ──────────────────────────────────────────── */}
      {mode === 'photo' ? (
        <div style={{
          position: 'relative',
          width: '100%',
          height: heroHeight,
          borderRadius: '6px',
          overflow: 'hidden',
          border: '1px solid var(--border-color)',
          background: '#090c10',
        }}>

          {/* Historical image */}
          <img
            src={media.src}
            alt={media.title}
            style={{
              width: '100%',
              height: '100%',
              objectFit: heroObjectFit,
              objectPosition: `${media.cropFocus.x * 100}% ${media.cropFocus.y * 100}%`,
              opacity: media.theaterOpacity,
            }}
          />

          {/* Bottom gradient for text legibility */}
          <div style={{
            position: 'absolute',
            inset: 0,
            background: 'linear-gradient(to top, rgba(9,12,16,0.88) 0%, rgba(9,12,16,0.25) 55%, rgba(9,12,16,0.0) 100%)',
            pointerEvents: 'none',
          }} />

          {/* Top-left: asset kind badge */}
          <div style={{
            position: 'absolute',
            top: '8px',
            left: '8px',
            fontFamily: 'var(--font-mono)',
            fontSize: '0.56rem',
            color: 'rgba(212,175,55,0.6)',
            background: 'rgba(9,12,16,0.72)',
            padding: '2px 7px',
            border: '1px solid rgba(212,175,55,0.12)',
            borderRadius: '3px',
            letterSpacing: '1px',
            textTransform: 'uppercase',
          }}>
            {kindLabel}
          </div>

          {/* Bottom-left: caption + credit */}
          <div style={{ position: 'absolute', bottom: 0, left: 0, right: scenario?.image ? '66px' : '8px', padding: '0.65rem 0.9rem' }}>
            {media.caption && (
              <div style={{ fontSize: '0.63rem', color: 'rgba(212,175,55,0.8)', fontStyle: 'italic', lineHeight: 1.35, marginBottom: '0.1rem' }}>
                {media.caption}
              </div>
            )}
            {media.credit && (
              <div style={{ fontSize: '0.58rem', color: 'rgba(156,163,175,0.45)', letterSpacing: '0.3px' }}>
                {media.credit}
              </div>
            )}
          </div>

          {/* Bottom-right: card art thumbnail */}
          {scenario?.image && (
            <div style={{
              position: 'absolute',
              bottom: '8px',
              right: '8px',
              width: '50px',
              height: '50px',
              borderRadius: '4px',
              overflow: 'hidden',
              border: '1px solid rgba(212,175,55,0.22)',
              boxShadow: '0 2px 8px rgba(0,0,0,0.55)',
            }}>
              <img src={scenario.image} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            </div>
          )}
        </div>
      ) : (
        /* ── Tactical canvas (existing BattlefieldMap) ────────────── */
        <BattlefieldMap
          scenarioId={scenario?.id}
          selectedChoiceId={selectedChoiceId}
        />
      )}

      {/* ── Description — always visible below the visual panel ───── */}
      <p style={{
        fontSize: '0.85rem',
        lineHeight: '1.45',
        color: 'var(--text-secondary)',
        marginTop: '0.85rem',
        marginBottom: 0,
      }}>
        {scenario?.description}
      </p>
    </div>
  );
}
